<?php

use Illuminate\Database\Seeder;

class AccountChangeTypePastTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('account_change_type_past')->delete();
        
        \DB::table('account_change_type_past')->insert(array (
            0 => 
            array (
                'id' => 1,
                'name' => '充值',
                'sign' => 'recharge',
                'type' => 1,
                'amount' => 1,
                'user_id' => 1,
                'project_id' => 0,
                'lottery_id' => 0,
                'method_id' => 0,
                'issue' => 0,
                'from_id' => 0,
                'from_admin_id' => 0,
                'to_id' => 0,
                'frozen_type' => 0,
                'activity_sign' => 0,
                'admin_id' => 0,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            1 => 
            array (
                'id' => 2,
                'name' => '投注返点',
                'sign' => 'point_from_bet',
                'type' => 1,
                'amount' => 1,
                'user_id' => 1,
                'project_id' => 1,
                'lottery_id' => 1,
                'method_id' => 1,
                'issue' => 1,
                'from_id' => 0,
                'from_admin_id' => 0,
                'to_id' => 0,
                'frozen_type' => 0,
                'activity_sign' => 0,
                'admin_id' => 0,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            2 => 
            array (
                'id' => 3,
                'name' => '下级返点',
                'sign' => 'point_from_child',
                'type' => 1,
                'amount' => 1,
                'user_id' => 1,
                'project_id' => 1,
                'lottery_id' => 1,
                'method_id' => 1,
                'issue' => 1,
                'from_id' => 1,
                'from_admin_id' => 1,
                'to_id' => 0,
                'frozen_type' => 0,
                'activity_sign' => 0,
                'admin_id' => 0,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            3 => 
            array (
                'id' => 4,
                'name' => '游戏奖金',
                'sign' => 'game_bonus',
                'type' => 1,
                'amount' => 1,
                'user_id' => 1,
                'project_id' => 1,
                'lottery_id' => 1,
                'method_id' => 1,
                'issue' => 1,
                'from_id' => 0,
                'from_admin_id' => 0,
                'to_id' => 0,
                'frozen_type' => 0,
                'activity_sign' => 0,
                'admin_id' => 0,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            4 => 
            array (
                'id' => 5,
                'name' => '撤单返款',
                'sign' => 'cancel_order',
                'type' => 1,
                'amount' => 1,
                'user_id' => 1,
                'project_id' => 1,
                'lottery_id' => 1,
                'method_id' => 1,
                'issue' => 1,
                'from_id' => 0,
                'from_admin_id' => 0,
                'to_id' => 0,
                'frozen_type' => 2,
                'activity_sign' => 0,
                'admin_id' => 0,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            5 => 
            array (
                'id' => 6,
                'name' => '活动礼金',
                'sign' => 'gift',
                'type' => 1,
                'amount' => 1,
                'user_id' => 1,
                'project_id' => 0,
                'lottery_id' => 0,
                'method_id' => 0,
                'issue' => 0,
                'from_id' => 0,
                'from_admin_id' => 0,
                'to_id' => 0,
                'frozen_type' => 0,
                'activity_sign' => 1,
                'admin_id' => 0,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            6 => 
            array (
                'id' => 7,
                'name' => '上级充值',
                'sign' => 'recharge_from_parent',
                'type' => 1,
                'amount' => 1,
                'user_id' => 1,
                'project_id' => 0,
                'lottery_id' => 0,
                'method_id' => 0,
                'issue' => 0,
                'from_id' => 1,
                'from_admin_id' => 0,
                'to_id' => 0,
                'frozen_type' => 0,
                'activity_sign' => 0,
                'admin_id' => 0,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            7 => 
            array (
                'id' => 8,
                'name' => '系统活动转账',
                'sign' => 'system_claim',
                'type' => 1,
                'amount' => 1,
                'user_id' => 1,
                'project_id' => 0,
                'lottery_id' => 0,
                'method_id' => 0,
                'issue' => 0,
                'from_id' => 0,
                'from_admin_id' => 1,
                'to_id' => 0,
                'frozen_type' => 0,
                'activity_sign' => 0,
                'admin_id' => 0,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            8 => 
            array (
                'id' => 9,
                'name' => '日工资',
                'sign' => 'day_salary',
                'type' => 1,
                'amount' => 1,
                'user_id' => 1,
                'project_id' => 0,
                'lottery_id' => 0,
                'method_id' => 0,
                'issue' => 0,
                'from_id' => 0,
                'from_admin_id' => 0,
                'to_id' => 0,
                'frozen_type' => 0,
                'activity_sign' => 0,
                'admin_id' => 0,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            9 => 
            array (
                'id' => 10,
                'name' => '上级分红',
                'sign' => 'dividend_from_parent',
                'type' => 1,
                'amount' => 1,
                'user_id' => 1,
                'project_id' => 0,
                'lottery_id' => 0,
                'method_id' => 0,
                'issue' => 0,
                'from_id' => 1,
                'from_admin_id' => 0,
                'to_id' => 0,
                'frozen_type' => 0,
                'activity_sign' => 0,
                'admin_id' => 0,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            10 => 
            array (
                'id' => 11,
                'name' => '提现解冻',
                'sign' => 'withdraw_un_frozen',
                'type' => 1,
                'amount' => 1,
                'user_id' => 1,
                'project_id' => 0,
                'lottery_id' => 0,
                'method_id' => 0,
                'issue' => 0,
                'from_id' => 0,
                'from_admin_id' => 0,
                'to_id' => 0,
                'frozen_type' => 2,
                'activity_sign' => 0,
                'admin_id' => 0,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            11 => 
            array (
                'id' => 12,
                'name' => '提现冻结',
                'sign' => 'withdraw_frozen',
                'type' => 2,
                'amount' => 1,
                'user_id' => 1,
                'project_id' => 0,
                'lottery_id' => 0,
                'method_id' => 0,
                'issue' => 0,
                'from_id' => 0,
                'from_admin_id' => 0,
                'to_id' => 0,
                'frozen_type' => 1,
                'activity_sign' => 0,
                'admin_id' => 0,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            12 => 
            array (
                'id' => 13,
                'name' => '提现成功',
                'sign' => 'withdraw_finish',
                'type' => 2,
                'amount' => 1,
                'user_id' => 1,
                'project_id' => 0,
                'lottery_id' => 0,
                'method_id' => 0,
                'issue' => 0,
                'from_id' => 0,
                'from_admin_id' => 0,
                'to_id' => 0,
                'frozen_type' => 4,
                'activity_sign' => 0,
                'admin_id' => 0,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            13 => 
            array (
                'id' => 14,
                'name' => '投注扣款',
                'sign' => 'bet_cost',
                'type' => 2,
                'amount' => 1,
                'user_id' => 1,
                'project_id' => 1,
                'lottery_id' => 1,
                'method_id' => 1,
                'issue' => 1,
                'from_id' => 0,
                'from_admin_id' => 0,
                'to_id' => 0,
                'frozen_type' => 1,
                'activity_sign' => 0,
                'admin_id' => 0,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            14 => 
            array (
                'id' => 15,
                'name' => '追号扣款',
                'sign' => 'trace_cost',
                'type' => 2,
                'amount' => 1,
                'user_id' => 1,
                'project_id' => 1,
                'lottery_id' => 1,
                'method_id' => 1,
                'issue' => 1,
                'from_id' => 0,
                'from_admin_id' => 0,
                'to_id' => 0,
                'frozen_type' => 4,
                'activity_sign' => 0,
                'admin_id' => 0,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            15 => 
            array (
                'id' => 16,
                'name' => '真实扣款',
                'sign' => 'real_cost',
                'type' => 2,
                'amount' => 1,
                'user_id' => 1,
                'project_id' => 1,
                'lottery_id' => 1,
                'method_id' => 1,
                'issue' => 1,
                'from_id' => 0,
                'from_admin_id' => 0,
                'to_id' => 0,
                'frozen_type' => 4,
                'activity_sign' => 0,
                'admin_id' => 0,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            16 => 
            array (
                'id' => 17,
                'name' => '撤销返点',
                'sign' => 'cancel_point',
                'type' => 2,
                'amount' => 1,
                'user_id' => 1,
                'project_id' => 1,
                'lottery_id' => 1,
                'method_id' => 1,
                'issue' => 1,
                'from_id' => 0,
                'from_admin_id' => 0,
                'to_id' => 0,
                'frozen_type' => 0,
                'activity_sign' => 0,
                'admin_id' => 0,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            17 => 
            array (
                'id' => 18,
                'name' => '撤销派奖',
                'sign' => 'cancel_bonus',
                'type' => 2,
                'amount' => 1,
                'user_id' => 1,
                'project_id' => 1,
                'lottery_id' => 1,
                'method_id' => 1,
                'issue' => 1,
                'from_id' => 0,
                'from_admin_id' => 0,
                'to_id' => 0,
                'frozen_type' => 0,
                'activity_sign' => 0,
                'admin_id' => 0,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            18 => 
            array (
                'id' => 19,
                'name' => '撤单手续费',
                'sign' => 'cancel_fee',
                'type' => 2,
                'amount' => 1,
                'user_id' => 1,
                'project_id' => 1,
                'lottery_id' => 1,
                'method_id' => 1,
                'issue' => 1,
                'from_id' => 0,
                'from_admin_id' => 0,
                'to_id' => 0,
                'frozen_type' => 0,
                'activity_sign' => 0,
                'admin_id' => 0,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            19 => 
            array (
                'id' => 20,
                'name' => '为下级充值',
                'sign' => 'recharge_to_child',
                'type' => 2,
                'amount' => 1,
                'user_id' => 1,
                'project_id' => 0,
                'lottery_id' => 0,
                'method_id' => 0,
                'issue' => 0,
                'from_id' => 0,
                'from_admin_id' => 0,
                'to_id' => 1,
                'frozen_type' => 0,
                'activity_sign' => 0,
                'admin_id' => 0,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            20 => 
            array (
                'id' => 21,
                'name' => '系统扣减',
                'sign' => 'system_reduce',
                'type' => 2,
                'amount' => 1,
                'user_id' => 1,
                'project_id' => 0,
                'lottery_id' => 0,
                'method_id' => 0,
                'issue' => 0,
                'from_id' => 0,
                'from_admin_id' => 1,
                'to_id' => 0,
                'frozen_type' => 0,
                'activity_sign' => 0,
                'admin_id' => 0,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            21 => 
            array (
                'id' => 22,
                'name' => '分红给下级',
                'sign' => 'dividend_to_child',
                'type' => 2,
                'amount' => 1,
                'user_id' => 1,
                'project_id' => 0,
                'lottery_id' => 0,
                'method_id' => 0,
                'issue' => 0,
                'from_id' => 0,
                'from_admin_id' => 0,
                'to_id' => 1,
                'frozen_type' => 0,
                'activity_sign' => 0,
                'admin_id' => 0,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            22 => 
            array (
                'id' => 23,
                'name' => '奖金限额扣除',
                'sign' => 'bonus_limit_reduce',
                'type' => 2,
                'amount' => 1,
                'user_id' => 1,
                'project_id' => 0,
                'lottery_id' => 0,
                'method_id' => 0,
                'issue' => 0,
                'from_id' => 0,
                'from_admin_id' => 0,
                'to_id' => 0,
                'frozen_type' => 0,
                'activity_sign' => 0,
                'admin_id' => 0,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
        ));
        
        
    }
}