<?php

use Illuminate\Database\Seeder;

class AdminMenusTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('admin_menus')->delete();
        
        \DB::table('admin_menus')->insert(array (
            0 => 
            array (
                'id' => 1000,
                'pid' => 0,
                'rid' => '',
                'title' => '系统管理',
                'route' => '',
                'api_path' => '',
                'sort' => 2,
                'css_class' => 'fa fa-lg fa-fw fa-cog',
                'type' => 0,
                'level' => 1,
                'status' => 1,
                'admin_id' => 0,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            1 => 
            array (
                'id' => 1100,
                'pid' => 1000,
                'rid' => '1000|1100',
                'title' => '配置列表',
                'route' => 'configureList',
                'api_path' => 'system/configure-list',
                'sort' => 0,
                'css_class' => '',
                'type' => 0,
                'level' => 1,
                'status' => 1,
                'admin_id' => 0,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            2 => 
            array (
                'id' => 1101,
                'pid' => 1100,
                'rid' => '1000|1100|1101',
                'title' => '添加配置',
                'route' => 'configureAdd',
                'api_path' => 'system/configure-add',
                'sort' => 0,
                'css_class' => 'fa fa-lg fa-fw fa-plus',
                'type' => 1,
                'level' => 1,
                'status' => 1,
                'admin_id' => 0,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            3 => 
            array (
                'id' => 1102,
                'pid' => 1100,
                'rid' => '1000|1100|1102',
                'title' => '配置详情',
                'route' => 'configureDetail',
                'api_path' => 'system/configure-detail',
                'sort' => 0,
                'css_class' => '',
                'type' => 1,
                'level' => 1,
                'status' => 1,
                'admin_id' => 0,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            4 => 
            array (
                'id' => 1103,
                'pid' => 1100,
                'rid' => '1000|1100|1103',
                'title' => '配置状态',
                'route' => 'configureStatus',
                'api_path' => 'system/configure-status',
                'sort' => 0,
                'css_class' => '',
                'type' => 1,
                'level' => 1,
                'status' => 1,
                'admin_id' => 0,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            5 => 
            array (
                'id' => 1104,
                'pid' => 1100,
                'rid' => '1000|1100|1104',
                'title' => '刷新配置',
                'route' => 'configureFlush',
                'api_path' => 'system/configure-flush',
                'sort' => 0,
                'css_class' => 'fa fa-lg fa-fw fa-plus',
                'type' => 1,
                'level' => 1,
                'status' => 1,
                'admin_id' => 0,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            6 => 
            array (
                'id' => 1300,
                'pid' => 1000,
                'rid' => '1000|1300',
                'title' => '后台日志',
                'route' => 'adminAccessLog',
                'api_path' => 'system/admin-log-list',
                'sort' => 0,
                'css_class' => '',
                'type' => 0,
                'level' => 1,
                'status' => 1,
                'admin_id' => 0,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            7 => 
            array (
                'id' => 1500,
                'pid' => 1000,
                'rid' => '1000|1500',
                'title' => '缓存管理',
                'route' => 'cacheList',
                'api_path' => 'system/cache-list',
                'sort' => 0,
                'css_class' => '',
                'type' => 0,
                'level' => 1,
                'status' => 1,
                'admin_id' => 0,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            8 => 
            array (
                'id' => 1501,
                'pid' => 1500,
                'rid' => '1000|1500|1501',
                'title' => '刷新缓存',
                'route' => 'cacheFlush',
                'api_path' => 'system/cache-flush',
                'sort' => 0,
                'css_class' => '',
                'type' => 1,
                'level' => 1,
                'status' => 1,
                'admin_id' => 0,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            9 => 
            array (
                'id' => 1502,
                'pid' => 1500,
                'rid' => '1000|1500|1502',
                'title' => '刷新所有缓存',
                'route' => 'cacheFlushAll',
                'api_path' => 'system/cache-flush-all',
                'sort' => 0,
                'css_class' => '',
                'type' => 1,
                'level' => 1,
                'status' => 1,
                'admin_id' => 0,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            10 => 
            array (
                'id' => 2000,
                'pid' => 0,
                'rid' => '',
                'title' => '游戏管理',
                'route' => '',
                'api_path' => '',
                'sort' => 3,
                'css_class' => 'fa fa-lg fa-fw fa-gamepad',
                'type' => 0,
                'level' => 1,
                'status' => 1,
                'admin_id' => 0,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            11 => 
            array (
                'id' => 2100,
                'pid' => 2000,
                'rid' => '2000|2100',
                'title' => '游戏列表',
                'route' => 'lotteryList',
                'api_path' => 'game/lottery-list',
                'sort' => 1,
                'css_class' => '',
                'type' => 0,
                'level' => 1,
                'status' => 1,
                'admin_id' => 0,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            12 => 
            array (
                'id' => 2101,
                'pid' => 2100,
                'rid' => '2000|2100|2101',
                'title' => '添加游戏',
                'route' => 'lotteryAdd',
                'api_path' => 'game/lottery-add',
                'sort' => 0,
                'css_class' => 'fa fa-lg fa-fw fa-plus',
                'type' => 1,
                'level' => 1,
                'status' => 1,
                'admin_id' => 0,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            13 => 
            array (
                'id' => 2102,
                'pid' => 2100,
                'rid' => '2000|2100|2102',
                'title' => '游戏状态',
                'route' => 'lotteryStatus',
                'api_path' => 'game/lottery-status',
                'sort' => 0,
                'css_class' => '',
                'type' => 1,
                'level' => 1,
                'status' => 1,
                'admin_id' => 0,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            14 => 
            array (
                'id' => 2103,
                'pid' => 2100,
                'rid' => '2000|2100|2103',
                'title' => '删除游戏',
                'route' => 'lotteryDel',
                'api_path' => 'game/lottery-del',
                'sort' => 0,
                'css_class' => '',
                'type' => 1,
                'level' => 1,
                'status' => 1,
                'admin_id' => 0,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            15 => 
            array (
                'id' => 2104,
                'pid' => 2100,
                'rid' => '2000|2100|2104',
                'title' => '刷新缓存',
                'route' => 'lotteryFlush',
                'api_path' => 'game/lottery-flush',
                'sort' => 0,
                'css_class' => '',
                'type' => 1,
                'level' => 1,
                'status' => 1,
                'admin_id' => 0,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            16 => 
            array (
                'id' => 2200,
                'pid' => 2000,
                'rid' => '2000|2200',
                'title' => '玩法列表',
                'route' => 'methodList',
                'api_path' => 'game/method-list',
                'sort' => 2,
                'css_class' => '',
                'type' => 0,
                'level' => 1,
                'status' => 1,
                'admin_id' => 0,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            17 => 
            array (
                'id' => 2201,
                'pid' => 2200,
                'rid' => '2000|2200|2201',
                'title' => '玩法状态',
                'route' => 'methodStatus',
                'api_path' => 'game/method-status',
                'sort' => 0,
                'css_class' => '',
                'type' => 1,
                'level' => 1,
                'status' => 1,
                'admin_id' => 0,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            18 => 
            array (
                'id' => 2300,
                'pid' => 2000,
                'rid' => '2000|2300',
                'title' => '奖期列表',
                'route' => 'issueList',
                'api_path' => 'game/issue-list',
                'sort' => 3,
                'css_class' => '',
                'type' => 0,
                'level' => 1,
                'status' => 1,
                'admin_id' => 0,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            19 => 
            array (
                'id' => 2301,
                'pid' => 2300,
                'rid' => '2000|2300|2301',
                'title' => '生成奖期',
                'route' => 'issueGen',
                'api_path' => 'game/issue-gen',
                'sort' => 0,
                'css_class' => '',
                'type' => 1,
                'level' => 1,
                'status' => 1,
                'admin_id' => 0,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            20 => 
            array (
                'id' => 2302,
                'pid' => 2300,
                'rid' => '2000|2300|2302',
                'title' => '录号',
                'route' => 'issueEncode',
                'api_path' => 'game/issue-encode',
                'sort' => 0,
                'css_class' => '',
                'type' => 1,
                'level' => 1,
                'status' => 1,
                'admin_id' => 0,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            21 => 
            array (
                'id' => 2303,
                'pid' => 2300,
                'rid' => '2000|2300|2303',
                'title' => '计奖',
                'route' => 'issueCalculated',
                'api_path' => 'igame/issue-calculated',
                'sort' => 0,
                'css_class' => '',
                'type' => 1,
                'level' => 1,
                'status' => 1,
                'admin_id' => 0,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            22 => 
            array (
                'id' => 2304,
                'pid' => 2300,
                'rid' => '2000|2300|2304',
                'title' => '派奖',
                'route' => 'issuePrize',
                'api_path' => 'game/issue-prize',
                'sort' => 0,
                'css_class' => '',
                'type' => 1,
                'level' => 1,
                'status' => 1,
                'admin_id' => 0,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            23 => 
            array (
                'id' => 2305,
                'pid' => 2300,
                'rid' => '2000|2300|2305',
                'title' => '追号',
                'route' => 'issueTrace',
                'api_path' => 'game/issue-trace',
                'sort' => 0,
                'css_class' => '',
                'type' => 1,
                'level' => 1,
                'status' => 1,
                'admin_id' => 0,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            24 => 
            array (
                'id' => 2306,
                'pid' => 2300,
                'rid' => '2000|2300|2306',
                'title' => '详情',
                'route' => 'issueDetail',
                'api_path' => 'game/issue-detail',
                'sort' => 0,
                'css_class' => '',
                'type' => 1,
                'level' => 1,
                'status' => 1,
                'admin_id' => 0,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            25 => 
            array (
                'id' => 2400,
                'pid' => 2000,
                'rid' => '2000|2400',
                'title' => '奖期规则',
                'route' => 'issueRuleList',
                'api_path' => 'game/issue-rule-list',
                'sort' => 4,
                'css_class' => '',
                'type' => 0,
                'level' => 1,
                'status' => 1,
                'admin_id' => 0,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            26 => 
            array (
                'id' => 2401,
                'pid' => 2400,
                'rid' => '2000|2400|2401',
                'title' => '添加规则',
                'route' => 'issueRuleAdd',
                'api_path' => 'game/issue-rule-add',
                'sort' => 0,
                'css_class' => '',
                'type' => 1,
                'level' => 1,
                'status' => 1,
                'admin_id' => 0,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            27 => 
            array (
                'id' => 2402,
                'pid' => 2400,
                'rid' => '2000|2400|2402',
                'title' => '删除规则',
                'route' => 'issueRuleDel',
                'api_path' => 'game/issue-rule-del',
                'sort' => 0,
                'css_class' => '',
                'type' => 1,
                'level' => 1,
                'status' => 1,
                'admin_id' => 0,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            28 => 
            array (
                'id' => 2500,
                'pid' => 2000,
                'rid' => '2000|2500',
                'title' => '追号列表',
                'route' => 'traceList',
                'api_path' => 'game/trace-list',
                'sort' => 6,
                'css_class' => '',
                'type' => 0,
                'level' => 1,
                'status' => 1,
                'admin_id' => 0,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            29 => 
            array (
                'id' => 2501,
                'pid' => 2500,
                'rid' => '2000|2500|2501',
                'title' => '玩法状态',
                'route' => 'traceDetail',
                'api_path' => 'game/trace-detail',
                'sort' => 0,
                'css_class' => '',
                'type' => 1,
                'level' => 1,
                'status' => 1,
                'admin_id' => 0,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            30 => 
            array (
                'id' => 2600,
                'pid' => 2000,
                'rid' => '2000|2600',
                'title' => '投注列表',
                'route' => 'projectList',
                'api_path' => 'game/project-list',
                'sort' => 5,
                'css_class' => '',
                'type' => 0,
                'level' => 1,
                'status' => 1,
                'admin_id' => 0,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            31 => 
            array (
                'id' => 2601,
                'pid' => 2600,
                'rid' => '2000|2600|2601',
                'title' => '投注详情',
                'route' => 'projectDetail',
                'api_path' => 'game/project-detail',
                'sort' => 0,
                'css_class' => '',
                'type' => 1,
                'level' => 1,
                'status' => 1,
                'admin_id' => 0,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            32 => 
            array (
                'id' => 2602,
                'pid' => 2600,
                'rid' => '2000|2600|2602',
                'title' => '撤单',
                'route' => 'projectCancel',
                'api_path' => 'game/project-cancel',
                'sort' => 0,
                'css_class' => '',
                'type' => 1,
                'level' => 1,
                'status' => 1,
                'admin_id' => 0,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            33 => 
            array (
                'id' => 3000,
                'pid' => 0,
                'rid' => '',
                'title' => '玩家管理',
                'route' => '',
                'api_path' => '',
                'sort' => 4,
                'css_class' => 'fa fa-lg fa-fw fa-user-md',
                'type' => 0,
                'level' => 1,
                'status' => 1,
                'admin_id' => 0,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            34 => 
            array (
                'id' => 3100,
                'pid' => 3000,
                'rid' => '3000|3100',
                'title' => '玩家列表',
                'route' => 'playerList',
                'api_path' => 'player/player-list',
                'sort' => 1,
                'css_class' => '',
                'type' => 0,
                'level' => 1,
                'status' => 1,
                'admin_id' => 0,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            35 => 
            array (
                'id' => 3101,
                'pid' => 3100,
                'rid' => '3000|3100|3101',
                'title' => '添加总代',
                'route' => 'playerAdd',
                'api_path' => 'player/player-add',
                'sort' => 0,
                'css_class' => '',
                'type' => 1,
                'level' => 1,
                'status' => 1,
                'admin_id' => 0,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            36 => 
            array (
                'id' => 3102,
                'pid' => 3100,
                'rid' => '3000|3100|3102',
                'title' => '玩家资金',
                'route' => 'playerFund',
                'api_path' => 'player/player-fund',
                'sort' => 0,
                'css_class' => '',
                'type' => 1,
                'level' => 1,
                'status' => 1,
                'admin_id' => 0,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            37 => 
            array (
                'id' => 3103,
                'pid' => 3100,
                'rid' => '3000|3100|3103',
                'title' => '玩家冻结',
                'route' => 'playerFrozen',
                'api_path' => 'player/player-frozen',
                'sort' => 0,
                'css_class' => '',
                'type' => 1,
                'level' => 1,
                'status' => 1,
                'admin_id' => 0,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            38 => 
            array (
                'id' => 3104,
                'pid' => 3100,
                'rid' => '3000|3100|3104',
                'title' => '玩家设置',
                'route' => 'playerSetting',
                'api_path' => 'player/player-setting',
                'sort' => 0,
                'css_class' => '',
                'type' => 1,
                'level' => 1,
                'status' => 1,
                'admin_id' => 0,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            39 => 
            array (
                'id' => 3105,
                'pid' => 3100,
                'rid' => '3000|3100|3105',
                'title' => '玩家密码',
                'route' => 'playerPassword',
                'api_path' => 'player/player-password',
                'sort' => 0,
                'css_class' => '',
                'type' => 1,
                'level' => 1,
                'status' => 1,
                'admin_id' => 0,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            40 => 
            array (
                'id' => 3106,
                'pid' => 3100,
                'rid' => '3000|3100|3106',
                'title' => '玩家密码',
                'route' => 'playerDetail',
                'api_path' => 'player/player-detail',
                'sort' => 0,
                'css_class' => '',
                'type' => 1,
                'level' => 1,
                'status' => 1,
                'admin_id' => 0,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            41 => 
            array (
                'id' => 3300,
                'pid' => 3000,
                'rid' => '3000|3300',
                'title' => '__银行卡',
                'route' => 'playerCardList',
                'api_path' => 'player/player-card-list',
                'sort' => 3,
                'css_class' => '',
                'type' => 0,
                'level' => 1,
                'status' => 1,
                'admin_id' => 0,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            42 => 
            array (
                'id' => 3301,
                'pid' => 3300,
                'rid' => '3000|3300|3301',
                'title' => '添加银行卡',
                'route' => '',
                'api_path' => 'player/player-card-add',
                'sort' => 0,
                'css_class' => '',
                'type' => 1,
                'level' => 1,
                'status' => 1,
                'admin_id' => 0,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            43 => 
            array (
                'id' => 3302,
                'pid' => 3300,
                'rid' => '3000|3300|3302',
                'title' => '银行卡状态',
                'route' => '',
                'api_path' => 'player/player-card-status',
                'sort' => 0,
                'css_class' => '',
                'type' => 1,
                'level' => 1,
                'status' => 1,
                'admin_id' => 0,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            44 => 
            array (
                'id' => 3303,
                'pid' => 3300,
                'rid' => '3000|3300|3303',
                'title' => '删除银行卡',
                'route' => '',
                'api_path' => 'player/player-card-del',
                'sort' => 0,
                'css_class' => '',
                'type' => 1,
                'level' => 1,
                'status' => 1,
                'admin_id' => 0,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            45 => 
            array (
                'id' => 3400,
                'pid' => 3000,
                'rid' => '3000|3400',
                'title' => '工资契约',
                'route' => 'playerSalaryConfigList',
                'api_path' => 'player/salary-config-list',
                'sort' => 4,
                'css_class' => '',
                'type' => 0,
                'level' => 1,
                'status' => 1,
                'admin_id' => 0,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            46 => 
            array (
                'id' => 3401,
                'pid' => 3400,
                'rid' => '3000|3400|3401',
                'title' => '添加配置',
                'route' => 'playerSalaryConfigList',
                'api_path' => 'player/salary-config-add',
                'sort' => 0,
                'css_class' => '',
                'type' => 1,
                'level' => 1,
                'status' => 1,
                'admin_id' => 0,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            47 => 
            array (
                'id' => 3402,
                'pid' => 3400,
                'rid' => '3000|3400|3402',
                'title' => '配置状态修改',
                'route' => 'playerSalaryConfigStatus',
                'api_path' => 'player/salary-config-status',
                'sort' => 0,
                'css_class' => '',
                'type' => 1,
                'level' => 1,
                'status' => 1,
                'admin_id' => 0,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            48 => 
            array (
                'id' => 3403,
                'pid' => 3400,
                'rid' => '3000|3400|3403',
                'title' => '配置状态删除',
                'route' => 'playerSalaryConfigDel',
                'api_path' => 'player/salary-config-del',
                'sort' => 0,
                'css_class' => '',
                'type' => 1,
                'level' => 1,
                'status' => 1,
                'admin_id' => 0,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            49 => 
            array (
                'id' => 3500,
                'pid' => 3000,
                'rid' => '3000|3500',
                'title' => '分红契约',
                'route' => 'playerDividendConfigList',
                'api_path' => 'player/dividend-config-list',
                'sort' => 5,
                'css_class' => '',
                'type' => 0,
                'level' => 1,
                'status' => 1,
                'admin_id' => 0,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            50 => 
            array (
                'id' => 3501,
                'pid' => 3500,
                'rid' => '3000|3500|3501',
                'title' => '添加配置',
                'route' => 'playerDividendConfigAdd',
                'api_path' => 'player/dividend-config-add',
                'sort' => 0,
                'css_class' => '',
                'type' => 1,
                'level' => 1,
                'status' => 1,
                'admin_id' => 0,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            51 => 
            array (
                'id' => 3502,
                'pid' => 3500,
                'rid' => '3000|3500|3502',
                'title' => '配置状态修改',
                'route' => 'playerDividendConfigStatus',
                'api_path' => 'player/dividend-config-status',
                'sort' => 0,
                'css_class' => '',
                'type' => 1,
                'level' => 1,
                'status' => 1,
                'admin_id' => 0,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            52 => 
            array (
                'id' => 3503,
                'pid' => 3500,
                'rid' => '3000|3500|3503',
                'title' => '配置状态删除',
                'route' => 'playerDividendConfigDel',
                'api_path' => 'player/dividend-config-del',
                'sort' => 0,
                'css_class' => '',
                'type' => 1,
                'level' => 1,
                'status' => 1,
                'admin_id' => 0,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            53 => 
            array (
                'id' => 4000,
                'pid' => 0,
                'rid' => '',
                'title' => '账户管理',
                'route' => '',
                'api_path' => '',
                'sort' => 5,
                'css_class' => 'fa fa-lg fa-fw fa-cny',
                'type' => 0,
                'level' => 1,
                'status' => 1,
                'admin_id' => 0,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            54 => 
            array (
                'id' => 4100,
                'pid' => 4000,
                'rid' => '4000|4100',
                'title' => '帐变类型',
                'route' => 'accountChangeTypeList',
                'api_path' => 'account-change-type/list',
                'sort' => 1,
                'css_class' => '',
                'type' => 0,
                'level' => 1,
                'status' => 1,
                'admin_id' => 0,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            55 => 
            array (
                'id' => 4101,
                'pid' => 4100,
                'rid' => '4000|4100|4101',
                'title' => '添加类型',
                'route' => 'accountChangeTypeAdd',
                'api_path' => 'account-change-type/add',
                'sort' => 0,
                'css_class' => '',
                'type' => 1,
                'level' => 1,
                'status' => 1,
                'admin_id' => 0,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            56 => 
            array (
                'id' => 4102,
                'pid' => 4100,
                'rid' => '4000|4100|4102',
                'title' => '删除类型',
                'route' => 'accountChangeTypeDel',
                'api_path' => 'account-change-type/del',
                'sort' => 0,
                'css_class' => '',
                'type' => 1,
                'level' => 1,
                'status' => 1,
                'admin_id' => 0,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            57 => 
            array (
                'id' => 4103,
                'pid' => 4100,
                'rid' => '4000|4100|4103',
                'title' => '缓存类型',
                'route' => 'accountChangeTypeFlush',
                'api_path' => 'account-change-type/flush',
                'sort' => 0,
                'css_class' => '',
                'type' => 1,
                'level' => 1,
                'status' => 1,
                'admin_id' => 0,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            58 => 
            array (
                'id' => 4200,
                'pid' => 4000,
                'rid' => '4000|4200',
                'title' => '帐变列表',
                'route' => 'accountChangeReportList',
                'api_path' => 'account-change-report/list',
                'sort' => 2,
                'css_class' => '',
                'type' => 0,
                'level' => 1,
                'status' => 1,
                'admin_id' => 0,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            59 => 
            array (
                'id' => 4201,
                'pid' => 4200,
                'rid' => '4000|4200|4201',
                'title' => '帐变详情',
                'route' => 'accountChangeReportDetail',
                'api_path' => 'account-change-detail/list',
                'sort' => 0,
                'css_class' => '',
                'type' => 1,
                'level' => 1,
                'status' => 1,
                'admin_id' => 0,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            60 => 
            array (
                'id' => 4300,
                'pid' => 4000,
                'rid' => '4000|4300',
                'title' => '玩家账户',
                'route' => 'accountList',
                'api_path' => 'account/list',
                'sort' => 1,
                'css_class' => '',
                'type' => 0,
                'level' => 1,
                'status' => 1,
                'admin_id' => 0,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            61 => 
            array (
                'id' => 5000,
                'pid' => 0,
                'rid' => '',
                'title' => '报表管理',
                'route' => '',
                'api_path' => '',
                'sort' => 6,
                'css_class' => 'fa fa-lg fa-fw fa-bar-chart',
                'type' => 0,
                'level' => 1,
                'status' => 1,
                'admin_id' => 0,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            62 => 
            array (
                'id' => 5100,
                'pid' => 5000,
                'rid' => '5000|5100',
                'title' => '结算报表',
                'route' => 'userStatList',
                'api_path' => 'user-stat/list',
                'sort' => 0,
                'css_class' => '',
                'type' => 0,
                'level' => 1,
                'status' => 1,
                'admin_id' => 0,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            63 => 
            array (
                'id' => 5200,
                'pid' => 5000,
                'rid' => '5000|5200',
                'title' => '销量报表',
                'route' => 'userSaleList',
                'api_path' => 'user-sale/list',
                'sort' => 0,
                'css_class' => '',
                'type' => 0,
                'level' => 1,
                'status' => 1,
                'admin_id' => 0,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            64 => 
            array (
                'id' => 5300,
                'pid' => 5000,
                'rid' => '5000|5300',
                'title' => '工资记录',
                'route' => 'salaryList',
                'api_path' => 'salary/list',
                'sort' => 0,
                'css_class' => '',
                'type' => 0,
                'level' => 1,
                'status' => 1,
                'admin_id' => 0,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            65 => 
            array (
                'id' => 5400,
                'pid' => 5000,
                'rid' => '5000|5400',
                'title' => '分红记录',
                'route' => 'dividendList',
                'api_path' => 'dividend/list',
                'sort' => 0,
                'css_class' => '',
                'type' => 0,
                'level' => 1,
                'status' => 1,
                'admin_id' => 0,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            66 => 
            array (
                'id' => 6000,
                'pid' => 0,
                'rid' => '',
                'title' => '伙伴管理',
                'route' => '',
                'api_path' => '',
                'sort' => 2,
                'css_class' => 'fa fa-lg fa-fw fa-modx',
                'type' => 0,
                'level' => 1,
                'status' => 1,
                'admin_id' => 0,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            67 => 
            array (
                'id' => 6100,
                'pid' => 6000,
                'rid' => '6000|6100',
                'title' => '__管理员',
                'route' => 'partnerAdminUserList',
                'api_path' => 'partner/admin-user-list',
                'sort' => 2,
                'css_class' => '',
                'type' => 0,
                'level' => 1,
                'status' => 1,
                'admin_id' => 0,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            68 => 
            array (
                'id' => 6101,
                'pid' => 6100,
                'rid' => '6000|6100|6101',
                'title' => '添加管理员',
                'route' => 'partnerAdminUserAdd',
                'api_path' => 'partner/admin-user-add',
                'sort' => 0,
                'css_class' => '',
                'type' => 1,
                'level' => 1,
                'status' => 1,
                'admin_id' => 0,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            69 => 
            array (
                'id' => 6102,
                'pid' => 6100,
                'rid' => '6000|6100|6102',
                'title' => '管理员状态',
                'route' => 'partnerAdminUserStatus',
                'api_path' => 'partner/admin-user-status',
                'sort' => 0,
                'css_class' => '',
                'type' => 1,
                'level' => 1,
                'status' => 1,
                'admin_id' => 0,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            70 => 
            array (
                'id' => 6200,
                'pid' => 6000,
                'rid' => '6000|6200',
                'title' => '平台域名',
                'route' => 'partnerDomainList',
                'api_path' => 'partner/domain-list',
                'sort' => 1,
                'css_class' => '',
                'type' => 0,
                'level' => 1,
                'status' => 1,
                'admin_id' => 0,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            71 => 
            array (
                'id' => 6201,
                'pid' => 6200,
                'rid' => '6000|6200|6101',
                'title' => '添加域名',
                'route' => 'partnerDomainAdd',
                'api_path' => 'partner/domain-add',
                'sort' => 0,
                'css_class' => '',
                'type' => 1,
                'level' => 1,
                'status' => 1,
                'admin_id' => 0,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            72 => 
            array (
                'id' => 6202,
                'pid' => 6200,
                'rid' => '6000|6200|6102',
                'title' => '域名状态',
                'route' => 'partnerDomainStatus',
                'api_path' => 'partner/domain-status',
                'sort' => 0,
                'css_class' => '',
                'type' => 1,
                'level' => 1,
                'status' => 1,
                'admin_id' => 0,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            73 => 
            array (
                'id' => 6203,
                'pid' => 6200,
                'rid' => '6000|6200|6203',
                'title' => '删除域名',
                'route' => 'partnerDomainDel',
                'api_path' => 'partner/domain-del',
                'sort' => 0,
                'css_class' => '',
                'type' => 1,
                'level' => 1,
                'status' => 1,
                'admin_id' => 0,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            74 => 
            array (
                'id' => 6300,
                'pid' => 6000,
                'rid' => '6000|6300',
                'title' => '菜单管理',
                'route' => 'partnerAdminMenuList',
                'api_path' => 'partner/admin-menu-list',
                'sort' => 4,
                'css_class' => '',
                'type' => 0,
                'level' => 1,
                'status' => 1,
                'admin_id' => 0,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            75 => 
            array (
                'id' => 6301,
                'pid' => 6300,
                'rid' => '6000|6300|6301',
                'title' => '添加菜单',
                'route' => 'partnerAdminMenuAdd',
                'api_path' => 'partner/admin-menu-add',
                'sort' => 0,
                'css_class' => 'fa fa-lg fa-fw fa-plus',
                'type' => 1,
                'level' => 1,
                'status' => 1,
                'admin_id' => 0,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            76 => 
            array (
                'id' => 6302,
                'pid' => 6300,
                'rid' => '6000|6300|6302',
                'title' => '修改状态',
                'route' => 'partnerAdminMenuStatus',
                'api_path' => 'partner/admin-menu-status',
                'sort' => 0,
                'css_class' => '',
                'type' => 1,
                'level' => 1,
                'status' => 1,
                'admin_id' => 0,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            77 => 
            array (
                'id' => 6400,
                'pid' => 6000,
                'rid' => '6000|6400',
                'title' => '__管理组',
                'route' => 'partnerAdminGroupList',
                'api_path' => 'partner/admin-group-list',
                'sort' => 3,
                'css_class' => '',
                'type' => 0,
                'level' => 1,
                'status' => 1,
                'admin_id' => 0,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            78 => 
            array (
                'id' => 6401,
                'pid' => 6400,
                'rid' => '6000|6400|6401',
                'title' => '添加管理组',
                'route' => 'partnerAdminGroupAdd',
                'api_path' => 'partner/admin-group-add',
                'sort' => 1,
                'css_class' => '',
                'type' => 1,
                'level' => 1,
                'status' => 1,
                'admin_id' => 0,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            79 => 
            array (
                'id' => 6402,
                'pid' => 6400,
                'rid' => '6000|6400|6402',
                'title' => '管理组详情',
                'route' => 'partnerAdminGroupDetail',
                'api_path' => 'partner/admin-group-detail',
                'sort' => 1,
                'css_class' => '',
                'type' => 1,
                'level' => 1,
                'status' => 1,
                'admin_id' => 0,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            80 => 
            array (
                'id' => 6403,
                'pid' => 6400,
                'rid' => '6000|6400|6403',
                'title' => '删除管理组',
                'route' => 'partnerAdminGroupDel',
                'api_path' => 'partner/admin-group-del',
                'sort' => 1,
                'css_class' => '',
                'type' => 1,
                'level' => 1,
                'status' => 1,
                'admin_id' => 0,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            81 => 
            array (
                'id' => 6404,
                'pid' => 6400,
                'rid' => '6000|6400|6404',
                'title' => '管理组权限',
                'route' => 'partnerAdminGroupAclDetail',
                'api_path' => 'partner/admin-group-acl-detail',
                'sort' => 1,
                'css_class' => '',
                'type' => 1,
                'level' => 1,
                'status' => 1,
                'admin_id' => 0,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            82 => 
            array (
                'id' => 6405,
                'pid' => 6400,
                'rid' => '6000|6400|6405',
                'title' => '编辑管理组权限',
                'route' => 'partnerAdminGroupAclEdit',
                'api_path' => 'partner/admin-group-acl-edit',
                'sort' => 1,
                'css_class' => '',
                'type' => 1,
                'level' => 1,
                'status' => 1,
                'admin_id' => 0,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            83 => 
            array (
                'id' => 6406,
                'pid' => 6400,
                'rid' => '6000|6400|6406',
                'title' => '添加管理组',
                'route' => 'partnerAdminGroupAddChildGroup',
                'api_path' => 'partner/admin-group-add-child-group',
                'sort' => 1,
                'css_class' => '',
                'type' => 1,
                'level' => 1,
                'status' => 1,
                'admin_id' => 0,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            84 => 
            array (
                'id' => 6500,
                'pid' => 6000,
                'rid' => '6000|6500',
                'title' => '平台列表',
                'route' => 'partnerPlatformList',
                'api_path' => 'partner/platform-list',
                'sort' => 0,
                'css_class' => '',
                'type' => 0,
                'level' => 1,
                'status' => 1,
                'admin_id' => 0,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            85 => 
            array (
                'id' => 6501,
                'pid' => 6500,
                'rid' => '6000|6500|6501',
                'title' => '添加平台',
                'route' => 'partnerPlatformAdd',
                'api_path' => 'partner/platform-add',
                'sort' => 0,
                'css_class' => '',
                'type' => 1,
                'level' => 1,
                'status' => 1,
                'admin_id' => 0,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            86 => 
            array (
                'id' => 6502,
                'pid' => 6500,
                'rid' => '6000|6500|6501',
                'title' => '平台状态',
                'route' => 'partnerPlatformStatus',
                'api_path' => 'partner/platform-status',
                'sort' => 0,
                'css_class' => '',
                'type' => 1,
                'level' => 1,
                'status' => 1,
                'admin_id' => 0,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            87 => 
            array (
                'id' => 6503,
                'pid' => 6500,
                'rid' => '6000|6500|6503',
                'title' => '平台状态',
                'route' => 'partnerPlatformDel',
                'api_path' => 'partner/platform-del',
                'sort' => 0,
                'css_class' => '',
                'type' => 1,
                'level' => 1,
                'status' => 1,
                'admin_id' => 0,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            88 => 
            array (
                'id' => 6600,
                'pid' => 6000,
                'rid' => '6000|6600',
                'title' => '公告列表',
                'route' => 'noticeList',
                'api_path' => 'partner/notice-list',
                'sort' => 0,
                'css_class' => '',
                'type' => 0,
                'level' => 1,
                'status' => 1,
                'admin_id' => 0,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            89 => 
            array (
                'id' => 6601,
                'pid' => 6600,
                'rid' => '6000|6600|6601',
                'title' => '添加公告',
                'route' => 'noticeAdd',
                'api_path' => 'partner/notice-add',
                'sort' => 0,
                'css_class' => '',
                'type' => 1,
                'level' => 1,
                'status' => 1,
                'admin_id' => 0,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            90 => 
            array (
                'id' => 6602,
                'pid' => 6600,
                'rid' => '6000|6600|6602',
                'title' => '公告状态',
                'route' => 'noticeStatus',
                'api_path' => 'partner/notice-status',
                'sort' => 0,
                'css_class' => '',
                'type' => 1,
                'level' => 1,
                'status' => 1,
                'admin_id' => 0,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            91 => 
            array (
                'id' => 6603,
                'pid' => 6600,
                'rid' => '6000|6600|6603',
                'title' => '公告详情',
                'route' => 'noticeDetail',
                'api_path' => 'partner/notice-detail',
                'sort' => 0,
                'css_class' => '',
                'type' => 1,
                'level' => 1,
                'status' => 1,
                'admin_id' => 0,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            92 => 
            array (
                'id' => 7000,
                'pid' => 0,
                'rid' => '',
                'title' => '冲提管理',
                'route' => '',
                'api_path' => '',
                'sort' => 5,
                'css_class' => 'fa fa-lg fa-fw fa-cny',
                'type' => 0,
                'level' => 1,
                'status' => 1,
                'admin_id' => 0,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            93 => 
            array (
                'id' => 7100,
                'pid' => 7000,
                'rid' => '7000|7100',
                'title' => '充值列表',
                'route' => 'rechargeList',
                'api_path' => 'recharge/list',
                'sort' => 1,
                'css_class' => '',
                'type' => 0,
                'level' => 1,
                'status' => 1,
                'admin_id' => 0,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            94 => 
            array (
                'id' => 7101,
                'pid' => 7100,
                'rid' => '7000|7100|7101',
                'title' => '人工处理',
                'route' => 'rechargeHand',
                'api_path' => 'recharge/hand',
                'sort' => 0,
                'css_class' => '',
                'type' => 1,
                'level' => 1,
                'status' => 1,
                'admin_id' => 0,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            95 => 
            array (
                'id' => 7102,
                'pid' => 7100,
                'rid' => '7000|7100|7102',
                'title' => '日志详情',
                'route' => 'rechargeLogDetail',
                'api_path' => 'rechargel/log-detail',
                'sort' => 0,
                'css_class' => '',
                'type' => 1,
                'level' => 1,
                'status' => 1,
                'admin_id' => 0,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            96 => 
            array (
                'id' => 7200,
                'pid' => 7000,
                'rid' => '7000|7200',
                'title' => '提现列表',
                'route' => 'withdrawList',
                'api_path' => 'withdraw/list',
                'sort' => 2,
                'css_class' => '',
                'type' => 0,
                'level' => 1,
                'status' => 1,
                'admin_id' => 0,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            97 => 
            array (
                'id' => 7201,
                'pid' => 7200,
                'rid' => '7000|7200|7201',
                'title' => '人工处理',
                'route' => 'withdrawHand',
                'api_path' => 'withdraw/hand',
                'sort' => 0,
                'css_class' => '',
                'type' => 1,
                'level' => 1,
                'status' => 1,
                'admin_id' => 0,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            98 => 
            array (
                'id' => 7202,
                'pid' => 7200,
                'rid' => '7000|7200|7202',
                'title' => '日志详情',
                'route' => 'withdrawLogDetail',
                'api_path' => 'withdraw/log-detail',
                'sort' => 0,
                'css_class' => '',
                'type' => 1,
                'level' => 1,
                'status' => 1,
                'admin_id' => 0,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            99 => 
            array (
                'id' => 7300,
                'pid' => 7000,
                'rid' => '7000|7300',
                'title' => '审核列表',
                'route' => 'withdrawCheckList',
                'api_path' => 'withdraw-check/list',
                'sort' => 3,
                'css_class' => '',
                'type' => 0,
                'level' => 1,
                'status' => 1,
                'admin_id' => 0,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            100 => 
            array (
                'id' => 7301,
                'pid' => 7300,
                'rid' => '7000|7300|7301',
                'title' => '人工审核',
                'route' => 'withdrawCheckHand',
                'api_path' => 'withdraw-check/hand',
                'sort' => 0,
                'css_class' => '',
                'type' => 1,
                'level' => 1,
                'status' => 1,
                'admin_id' => 0,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            101 => 
            array (
                'id' => 7400,
                'pid' => 7000,
                'rid' => '7000|7400',
                'title' => '充值日志',
                'route' => 'rechargeLogList',
                'api_path' => 'recharge/log-list',
                'sort' => 4,
                'css_class' => '',
                'type' => 0,
                'level' => 1,
                'status' => 1,
                'admin_id' => 0,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            102 => 
            array (
                'id' => 7500,
                'pid' => 7000,
                'rid' => '7000|7500',
                'title' => '提现日志',
                'route' => 'withdrawLogList',
                'api_path' => 'withdraw/log-list',
                'sort' => 5,
                'css_class' => '',
                'type' => 0,
                'level' => 1,
                'status' => 1,
                'admin_id' => 0,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            103 => 
            array (
                'id' => 7600,
                'pid' => 7000,
                'rid' => '7000|7600',
                'title' => '审核日志',
                'route' => 'withdrawCheckLog',
                'api_path' => 'withdraw/list',
                'sort' => 6,
                'css_class' => '',
                'type' => 0,
                'level' => 1,
                'status' => 1,
                'admin_id' => 0,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            104 => 
            array (
                'id' => 8000,
                'pid' => 0,
                'rid' => '',
                'title' => '__管理员',
                'route' => '',
                'api_path' => '',
                'sort' => 1,
                'css_class' => 'fa fa-lg fa-fw fa-user',
                'type' => 0,
                'level' => 1,
                'status' => 1,
                'admin_id' => 0,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            105 => 
            array (
                'id' => 8100,
                'pid' => 8000,
                'rid' => '8000|8100',
                'title' => '__管理员',
                'route' => 'adminUserList',
                'api_path' => 'admin/admin-user-list',
                'sort' => 1,
                'css_class' => '',
                'type' => 0,
                'level' => 1,
                'status' => 1,
                'admin_id' => 0,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            106 => 
            array (
                'id' => 8101,
                'pid' => 8100,
                'rid' => '8000|8100|8101',
                'title' => '添加管理员',
                'route' => 'adminUserAdd',
                'api_path' => 'aadmin/dmin-user-add',
                'sort' => 1,
                'css_class' => '',
                'type' => 1,
                'level' => 1,
                'status' => 1,
                'admin_id' => 0,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            107 => 
            array (
                'id' => 8102,
                'pid' => 8100,
                'rid' => '8000|8100|8102',
                'title' => '管理员详情',
                'route' => 'adminUserDetail',
                'api_path' => 'admin/admin-user-detail',
                'sort' => 1,
                'css_class' => '',
                'type' => 1,
                'level' => 1,
                'status' => 1,
                'admin_id' => 0,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            108 => 
            array (
                'id' => 8103,
                'pid' => 8100,
                'rid' => '8000|8100|8103',
                'title' => '管理员状态',
                'route' => 'adminUserStatus',
                'api_path' => 'admin/admin-user-status',
                'sort' => 1,
                'css_class' => '',
                'type' => 1,
                'level' => 1,
                'status' => 1,
                'admin_id' => 0,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            109 => 
            array (
                'id' => 8104,
                'pid' => 8100,
                'rid' => '8000|8100|8104',
                'title' => '管理员密码',
                'route' => 'adminUserPassword',
                'api_path' => 'admin/admin-user-password',
                'sort' => 1,
                'css_class' => '',
                'type' => 1,
                'level' => 1,
                'status' => 1,
                'admin_id' => 0,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            110 => 
            array (
                'id' => 8200,
                'pid' => 8000,
                'rid' => '8000|8200',
                'title' => '__管理组',
                'route' => 'adminGroupList',
                'api_path' => 'admin/admin-group-list',
                'sort' => 2,
                'css_class' => '',
                'type' => 0,
                'level' => 1,
                'status' => 1,
                'admin_id' => 0,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            111 => 
            array (
                'id' => 8201,
                'pid' => 8200,
                'rid' => '8000|8200|8201',
                'title' => '添加管理组',
                'route' => 'adminGroupAdd',
                'api_path' => 'admin/admin-group-add',
                'sort' => 1,
                'css_class' => '',
                'type' => 1,
                'level' => 1,
                'status' => 1,
                'admin_id' => 0,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            112 => 
            array (
                'id' => 8202,
                'pid' => 8200,
                'rid' => '8000|8200|8202',
                'title' => '管理组详情',
                'route' => 'adminGroupDetail',
                'api_path' => 'admin/admin-group-detail',
                'sort' => 1,
                'css_class' => '',
                'type' => 1,
                'level' => 1,
                'status' => 1,
                'admin_id' => 0,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            113 => 
            array (
                'id' => 8203,
                'pid' => 8200,
                'rid' => '8000|8200|8203',
                'title' => '删除管理组',
                'route' => 'adminGroupDel',
                'api_path' => 'admin/admin-group-del',
                'sort' => 1,
                'css_class' => '',
                'type' => 1,
                'level' => 1,
                'status' => 1,
                'admin_id' => 0,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            114 => 
            array (
                'id' => 8204,
                'pid' => 8200,
                'rid' => '8000|8200|8204',
                'title' => '管理组权限',
                'route' => 'adminGroupAclDetail',
                'api_path' => 'admin/admin-group-acl-detail',
                'sort' => 1,
                'css_class' => '',
                'type' => 1,
                'level' => 1,
                'status' => 1,
                'admin_id' => 0,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            115 => 
            array (
                'id' => 8205,
                'pid' => 8200,
                'rid' => '8000|8200|8205',
                'title' => '编辑管理组权限',
                'route' => 'adminGroupAclEdit',
                'api_path' => 'admin/admin-group-acl-edit',
                'sort' => 1,
                'css_class' => '',
                'type' => 1,
                'level' => 1,
                'status' => 1,
                'admin_id' => 0,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            116 => 
            array (
                'id' => 8206,
                'pid' => 8200,
                'rid' => '8000|8200|8206',
                'title' => '添加管理组',
                'route' => 'adminGroupAddChildGroup',
                'api_path' => 'admin/admin-group-add-child',
                'sort' => 1,
                'css_class' => '',
                'type' => 1,
                'level' => 1,
                'status' => 1,
                'admin_id' => 0,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            117 => 
            array (
                'id' => 8300,
                'pid' => 8000,
                'rid' => '8000|8300',
                'title' => '菜单管理',
                'route' => 'menuList',
                'api_path' => 'admin/admin-menu-list',
                'sort' => 0,
                'css_class' => '',
                'type' => 0,
                'level' => 1,
                'status' => 1,
                'admin_id' => 0,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            118 => 
            array (
                'id' => 8301,
                'pid' => 8300,
                'rid' => '8000|8300|8301',
                'title' => '添加菜单',
                'route' => 'menuAdd',
                'api_path' => 'admin/admin-menu-add',
                'sort' => 0,
                'css_class' => 'fa fa-lg fa-fw fa-plus',
                'type' => 1,
                'level' => 1,
                'status' => 1,
                'admin_id' => 0,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            119 => 
            array (
                'id' => 8302,
                'pid' => 8300,
                'rid' => '8000|8300|8302',
                'title' => '修改状态',
                'route' => 'menuStatus',
                'api_path' => 'admin/admin-menu-status',
                'sort' => 0,
                'css_class' => '',
                'type' => 1,
                'level' => 1,
                'status' => 1,
                'admin_id' => 0,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
        ));
        
        
    }
}