<?php

use Illuminate\Database\Seeder;

class BackendAdminRechargehumanLogsTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('backend_admin_rechargehuman_logs')->delete();
        
        \DB::table('backend_admin_rechargehuman_logs')->insert(array (
            0 => 
            array (
                'id' => 13,
                'type' => 2,
                'in_out' => 0,
                'super_admin_id' => NULL,
                'super_admin_name' => NULL,
                'admin_id' => 13,
                'admin_name' => 'york1',
                'user_id' => 1,
                'user_name' => 'Dr. Taurean Nader1',
                'amount' => '300.00',
                'comment' => '[给用户人工充值]==>-300|[目前额度]==>1400',
                'audit_flow_id' => 265,
                'status' => 1,
                'updated_at' => NULL,
                'created_at' => NULL,
            ),
            1 => 
            array (
                'id' => 14,
                'type' => 1,
                'in_out' => 1,
                'super_admin_id' => 4,
                'super_admin_name' => 'york',
                'admin_id' => 13,
                'admin_name' => 'york1',
                'user_id' => NULL,
                'user_name' => NULL,
                'amount' => '99999999.99',
                'comment' => '[人工充值额度操作]==>+100000000|[目前额度]==>100000000',
                'audit_flow_id' => NULL,
                'status' => NULL,
                'updated_at' => '2019-05-09 11:16:43',
                'created_at' => '2019-05-09 11:16:43',
            ),
            2 => 
            array (
                'id' => 15,
                'type' => 1,
                'in_out' => 1,
                'super_admin_id' => 4,
                'super_admin_name' => 'york',
                'admin_id' => 13,
                'admin_name' => 'york1',
                'user_id' => NULL,
                'user_name' => NULL,
                'amount' => '1000.00',
                'comment' => '[人工充值额度操作]==>+1000|[目前额度]==>1000',
                'audit_flow_id' => NULL,
                'status' => NULL,
                'updated_at' => '2019-05-09 14:20:57',
                'created_at' => '2019-05-09 14:20:57',
            ),
            3 => 
            array (
                'id' => 16,
                'type' => 2,
                'in_out' => 0,
                'super_admin_id' => NULL,
                'super_admin_name' => NULL,
                'admin_id' => 13,
                'admin_name' => 'york1',
                'user_id' => 500,
                'user_name' => 'Miss Alison Pfannerstill499',
                'amount' => '11.00',
                'comment' => '[给用户人工充值]==>-11|[目前额度]==>989',
                'audit_flow_id' => 249,
                'status' => 1,
                'updated_at' => '2019-05-09 14:41:16',
                'created_at' => '2019-05-09 14:21:08',
            ),
            4 => 
            array (
                'id' => 17,
                'type' => 1,
                'in_out' => 1,
                'super_admin_id' => 4,
                'super_admin_name' => 'york',
                'admin_id' => 13,
                'admin_name' => 'york1',
                'user_id' => NULL,
                'user_name' => NULL,
                'amount' => '123.00',
                'comment' => '[人工充值额度操作]==>+123|[目前额度]==>1112',
                'audit_flow_id' => NULL,
                'status' => NULL,
                'updated_at' => '2019-05-09 14:29:28',
                'created_at' => '2019-05-09 14:29:28',
            ),
            5 => 
            array (
                'id' => 18,
                'type' => 0,
                'in_out' => 1,
                'super_admin_id' => NULL,
                'super_admin_name' => NULL,
                'admin_id' => 13,
                'admin_name' => 'york1',
                'user_id' => NULL,
                'user_name' => NULL,
                'amount' => NULL,
                'comment' => '[每日充值额度发放]=>>+3888|[目前额度]=>>5000',
                'audit_flow_id' => NULL,
                'status' => NULL,
                'updated_at' => '2019-05-10 00:00:12',
                'created_at' => '2019-05-10 00:00:12',
            ),
            6 => 
            array (
                'id' => 19,
                'type' => 0,
                'in_out' => 1,
                'super_admin_id' => NULL,
                'super_admin_name' => NULL,
                'admin_id' => 13,
                'admin_name' => 'york1',
                'user_id' => NULL,
                'user_name' => NULL,
                'amount' => NULL,
                'comment' => '[每日充值额度发放]=>>+3888|[目前额度]=>>5000',
                'audit_flow_id' => NULL,
                'status' => NULL,
                'updated_at' => '2019-05-10 00:00:12',
                'created_at' => '2019-05-10 00:00:12',
            ),
            7 => 
            array (
                'id' => 20,
                'type' => 0,
                'in_out' => 1,
                'super_admin_id' => NULL,
                'super_admin_name' => NULL,
                'admin_id' => 13,
                'admin_name' => 'york1',
                'user_id' => NULL,
                'user_name' => NULL,
                'amount' => NULL,
                'comment' => '[每日充值额度发放]=>>+3888|[目前额度]=>>5000',
                'audit_flow_id' => NULL,
                'status' => NULL,
                'updated_at' => '2019-05-10 00:00:12',
                'created_at' => '2019-05-10 00:00:12',
            ),
            8 => 
            array (
                'id' => 21,
                'type' => 0,
                'in_out' => 1,
                'super_admin_id' => NULL,
                'super_admin_name' => NULL,
                'admin_id' => 13,
                'admin_name' => 'york1',
                'user_id' => NULL,
                'user_name' => NULL,
                'amount' => NULL,
                'comment' => '[每日充值额度发放]=>>+3888|[目前额度]=>>5000',
                'audit_flow_id' => NULL,
                'status' => NULL,
                'updated_at' => '2019-05-10 00:00:12',
                'created_at' => '2019-05-10 00:00:12',
            ),
            9 => 
            array (
                'id' => 22,
                'type' => 0,
                'in_out' => 1,
                'super_admin_id' => NULL,
                'super_admin_name' => NULL,
                'admin_id' => 20,
                'admin_name' => 'name',
                'user_id' => NULL,
                'user_name' => NULL,
                'amount' => NULL,
                'comment' => '[每日充值额度发放]=>>+5000|[目前额度]=>>5000',
                'audit_flow_id' => NULL,
                'status' => NULL,
                'updated_at' => '2019-05-10 00:00:12',
                'created_at' => '2019-05-10 00:00:12',
            ),
            10 => 
            array (
                'id' => 23,
                'type' => 0,
                'in_out' => 1,
                'super_admin_id' => NULL,
                'super_admin_name' => NULL,
                'admin_id' => 20,
                'admin_name' => 'name',
                'user_id' => NULL,
                'user_name' => NULL,
                'amount' => NULL,
                'comment' => '[每日充值额度发放]=>>+5000|[目前额度]=>>5000',
                'audit_flow_id' => NULL,
                'status' => NULL,
                'updated_at' => '2019-05-10 00:00:12',
                'created_at' => '2019-05-10 00:00:12',
            ),
            11 => 
            array (
                'id' => 24,
                'type' => 0,
                'in_out' => 1,
                'super_admin_id' => NULL,
                'super_admin_name' => NULL,
                'admin_id' => 20,
                'admin_name' => 'name',
                'user_id' => NULL,
                'user_name' => NULL,
                'amount' => NULL,
                'comment' => '[每日充值额度发放]=>>+5000|[目前额度]=>>5000',
                'audit_flow_id' => NULL,
                'status' => NULL,
                'updated_at' => '2019-05-10 00:00:12',
                'created_at' => '2019-05-10 00:00:12',
            ),
            12 => 
            array (
                'id' => 25,
                'type' => 0,
                'in_out' => 1,
                'super_admin_id' => NULL,
                'super_admin_name' => NULL,
                'admin_id' => 20,
                'admin_name' => 'name',
                'user_id' => NULL,
                'user_name' => NULL,
                'amount' => NULL,
                'comment' => '[每日充值额度发放]=>>+5000|[目前额度]=>>5000',
                'audit_flow_id' => NULL,
                'status' => NULL,
                'updated_at' => '2019-05-10 00:00:12',
                'created_at' => '2019-05-10 00:00:12',
            ),
            13 => 
            array (
                'id' => 26,
                'type' => 1,
                'in_out' => 1,
                'super_admin_id' => 1,
                'super_admin_name' => 'Harris',
                'admin_id' => 13,
                'admin_name' => 'york1',
                'user_id' => NULL,
                'user_name' => NULL,
                'amount' => '7.00',
                'comment' => '[人工充值额度操作]==>+7|[目前额度]==>5007',
                'audit_flow_id' => NULL,
                'status' => NULL,
                'updated_at' => '2019-05-10 15:42:05',
                'created_at' => '2019-05-10 15:42:05',
            ),
            14 => 
            array (
                'id' => 27,
                'type' => 1,
                'in_out' => 1,
                'super_admin_id' => 23,
                'super_admin_name' => 'Diana',
                'admin_id' => 25,
                'admin_name' => '122324354654',
                'user_id' => NULL,
                'user_name' => NULL,
                'amount' => '99999999.99',
                'comment' => '[人工充值额度操作]==>+1.0E+43|[目前额度]==>1.0E+43',
                'audit_flow_id' => NULL,
                'status' => NULL,
                'updated_at' => '2019-05-11 16:16:56',
                'created_at' => '2019-05-11 16:16:56',
            ),
            15 => 
            array (
                'id' => 28,
                'type' => 0,
                'in_out' => 1,
                'super_admin_id' => NULL,
                'super_admin_name' => NULL,
                'admin_id' => 20,
                'admin_name' => 'name',
                'user_id' => NULL,
                'user_name' => NULL,
                'amount' => NULL,
                'comment' => '[每日充值额度发放]=>>+10000|[目前额度]=>>10000',
                'audit_flow_id' => NULL,
                'status' => NULL,
                'updated_at' => '2019-05-12 00:00:15',
                'created_at' => '2019-05-12 00:00:15',
            ),
            16 => 
            array (
                'id' => 29,
                'type' => 0,
                'in_out' => 1,
                'super_admin_id' => NULL,
                'super_admin_name' => NULL,
                'admin_id' => 20,
                'admin_name' => 'name',
                'user_id' => NULL,
                'user_name' => NULL,
                'amount' => NULL,
                'comment' => '[每日充值额度发放]=>>+10000|[目前额度]=>>10000',
                'audit_flow_id' => NULL,
                'status' => NULL,
                'updated_at' => '2019-05-12 00:00:15',
                'created_at' => '2019-05-12 00:00:15',
            ),
            17 => 
            array (
                'id' => 30,
                'type' => 0,
                'in_out' => 1,
                'super_admin_id' => NULL,
                'super_admin_name' => NULL,
                'admin_id' => 20,
                'admin_name' => 'name',
                'user_id' => NULL,
                'user_name' => NULL,
                'amount' => NULL,
                'comment' => '[每日充值额度发放]=>>+10000|[目前额度]=>>10000',
                'audit_flow_id' => NULL,
                'status' => NULL,
                'updated_at' => '2019-05-12 00:00:15',
                'created_at' => '2019-05-12 00:00:15',
            ),
            18 => 
            array (
                'id' => 31,
                'type' => 1,
                'in_out' => 1,
                'super_admin_id' => 4,
                'super_admin_name' => 'york',
                'admin_id' => 25,
                'admin_name' => 'york222',
                'user_id' => NULL,
                'user_name' => NULL,
                'amount' => '100.00',
                'comment' => '[人工充值额度操作]==>+100|[目前额度]==>100',
                'audit_flow_id' => NULL,
                'status' => NULL,
                'updated_at' => '2019-05-23 17:34:29',
                'created_at' => '2019-05-23 17:34:29',
            ),
            19 => 
            array (
                'id' => 32,
                'type' => 2,
                'in_out' => 0,
                'super_admin_id' => NULL,
                'super_admin_name' => NULL,
                'admin_id' => 20,
                'admin_name' => 'york888',
                'user_id' => 1,
                'user_name' => 'harriszhongdai',
                'amount' => '10.00',
                'comment' => '[给用户人工充值]==>-10|[目前额度]==>9990',
                'audit_flow_id' => 257,
                'status' => 2,
                'updated_at' => '2019-05-23 17:45:10',
                'created_at' => '2019-05-23 17:42:21',
            ),
            20 => 
            array (
                'id' => 33,
                'type' => 0,
                'in_out' => 1,
                'super_admin_id' => NULL,
                'super_admin_name' => NULL,
                'admin_id' => 20,
                'admin_name' => 'york888',
                'user_id' => NULL,
                'user_name' => NULL,
                'amount' => '10.00',
                'comment' => '[充值审核失败额度返还]==>+10.00|[目前额度]==>10000',
                'audit_flow_id' => NULL,
                'status' => NULL,
                'updated_at' => '2019-05-23 17:45:10',
                'created_at' => '2019-05-23 17:45:10',
            ),
            21 => 
            array (
                'id' => 34,
                'type' => 0,
                'in_out' => 1,
                'super_admin_id' => NULL,
                'super_admin_name' => NULL,
                'admin_id' => 25,
                'admin_name' => 'york222',
                'user_id' => NULL,
                'user_name' => NULL,
                'amount' => NULL,
                'comment' => '[每日充值额度发放]=>>+9900|[目前额度]=>>10000',
                'audit_flow_id' => NULL,
                'status' => NULL,
                'updated_at' => '2019-05-24 00:00:12',
                'created_at' => '2019-05-24 00:00:12',
            ),
            22 => 
            array (
                'id' => 35,
                'type' => 0,
                'in_out' => 1,
                'super_admin_id' => NULL,
                'super_admin_name' => NULL,
                'admin_id' => 25,
                'admin_name' => 'york222',
                'user_id' => NULL,
                'user_name' => NULL,
                'amount' => NULL,
                'comment' => '[每日充值额度发放]=>>+9900|[目前额度]=>>10000',
                'audit_flow_id' => NULL,
                'status' => NULL,
                'updated_at' => '2019-05-24 00:00:12',
                'created_at' => '2019-05-24 00:00:12',
            ),
            23 => 
            array (
                'id' => 36,
                'type' => 0,
                'in_out' => 1,
                'super_admin_id' => NULL,
                'super_admin_name' => NULL,
                'admin_id' => 25,
                'admin_name' => 'york222',
                'user_id' => NULL,
                'user_name' => NULL,
                'amount' => NULL,
                'comment' => '[每日充值额度发放]=>>+9900|[目前额度]=>>10000',
                'audit_flow_id' => NULL,
                'status' => NULL,
                'updated_at' => '2019-05-24 00:00:12',
                'created_at' => '2019-05-24 00:00:12',
            ),
            24 => 
            array (
                'id' => 37,
                'type' => 0,
                'in_out' => 1,
                'super_admin_id' => NULL,
                'super_admin_name' => NULL,
                'admin_id' => 26,
                'admin_name' => 'york888',
                'user_id' => NULL,
                'user_name' => NULL,
                'amount' => NULL,
                'comment' => '[每日充值额度发放]=>>+10000|[目前额度]=>>10000',
                'audit_flow_id' => NULL,
                'status' => NULL,
                'updated_at' => '2019-05-24 00:00:12',
                'created_at' => '2019-05-24 00:00:12',
            ),
            25 => 
            array (
                'id' => 38,
                'type' => 0,
                'in_out' => 1,
                'super_admin_id' => NULL,
                'super_admin_name' => NULL,
                'admin_id' => 26,
                'admin_name' => 'york888',
                'user_id' => NULL,
                'user_name' => NULL,
                'amount' => NULL,
                'comment' => '[每日充值额度发放]=>>+10000|[目前额度]=>>10000',
                'audit_flow_id' => NULL,
                'status' => NULL,
                'updated_at' => '2019-05-24 00:00:12',
                'created_at' => '2019-05-24 00:00:12',
            ),
            26 => 
            array (
                'id' => 39,
                'type' => 0,
                'in_out' => 1,
                'super_admin_id' => NULL,
                'super_admin_name' => NULL,
                'admin_id' => 26,
                'admin_name' => 'york888',
                'user_id' => NULL,
                'user_name' => NULL,
                'amount' => NULL,
                'comment' => '[每日充值额度发放]=>>+10000|[目前额度]=>>10000',
                'audit_flow_id' => NULL,
                'status' => NULL,
                'updated_at' => '2019-05-24 00:00:12',
                'created_at' => '2019-05-24 00:00:12',
            ),
            27 => 
            array (
                'id' => 40,
                'type' => 1,
                'in_out' => 1,
                'super_admin_id' => 4,
                'super_admin_name' => 'york',
                'admin_id' => 25,
                'admin_name' => 'york222',
                'user_id' => NULL,
                'user_name' => NULL,
                'amount' => '199.00',
                'comment' => '[人工充值额度操作]==>+199|[目前额度]==>10199',
                'audit_flow_id' => NULL,
                'status' => NULL,
                'updated_at' => '2019-05-24 11:48:38',
                'created_at' => '2019-05-24 11:48:38',
            ),
            28 => 
            array (
                'id' => 41,
                'type' => 0,
                'in_out' => 1,
                'super_admin_id' => NULL,
                'super_admin_name' => NULL,
                'admin_id' => 25,
                'admin_name' => 'york222',
                'user_id' => NULL,
                'user_name' => NULL,
                'amount' => NULL,
                'comment' => '[每日充值额度发放]=>>+69801|[目前额度]=>>80000',
                'audit_flow_id' => NULL,
                'status' => NULL,
                'updated_at' => '2019-05-25 00:00:15',
                'created_at' => '2019-05-25 00:00:15',
            ),
            29 => 
            array (
                'id' => 42,
                'type' => 0,
                'in_out' => 1,
                'super_admin_id' => NULL,
                'super_admin_name' => NULL,
                'admin_id' => 25,
                'admin_name' => 'york222',
                'user_id' => NULL,
                'user_name' => NULL,
                'amount' => NULL,
                'comment' => '[每日充值额度发放]=>>+69801|[目前额度]=>>80000',
                'audit_flow_id' => NULL,
                'status' => NULL,
                'updated_at' => '2019-05-25 00:00:15',
                'created_at' => '2019-05-25 00:00:15',
            ),
            30 => 
            array (
                'id' => 43,
                'type' => 0,
                'in_out' => 1,
                'super_admin_id' => NULL,
                'super_admin_name' => NULL,
                'admin_id' => 25,
                'admin_name' => 'york222',
                'user_id' => NULL,
                'user_name' => NULL,
                'amount' => NULL,
                'comment' => '[每日充值额度发放]=>>+69801|[目前额度]=>>80000',
                'audit_flow_id' => NULL,
                'status' => NULL,
                'updated_at' => '2019-05-25 00:00:15',
                'created_at' => '2019-05-25 00:00:15',
            ),
            31 => 
            array (
                'id' => 44,
                'type' => 0,
                'in_out' => 1,
                'super_admin_id' => NULL,
                'super_admin_name' => NULL,
                'admin_id' => 26,
                'admin_name' => 'york888',
                'user_id' => NULL,
                'user_name' => NULL,
                'amount' => NULL,
                'comment' => '[每日充值额度发放]=>>+70000|[目前额度]=>>80000',
                'audit_flow_id' => NULL,
                'status' => NULL,
                'updated_at' => '2019-05-25 00:00:15',
                'created_at' => '2019-05-25 00:00:15',
            ),
            32 => 
            array (
                'id' => 45,
                'type' => 0,
                'in_out' => 1,
                'super_admin_id' => NULL,
                'super_admin_name' => NULL,
                'admin_id' => 26,
                'admin_name' => 'york888',
                'user_id' => NULL,
                'user_name' => NULL,
                'amount' => NULL,
                'comment' => '[每日充值额度发放]=>>+70000|[目前额度]=>>80000',
                'audit_flow_id' => NULL,
                'status' => NULL,
                'updated_at' => '2019-05-25 00:00:15',
                'created_at' => '2019-05-25 00:00:15',
            ),
            33 => 
            array (
                'id' => 46,
                'type' => 0,
                'in_out' => 1,
                'super_admin_id' => NULL,
                'super_admin_name' => NULL,
                'admin_id' => 26,
                'admin_name' => 'york888',
                'user_id' => NULL,
                'user_name' => NULL,
                'amount' => NULL,
                'comment' => '[每日充值额度发放]=>>+70000|[目前额度]=>>80000',
                'audit_flow_id' => NULL,
                'status' => NULL,
                'updated_at' => '2019-05-25 00:00:15',
                'created_at' => '2019-05-25 00:00:15',
            ),
            34 => 
            array (
                'id' => 47,
                'type' => 2,
                'in_out' => 0,
                'super_admin_id' => NULL,
                'super_admin_name' => NULL,
                'admin_id' => 25,
                'admin_name' => 'york222',
                'user_id' => 1,
                'user_name' => 'harriszhongdai',
                'amount' => '10.00',
                'comment' => '[给用户人工充值]==>-10|[目前额度]==>79990',
                'audit_flow_id' => 258,
                'status' => 1,
                'updated_at' => '2019-05-25 15:28:44',
                'created_at' => '2019-05-25 15:28:04',
            ),
            35 => 
            array (
                'id' => 48,
                'type' => 0,
                'in_out' => 1,
                'super_admin_id' => NULL,
                'super_admin_name' => NULL,
                'admin_id' => 25,
                'admin_name' => 'york222',
                'user_id' => NULL,
                'user_name' => NULL,
                'amount' => NULL,
                'comment' => '[每日充值额度发放]=>>+10|[目前额度]=>>80000',
                'audit_flow_id' => NULL,
                'status' => NULL,
                'updated_at' => '2019-05-28 00:00:11',
                'created_at' => '2019-05-28 00:00:11',
            ),
            36 => 
            array (
                'id' => 49,
                'type' => 0,
                'in_out' => 1,
                'super_admin_id' => NULL,
                'super_admin_name' => NULL,
                'admin_id' => 25,
                'admin_name' => 'york222',
                'user_id' => NULL,
                'user_name' => NULL,
                'amount' => NULL,
                'comment' => '[每日充值额度发放]=>>+10|[目前额度]=>>80000',
                'audit_flow_id' => NULL,
                'status' => NULL,
                'updated_at' => '2019-05-28 00:00:11',
                'created_at' => '2019-05-28 00:00:11',
            ),
            37 => 
            array (
                'id' => 50,
                'type' => 0,
                'in_out' => 1,
                'super_admin_id' => NULL,
                'super_admin_name' => NULL,
                'admin_id' => 25,
                'admin_name' => 'york222',
                'user_id' => NULL,
                'user_name' => NULL,
                'amount' => NULL,
                'comment' => '[每日充值额度发放]=>>+10|[目前额度]=>>80000',
                'audit_flow_id' => NULL,
                'status' => NULL,
                'updated_at' => '2019-05-28 00:00:11',
                'created_at' => '2019-05-28 00:00:11',
            ),
            38 => 
            array (
                'id' => 51,
                'type' => 3,
                'in_out' => 0,
                'super_admin_id' => 4,
                'super_admin_name' => 'york',
                'admin_id' => NULL,
                'admin_name' => NULL,
                'user_id' => 1,
                'user_name' => 'harriszhongdai',
                'amount' => '1.00',
                'comment' => '[给用户人工充值]==>-1|[目前额度]==>',
                'audit_flow_id' => NULL,
                'status' => 1,
                'updated_at' => '2019-06-06 17:46:51',
                'created_at' => '2019-06-06 17:46:51',
            ),
        ));
        
        
    }
}