<?php

use Illuminate\Database\Seeder;

class BackendAdminRoutesTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('backend_admin_routes')->delete();
        
        \DB::table('backend_admin_routes')->insert(array (
            0 => 
            array (
                'id' => 3,
                'route_name' => 'backend-api.logout',
                'controller' => NULL,
                'method' => NULL,
                'menu_group_id' => NULL,
                'title' => '登出',
                'description' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            1 => 
            array (
                'id' => 4,
                'route_name' => 'backend-api.menu.allPartnerMenu',
                'controller' => 'App\\Http\\Controllers\\BackendApi\\DeveloperUsage\\Backend\\Menu\\Menu',
                'method' => 'getAllMenu',
                'menu_group_id' => 1,
                'title' => '获取所有菜单',
                'description' => NULL,
                'created_at' => NULL,
                'updated_at' => '2019-06-04 15:14:34',
            ),
            2 => 
            array (
                'id' => 5,
                'route_name' => 'backend-api.partnerAdminGroup.detail',
                'controller' => 'App\\Http\\Controllers\\BackendApi\\Admin\\PartnerAdminGroupControlle',
                'method' => 'index',
                'menu_group_id' => 11,
                'title' => '获取管理员角色接口',
                'description' => NULL,
                'created_at' => NULL,
                'updated_at' => '2019-06-04 15:29:18',
            ),
            3 => 
            array (
                'id' => 6,
                'route_name' => 'backend-api.partnerAdminGroup.edit',
                'controller' => 'App\\Http\\Controllers\\BackendApi\\Admin\\PartnerAdminGroupControlle',
                'method' => 'edit',
                'menu_group_id' => 11,
                'title' => '编辑管理员角色接口',
                'description' => NULL,
                'created_at' => NULL,
                'updated_at' => '2019-06-04 15:29:34',
            ),
            4 => 
            array (
                'id' => 7,
                'route_name' => 'backend-api.partnerAdmin.get-all-users',
                'controller' => 'App\\Http\\Controllers\\BackendApi\\BackendAuthController',
                'method' => 'allUser',
                'menu_group_id' => 11,
                'title' => '获取所有管理员接口',
                'description' => NULL,
                'created_at' => NULL,
                'updated_at' => '2019-06-04 15:29:48',
            ),
            5 => 
            array (
                'id' => 8,
                'route_name' => 'backend-api.partnerAdmin.update-user-group',
                'controller' => 'App\\Http\\Controllers\\BackendApi\\BackendAuthController',
                'method' => 'updateUserGroup',
                'menu_group_id' => 11,
                'title' => '更改目前用户到另外的组',
                'description' => NULL,
                'created_at' => NULL,
                'updated_at' => '2019-06-04 15:30:04',
            ),
            6 => 
            array (
                'id' => 9,
                'route_name' => 'backend-api.partnerAdmin.register',
                'controller' => 'App\\Http\\Controllers\\BackendApi\\BackendAuthController',
                'method' => 'register',
                'menu_group_id' => 11,
                'title' => '创建商户用户',
                'description' => NULL,
                'created_at' => NULL,
                'updated_at' => '2019-06-04 15:30:20',
            ),
            7 => 
            array (
                'id' => 10,
                'route_name' => 'backend-api.partnerAdmin.delete-user',
                'controller' => 'App\\Http\\Controllers\\BackendApi\\BackendAuthController',
                'method' => 'deletePartnerAdmin',
                'menu_group_id' => 11,
                'title' => '删除管理员账号',
                'description' => NULL,
                'created_at' => NULL,
                'updated_at' => '2019-06-04 15:30:36',
            ),
            8 => 
            array (
                'id' => 11,
                'route_name' => 'backend-api.partnerAdminGroup.delete-access-group',
                'controller' => 'App\\Http\\Controllers\\BackendApi\\Admin\\PartnerAdminGroupControlle',
                'method' => 'destroy',
                'menu_group_id' => 11,
                'title' => '删除管理员组',
                'description' => NULL,
                'created_at' => NULL,
                'updated_at' => '2019-06-04 15:30:44',
            ),
            9 => 
            array (
                'id' => 12,
                'route_name' => 'backend-api.partnerAdmin.self-reset-password',
                'controller' => 'App\\Http\\Controllers\\BackendApi\\BackendAuthController',
                'method' => 'selfResetPassword',
                'menu_group_id' => 11,
                'title' => '更换密码管理员亲自',
                'description' => NULL,
                'created_at' => NULL,
                'updated_at' => '2019-06-04 15:30:52',
            ),
            10 => 
            array (
                'id' => 13,
                'route_name' => 'backend-api.partnerAdminGroup.specific-group-users',
                'controller' => 'App\\Http\\Controllers\\BackendApi\\Admin\\PartnerAdminGroupControlle',
                'method' => 'specificGroupUsers',
                'menu_group_id' => 11,
                'title' => '获取某组的管理员信息',
                'description' => NULL,
                'created_at' => NULL,
                'updated_at' => '2019-06-04 15:30:59',
            ),
            11 => 
            array (
                'id' => 14,
                'route_name' => 'backend-api.userhandle.create-user',
                'controller' => 'App\\Http\\Controllers\\BackendApi\\Users\\UserHandleController',
                'method' => 'createUser',
                'menu_group_id' => 25,
                'title' => '创建总代接口',
                'description' => NULL,
                'created_at' => NULL,
                'updated_at' => '2019-06-04 17:33:24',
            ),
            12 => 
            array (
                'id' => 15,
                'route_name' => 'backend-api.userhandle.prizegroup',
                'controller' => 'App\\Http\\Controllers\\BackendApi\\Users\\UserHandleController',
                'method' => 'getUserPrizeGroup',
                'menu_group_id' => 25,
                'title' => '创建总代时获取平台的最低与最高的奖金组',
                'description' => NULL,
                'created_at' => NULL,
                'updated_at' => '2019-06-04 17:33:35',
            ),
            13 => 
            array (
                'id' => 16,
                'route_name' => 'backend-api.userhandle.users-info',
                'controller' => 'App\\Http\\Controllers\\BackendApi\\Users\\UserHandleController',
                'method' => 'usersInfo',
                'menu_group_id' => 25,
                'title' => '用户信息表',
                'description' => NULL,
                'created_at' => NULL,
                'updated_at' => '2019-06-04 17:33:51',
            ),
            14 => 
            array (
                'id' => 17,
                'route_name' => 'backend-api.userhandle.reset-password',
                'controller' => 'App\\Http\\Controllers\\BackendApi\\Users\\UserHandleController',
                'method' => 'applyResetUserPassword',
                'menu_group_id' => 25,
                'title' => '申请用户密码功能',
                'description' => NULL,
                'created_at' => NULL,
                'updated_at' => '2019-06-04 17:35:17',
            ),
            15 => 
            array (
                'id' => 18,
                'route_name' => 'backend-api.userhandle.reset-password-list',
                'controller' => 'App\\Http\\Controllers\\BackendApi\\Users\\UserHandleController',
                'method' => 'appliedResetUserPasswordLists',
                'menu_group_id' => 25,
                'title' => '用户密码已申请列表',
                'description' => NULL,
                'created_at' => NULL,
                'updated_at' => '2019-06-04 17:35:39',
            ),
            16 => 
            array (
                'id' => 19,
                'route_name' => 'backend-api.userhandle.reset-fund-password',
                'controller' => 'App\\Http\\Controllers\\BackendApi\\Users\\UserHandleController',
                'method' => 'applyResetUserFundPassword',
                'menu_group_id' => 25,
                'title' => '申请用户资金密码功能',
                'description' => NULL,
                'created_at' => NULL,
                'updated_at' => '2019-06-04 17:36:14',
            ),
            17 => 
            array (
                'id' => 20,
                'route_name' => 'backend-api.userhandle.reset-fund-password-list',
                'controller' => 'App\\Http\\Controllers\\BackendApi\\Users\\UserHandleController',
                'method' => 'appliedResetUserFundPasswordLists',
                'menu_group_id' => 25,
                'title' => '用户资金密码已申请列表',
                'description' => NULL,
                'created_at' => NULL,
                'updated_at' => '2019-06-04 17:36:35',
            ),
            18 => 
            array (
                'id' => 21,
                'route_name' => 'backend-api.userhandle.audit-applied-password',
                'controller' => 'App\\Http\\Controllers\\BackendApi\\Users\\UserHandleController',
                'method' => 'auditApplyUserPassword',
                'menu_group_id' => 25,
                'title' => '给用户审核密码',
                'description' => NULL,
                'created_at' => NULL,
                'updated_at' => '2019-06-04 17:36:57',
            ),
            19 => 
            array (
                'id' => 22,
                'route_name' => 'backend-api.userhandle.audit-applied-fund-password',
                'controller' => 'App\\Http\\Controllers\\BackendApi\\Users\\UserHandleController',
                'method' => 'auditApplyUserFundPassword',
                'menu_group_id' => 25,
                'title' => '给用户审核资金密码',
                'description' => NULL,
                'created_at' => NULL,
                'updated_at' => '2019-06-04 17:37:06',
            ),
            20 => 
            array (
                'id' => 23,
                'route_name' => 'backend-api.loghandle.list',
                'controller' => 'App\\Http\\Controllers\\BackendApi\\Admin\\Log\\HandleLogController',
                'method' => 'details',
                'menu_group_id' => 59,
                'title' => '管理员操作日志列表',
                'description' => NULL,
                'created_at' => NULL,
                'updated_at' => '2019-06-04 15:42:52',
            ),
            21 => 
            array (
                'id' => 24,
                'route_name' => 'backend-api.userhandle.deactivate',
                'controller' => 'App\\Http\\Controllers\\BackendApi\\Users\\UserHandleController',
                'method' => 'deactivate',
                'menu_group_id' => 25,
                'title' => '玩家冻结操作',
                'description' => NULL,
                'created_at' => NULL,
                'updated_at' => '2019-06-04 17:38:08',
            ),
            22 => 
            array (
                'id' => 25,
                'route_name' => 'backend-api.userhandle.deactivated-detail',
                'controller' => 'App\\Http\\Controllers\\BackendApi\\Users\\UserHandleController',
                'method' => 'deactivateDetail',
                'menu_group_id' => 25,
                'title' => '玩家被冻结操作历史',
                'description' => NULL,
                'created_at' => NULL,
                'updated_at' => '2019-06-04 17:42:48',
            ),
            23 => 
            array (
                'id' => 26,
                'route_name' => 'backend-api.menu.current-admin-menu',
                'controller' => 'App\\Http\\Controllers\\BackendApi\\DeveloperUsage\\Backend\\Menu\\Menu',
                'method' => 'currentPartnerMenu',
                'menu_group_id' => 1,
                'title' => '获取当前商户用户的菜单',
                'description' => NULL,
                'created_at' => NULL,
                'updated_at' => '2019-06-04 15:20:53',
            ),
            24 => 
            array (
                'id' => 27,
                'route_name' => 'backend-api.configures.detail',
                'controller' => 'App\\Http\\Controllers\\BackendApi\\Admin\\ConfiguresController',
                'method' => 'getConfiguresList',
                'menu_group_id' => 3,
                'title' => '获取系统配置',
                'description' => NULL,
                'created_at' => NULL,
                'updated_at' => '2019-06-04 15:21:08',
            ),
            25 => 
            array (
                'id' => 28,
                'route_name' => 'backend-api.configures.add',
                'controller' => 'App\\Http\\Controllers\\BackendApi\\Admin\\ConfiguresController',
                'method' => 'add',
                'menu_group_id' => 3,
                'title' => '添加系统配置',
                'description' => NULL,
                'created_at' => NULL,
                'updated_at' => '2019-06-04 15:21:22',
            ),
            26 => 
            array (
                'id' => 29,
                'route_name' => 'backend-api.lotteries.series-lists',
                'controller' => 'App\\Http\\Controllers\\BackendApi\\Game\\Lottery\\LotteriesController',
                'method' => 'seriesLists',
                'menu_group_id' => 12,
                'title' => '游戏series获取接口',
                'description' => NULL,
                'created_at' => NULL,
                'updated_at' => '2019-06-04 17:25:26',
            ),
            27 => 
            array (
                'id' => 30,
                'route_name' => 'backend-api.lotteries.lotteries-lists',
                'controller' => 'App\\Http\\Controllers\\BackendApi\\Game\\Lottery\\LotteriesController',
                'method' => 'lotteriesLists',
                'menu_group_id' => 12,
                'title' => '彩种列表获取接口',
                'description' => NULL,
                'created_at' => NULL,
                'updated_at' => '2019-06-04 17:30:10',
            ),
            28 => 
            array (
                'id' => 31,
                'route_name' => 'backend-api.configures.edit',
                'controller' => 'App\\Http\\Controllers\\BackendApi\\Admin\\ConfiguresController',
                'method' => 'edit',
                'menu_group_id' => 3,
                'title' => '修改系统配置',
                'description' => NULL,
                'created_at' => NULL,
                'updated_at' => '2019-06-04 15:21:36',
            ),
            29 => 
            array (
                'id' => 32,
                'route_name' => 'backend-api.configures.delete',
                'controller' => 'App\\Http\\Controllers\\BackendApi\\Admin\\ConfiguresController',
                'method' => 'delete',
                'menu_group_id' => 3,
                'title' => '删除系统配置',
                'description' => NULL,
                'created_at' => NULL,
                'updated_at' => '2019-06-04 15:21:49',
            ),
            30 => 
            array (
                'id' => 33,
                'route_name' => 'backend-api.configures.switch',
                'controller' => 'App\\Http\\Controllers\\BackendApi\\Admin\\ConfiguresController',
                'method' => 'configSwitch',
                'menu_group_id' => 3,
                'title' => '系统配置开关',
                'description' => NULL,
                'created_at' => NULL,
                'updated_at' => '2019-06-04 15:22:05',
            ),
            31 => 
            array (
                'id' => 34,
                'route_name' => 'backend-api.lotteries.lotteries-method-lists',
                'controller' => 'App\\Http\\Controllers\\BackendApi\\Game\\Lottery\\LotteriesController',
                'method' => 'lotteriesMethodLists',
                'menu_group_id' => 12,
                'title' => '彩种玩法展示接口',
                'description' => NULL,
                'created_at' => NULL,
                'updated_at' => '2019-06-04 17:30:19',
            ),
            32 => 
            array (
                'id' => 35,
                'route_name' => 'backend-api.region.detail',
                'controller' => 'App\\Http\\Controllers\\BackendApi\\Users\\District\\RegionController',
                'method' => 'detail',
                'menu_group_id' => 61,
                'title' => '获取省-市-县列表',
                'description' => NULL,
                'created_at' => NULL,
                'updated_at' => '2019-06-04 17:44:29',
            ),
            33 => 
            array (
                'id' => 36,
                'route_name' => 'backend-api.region.get_town',
                'controller' => 'App\\Http\\Controllers\\BackendApi\\Users\\District\\RegionController',
                'method' => 'getTown',
                'menu_group_id' => 61,
                'title' => '获取镇级行政区',
                'description' => NULL,
                'created_at' => NULL,
                'updated_at' => '2019-06-04 17:44:40',
            ),
            34 => 
            array (
                'id' => 37,
                'route_name' => 'backend-api.region.search_town',
                'controller' => 'App\\Http\\Controllers\\BackendApi\\Users\\District\\RegionController',
                'method' => 'searchTown',
                'menu_group_id' => 61,
                'title' => '查询镇级行政区',
                'description' => NULL,
                'created_at' => NULL,
                'updated_at' => '2019-06-04 17:44:52',
            ),
            35 => 
            array (
                'id' => 40,
                'route_name' => 'backend-api.region.add',
                'controller' => 'App\\Http\\Controllers\\BackendApi\\Users\\District\\RegionController',
                'method' => 'add',
                'menu_group_id' => 61,
                'title' => '添加行政区',
                'description' => NULL,
                'created_at' => NULL,
                'updated_at' => '2019-06-04 17:46:59',
            ),
            36 => 
            array (
                'id' => 41,
                'route_name' => 'backend-api.region.edit',
                'controller' => 'App\\Http\\Controllers\\BackendApi\\Users\\District\\RegionController',
                'method' => 'edit',
                'menu_group_id' => 61,
                'title' => '编辑行政区',
                'description' => NULL,
                'created_at' => NULL,
                'updated_at' => '2019-06-04 17:47:10',
            ),
            37 => 
            array (
                'id' => 42,
                'route_name' => 'backend-api.activity.add',
                'controller' => 'App\\Http\\Controllers\\BackendApi\\Admin\\Activity\\ActivityInfosCont',
                'method' => 'add',
                'menu_group_id' => 5,
                'title' => '添加活动',
                'description' => NULL,
                'created_at' => NULL,
                'updated_at' => '2019-06-04 15:43:00',
            ),
            38 => 
            array (
                'id' => 43,
                'route_name' => 'backend-api.activity.edit',
                'controller' => 'App\\Http\\Controllers\\BackendApi\\Admin\\Activity\\ActivityInfosCont',
                'method' => 'edit',
                'menu_group_id' => 5,
                'title' => '编辑活动',
                'description' => NULL,
                'created_at' => NULL,
                'updated_at' => '2019-06-04 15:43:09',
            ),
            39 => 
            array (
                'id' => 44,
                'route_name' => 'backend-api.activity.delete',
                'controller' => 'App\\Http\\Controllers\\BackendApi\\Admin\\Activity\\ActivityInfosCont',
                'method' => 'delete',
                'menu_group_id' => 5,
                'title' => '删除活动',
                'description' => NULL,
                'created_at' => NULL,
                'updated_at' => '2019-06-04 15:43:24',
            ),
            40 => 
            array (
                'id' => 45,
                'route_name' => 'backend-api.activity.detail',
                'controller' => 'App\\Http\\Controllers\\BackendApi\\Admin\\Activity\\ActivityInfosCont',
                'method' => 'detail',
                'menu_group_id' => 5,
                'title' => '活动列表',
                'description' => NULL,
                'created_at' => NULL,
                'updated_at' => '2019-06-04 15:43:33',
            ),
            41 => 
            array (
                'id' => 47,
                'route_name' => 'backend-api.lotteries.lotteries-issue-lists',
                'controller' => 'App\\Http\\Controllers\\BackendApi\\Game\\Lottery\\LotteriesController',
                'method' => 'lotteryIssueLists',
                'menu_group_id' => 12,
                'title' => '奖期展示接口',
                'description' => NULL,
                'created_at' => NULL,
                'updated_at' => '2019-06-04 17:30:27',
            ),
            42 => 
            array (
                'id' => 52,
                'route_name' => 'backend-api.lotteries.lotteries-issue-generate',
                'controller' => 'App\\Http\\Controllers\\BackendApi\\Game\\Lottery\\LotteriesController',
                'method' => 'generateIssue',
                'menu_group_id' => 12,
                'title' => '奖期生成接口',
                'description' => NULL,
                'created_at' => NULL,
                'updated_at' => '2019-06-04 17:31:14',
            ),
            43 => 
            array (
                'id' => 53,
                'route_name' => 'backend-api.content.category',
                'controller' => 'App\\Http\\Controllers\\BackendApi\\Admin\\Article\\CategoryController',
                'method' => 'detail',
                'menu_group_id' => 65,
                'title' => '分类列表',
                'description' => NULL,
                'created_at' => NULL,
                'updated_at' => '2019-06-04 15:47:03',
            ),
            44 => 
            array (
                'id' => 54,
                'route_name' => 'backend-api.content.category-select',
                'controller' => 'App\\Http\\Controllers\\BackendApi\\Admin\\Article\\CategoryController',
                'method' => 'select',
                'menu_group_id' => 65,
                'title' => '文章分类列表',
                'description' => NULL,
                'created_at' => NULL,
                'updated_at' => '2019-06-04 15:47:08',
            ),
            45 => 
            array (
                'id' => 55,
                'route_name' => 'backend-api.content.detail',
                'controller' => 'App\\Http\\Controllers\\BackendApi\\Admin\\Article\\ArticlesController',
                'method' => 'detail',
                'menu_group_id' => 66,
                'title' => '文章列表',
                'description' => NULL,
                'created_at' => NULL,
                'updated_at' => '2019-06-04 18:24:29',
            ),
            46 => 
            array (
                'id' => 56,
                'route_name' => 'backend-api.content.add-articles',
                'controller' => 'App\\Http\\Controllers\\BackendApi\\Admin\\Article\\ArticlesController',
                'method' => 'addArticles',
                'menu_group_id' => 66,
                'title' => '发布文章',
                'description' => NULL,
                'created_at' => NULL,
                'updated_at' => '2019-06-04 18:24:45',
            ),
            47 => 
            array (
                'id' => 57,
                'route_name' => 'backend-api.content.edit-articles',
                'controller' => 'App\\Http\\Controllers\\BackendApi\\Admin\\Article\\ArticlesController',
                'method' => 'editArticles',
                'menu_group_id' => 66,
                'title' => '编辑文章',
                'description' => NULL,
                'created_at' => NULL,
                'updated_at' => '2019-06-04 18:24:59',
            ),
            48 => 
            array (
                'id' => 58,
                'route_name' => 'backend-api.content.delete-articles',
                'controller' => 'App\\Http\\Controllers\\BackendApi\\Admin\\Article\\ArticlesController',
                'method' => 'deleteArticles',
                'menu_group_id' => 66,
                'title' => '删除文章',
                'description' => NULL,
                'created_at' => NULL,
                'updated_at' => '2019-06-04 16:51:45',
            ),
            49 => 
            array (
                'id' => 59,
                'route_name' => 'backend-api.content.sort-articles',
                'controller' => 'App\\Http\\Controllers\\BackendApi\\Admin\\Article\\ArticlesController',
                'method' => 'sortArticles',
                'menu_group_id' => 66,
                'title' => '文章排序',
                'description' => NULL,
                'created_at' => NULL,
                'updated_at' => '2019-06-04 16:53:36',
            ),
            50 => 
            array (
                'id' => 60,
                'route_name' => 'backend-api.content.top-articles',
                'controller' => 'App\\Http\\Controllers\\BackendApi\\Admin\\Article\\ArticlesController',
                'method' => 'topArticles',
                'menu_group_id' => 66,
                'title' => '置顶文章',
                'description' => NULL,
                'created_at' => NULL,
                'updated_at' => '2019-06-04 16:53:56',
            ),
            51 => 
            array (
                'id' => 61,
                'route_name' => 'backend-api.content.upload-pic',
                'controller' => 'App\\Http\\Controllers\\BackendApi\\Admin\\Article\\ArticlesController',
                'method' => 'uploadPic',
                'menu_group_id' => 66,
                'title' => '图片上传',
                'description' => NULL,
                'created_at' => NULL,
                'updated_at' => '2019-06-04 16:54:15',
            ),
            52 => 
            array (
                'id' => 62,
                'route_name' => 'backend-api.bank.detail',
                'controller' => 'App\\Http\\Controllers\\BackendApi\\Admin\\FundOperate\\BankController',
                'method' => 'detail',
                'menu_group_id' => 69,
                'title' => '银行列表',
                'description' => NULL,
                'created_at' => NULL,
                'updated_at' => '2019-06-04 16:55:41',
            ),
            53 => 
            array (
                'id' => 63,
                'route_name' => 'backend-api.bank.add-bank',
                'controller' => 'App\\Http\\Controllers\\BackendApi\\Admin\\FundOperate\\BankController',
                'method' => 'addBank',
                'menu_group_id' => 69,
                'title' => '添加银行',
                'description' => NULL,
                'created_at' => NULL,
                'updated_at' => '2019-06-04 16:56:08',
            ),
            54 => 
            array (
                'id' => 64,
                'route_name' => 'backend-api.bank.edit-bank',
                'controller' => 'App\\Http\\Controllers\\BackendApi\\Admin\\FundOperate\\BankController',
                'method' => 'editBank',
                'menu_group_id' => 69,
                'title' => '编辑银行',
                'description' => NULL,
                'created_at' => NULL,
                'updated_at' => '2019-06-04 17:00:49',
            ),
            55 => 
            array (
                'id' => 65,
                'route_name' => 'backend-api.bank.delete-bank',
                'controller' => 'App\\Http\\Controllers\\BackendApi\\Admin\\FundOperate\\BankController',
                'method' => 'deleteBank',
                'menu_group_id' => 69,
                'title' => '删除银行',
                'description' => NULL,
                'created_at' => NULL,
                'updated_at' => '2019-06-04 17:01:18',
            ),
            56 => 
            array (
                'id' => 66,
                'route_name' => 'backend-api.activity.edit-actype',
                'controller' => NULL,
                'method' => NULL,
                'menu_group_id' => 64,
                'title' => '编辑活动分类',
                'description' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            57 => 
            array (
                'id' => 70,
                'route_name' => 'backend-api.fundOperation.users',
                'controller' => NULL,
                'method' => NULL,
                'menu_group_id' => 66,
                'title' => '资金操作列表',
                'description' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            58 => 
            array (
                'id' => 71,
                'route_name' => 'backend-api.fundOperation.add-fund',
                'controller' => 'App\\Http\\Controllers\\BackendApi\\Admin\\FundOperate\\FundOperationC',
                'method' => 'addFund',
                'menu_group_id' => 70,
                'title' => '增加额度',
                'description' => NULL,
                'created_at' => NULL,
                'updated_at' => '2019-06-04 18:26:17',
            ),
            59 => 
            array (
                'id' => 72,
                'route_name' => 'backend-api.menu.allRequireInfos',
                'controller' => 'App\\Http\\Controllers\\BackendApi\\DeveloperUsage\\Backend\\Menu\\Menu',
                'method' => 'allRequireInfos',
                'menu_group_id' => 81,
                'title' => '开发管理菜单操作相关需要的数据',
                'description' => NULL,
                'created_at' => NULL,
                'updated_at' => '2019-06-04 18:03:42',
            ),
            60 => 
            array (
                'id' => 73,
                'route_name' => 'backend-api.menu.changeParent',
                'controller' => 'App\\Http\\Controllers\\BackendApi\\DeveloperUsage\\Backend\\Menu\\Menu',
                'method' => 'changeParent',
                'menu_group_id' => 81,
                'title' => '开发管理拖拽分父级接口',
                'description' => NULL,
                'created_at' => NULL,
                'updated_at' => '2019-06-04 18:03:52',
            ),
            61 => 
            array (
                'id' => 74,
                'route_name' => 'backend-api.menu.add',
                'controller' => 'App\\Http\\Controllers\\BackendApi\\DeveloperUsage\\Backend\\Menu\\Menu',
                'method' => 'add',
                'menu_group_id' => 81,
                'title' => '开发管理菜单添加接口',
                'description' => NULL,
                'created_at' => NULL,
                'updated_at' => '2019-06-04 18:04:39',
            ),
            62 => 
            array (
                'id' => 75,
                'route_name' => 'backend-api.fundOperation.admins',
                'controller' => 'App\\Http\\Controllers\\BackendApi\\Admin\\FundOperate\\FundOperationC',
                'method' => 'admins',
                'menu_group_id' => 70,
                'title' => '资金的操作列表',
                'description' => NULL,
                'created_at' => NULL,
                'updated_at' => '2019-06-04 17:05:33',
            ),
            63 => 
            array (
                'id' => 76,
                'route_name' => 'backend-api.fundOperation.add-fund',
                'controller' => 'App\\Http\\Controllers\\BackendApi\\Admin\\FundOperate\\FundOperationC',
                'method' => 'addFund',
                'menu_group_id' => 70,
                'title' => '给管理员增加额度',
                'description' => NULL,
                'created_at' => NULL,
                'updated_at' => '2019-06-04 17:03:08',
            ),
            64 => 
            array (
                'id' => 77,
                'route_name' => 'backend-api.fundOperation.every-day-fund',
                'controller' => 'App\\Http\\Controllers\\BackendApi\\Admin\\FundOperate\\FundOperationC',
                'method' => 'everyDayFund',
                'menu_group_id' => 70,
                'title' => '设置每日人工充值额度',
                'description' => NULL,
                'created_at' => NULL,
                'updated_at' => '2019-06-04 17:03:23',
            ),
            65 => 
            array (
                'id' => 79,
                'route_name' => 'backend-api.artificialRecharge.users',
                'controller' => 'App\\Http\\Controllers\\BackendApi\\Users\\Fund\\ArtificialRechargeCon',
                'method' => 'users',
                'menu_group_id' => 80,
                'title' => '人工充值列表',
                'description' => NULL,
                'created_at' => NULL,
                'updated_at' => '2019-06-04 17:52:13',
            ),
            66 => 
            array (
                'id' => 80,
                'route_name' => 'backend-api.artificialRecharge.add',
                'controller' => 'App\\Http\\Controllers\\BackendApi\\Users\\Fund\\ArtificialRechargeCon',
                'method' => 'recharge',
                'menu_group_id' => 80,
                'title' => '给用户人工充值',
                'description' => NULL,
                'created_at' => NULL,
                'updated_at' => '2019-06-04 18:05:01',
            ),
            67 => 
            array (
                'id' => 81,
                'route_name' => 'backend-api.menu.edit',
                'controller' => 'App\\Http\\Controllers\\BackendApi\\DeveloperUsage\\Backend\\Menu\\Menu',
                'method' => 'edit',
                'menu_group_id' => 81,
                'title' => '菜单编辑接口',
                'description' => NULL,
                'created_at' => NULL,
                'updated_at' => '2019-06-04 18:04:50',
            ),
            68 => 
            array (
                'id' => 82,
                'route_name' => 'backend-api.menu.delete',
                'controller' => 'App\\Http\\Controllers\\BackendApi\\DeveloperUsage\\Backend\\Menu\\Menu',
                'method' => 'delete',
                'menu_group_id' => 81,
                'title' => '菜单删除接口',
                'description' => NULL,
                'created_at' => NULL,
                'updated_at' => '2019-06-04 18:05:01',
            ),
            69 => 
            array (
                'id' => 83,
                'route_name' => 'backend-api.RechargeCheck.detail',
                'controller' => 'App\\Http\\Controllers\\BackendApi\\Users\\Fund\\RechargeCheckControll',
                'method' => 'detail',
                'menu_group_id' => 97,
                'title' => '充值审核列表',
                'description' => NULL,
                'created_at' => NULL,
                'updated_at' => '2019-06-04 18:06:25',
            ),
            70 => 
            array (
                'id' => 84,
                'route_name' => 'backend-api.RechargeCheck.audit-success',
                'controller' => 'App\\Http\\Controllers\\BackendApi\\Users\\Fund\\RechargeCheckControll',
                'method' => 'auditSuccess',
                'menu_group_id' => 97,
                'title' => '充值审核通过',
                'description' => NULL,
                'created_at' => NULL,
                'updated_at' => '2019-06-04 17:59:50',
            ),
            71 => 
            array (
                'id' => 85,
                'route_name' => 'backend-api.RechargeCheck.audit-failure',
                'controller' => 'App\\Http\\Controllers\\BackendApi\\Users\\Fund\\RechargeCheckControll',
                'method' => 'auditFailure',
                'menu_group_id' => 97,
                'title' => '充值审核驳回',
                'description' => NULL,
                'created_at' => NULL,
                'updated_at' => '2019-06-04 18:00:34',
            ),
            72 => 
            array (
                'id' => 86,
                'route_name' => 'backend-api.fundOperation.fund-change-log',
                'controller' => 'App\\Http\\Controllers\\BackendApi\\Admin\\FundOperate\\FundOperationC',
                'method' => 'fundChangeLog',
                'menu_group_id' => 70,
                'title' => '查看管理员充值额度记录',
                'description' => NULL,
                'created_at' => NULL,
                'updated_at' => '2019-06-04 17:03:37',
            ),
            73 => 
            array (
                'id' => 87,
                'route_name' => 'backend-api.accountChangeType.detail',
                'controller' => 'App\\Http\\Controllers\\BackendApi\\Users\\Fund\\AccountChangeTypeCont',
                'method' => 'detail',
                'menu_group_id' => 99,
                'title' => '帐变类型列表',
                'description' => NULL,
                'created_at' => NULL,
                'updated_at' => '2019-06-04 18:00:48',
            ),
            74 => 
            array (
                'id' => 88,
                'route_name' => 'backend-api.accountChangeType.add',
                'controller' => 'App\\Http\\Controllers\\BackendApi\\Users\\Fund\\AccountChangeTypeCont',
                'method' => 'add',
                'menu_group_id' => 99,
                'title' => '添加帐变类型',
                'description' => NULL,
                'created_at' => NULL,
                'updated_at' => '2019-06-04 18:01:19',
            ),
            75 => 
            array (
                'id' => 89,
                'route_name' => 'backend-api.accountChangeType.edit',
                'controller' => 'App\\Http\\Controllers\\BackendApi\\Users\\Fund\\AccountChangeTypeCont',
                'method' => 'edit',
                'menu_group_id' => 99,
                'title' => '编辑帐变类型',
                'description' => NULL,
                'created_at' => NULL,
                'updated_at' => '2019-06-04 18:01:34',
            ),
            76 => 
            array (
                'id' => 90,
                'route_name' => 'backend-api.accountChangeType.delete',
                'controller' => 'App\\Http\\Controllers\\BackendApi\\Users\\Fund\\AccountChangeTypeCont',
                'method' => 'delete',
                'menu_group_id' => 99,
                'title' => '删除帐变类型',
                'description' => NULL,
                'created_at' => NULL,
                'updated_at' => '2019-06-04 18:01:49',
            ),
            77 => 
            array (
                'id' => 91,
                'route_name' => 'backend-api.route.detail',
                'controller' => 'App\\Http\\Controllers\\BackendApi\\DeveloperUsage\\Backend\\Routes\\Ro',
                'method' => 'detail',
                'menu_group_id' => 100,
                'title' => '路由管理列表',
                'description' => NULL,
                'created_at' => NULL,
                'updated_at' => '2019-06-04 18:07:02',
            ),
            78 => 
            array (
                'id' => 92,
                'route_name' => 'backend-api.route.add',
                'controller' => 'App\\Http\\Controllers\\BackendApi\\DeveloperUsage\\Backend\\Routes\\Ro',
                'method' => 'add',
                'menu_group_id' => 100,
                'title' => '添加路由',
                'description' => NULL,
                'created_at' => NULL,
                'updated_at' => '2019-06-04 18:06:06',
            ),
            79 => 
            array (
                'id' => 93,
                'route_name' => 'backend-api.route.edit',
                'controller' => 'App\\Http\\Controllers\\BackendApi\\DeveloperUsage\\Backend\\Routes\\Ro',
                'method' => 'edit',
                'menu_group_id' => 100,
                'title' => '编辑路由',
                'description' => NULL,
                'created_at' => NULL,
                'updated_at' => '2019-06-04 18:27:21',
            ),
            80 => 
            array (
                'id' => 94,
                'route_name' => 'backend-api.route.delete',
                'controller' => 'App\\Http\\Controllers\\BackendApi\\DeveloperUsage\\Backend\\Routes\\Ro',
                'method' => 'delete',
                'menu_group_id' => 100,
                'title' => '删除路由',
                'description' => NULL,
                'created_at' => NULL,
                'updated_at' => '2019-06-04 18:06:18',
            ),
            81 => 
            array (
                'id' => 97,
                'route_name' => 'backend-api.advertisementType.detail',
                'controller' => 'App\\Http\\Controllers\\BackendApi\\Admin\\Advertisement\\Advertisemen',
                'method' => 'detail',
                'menu_group_id' => 102,
                'title' => '获取广告分类列表',
                'description' => NULL,
                'created_at' => '2019-05-17 16:50:08',
                'updated_at' => '2019-06-04 18:18:12',
            ),
            82 => 
            array (
                'id' => 98,
                'route_name' => 'backend-api.advertisementType.edit',
                'controller' => 'App\\Http\\Controllers\\BackendApi\\Admin\\Advertisement\\Advertisemen',
                'method' => 'edit',
                'menu_group_id' => 102,
                'title' => '编辑广告类型',
                'description' => NULL,
                'created_at' => '2019-05-17 16:50:25',
                'updated_at' => '2019-06-04 18:18:23',
            ),
            83 => 
            array (
                'id' => 99,
                'route_name' => 'backend-api.homepage.detail',
                'controller' => NULL,
                'method' => NULL,
                'menu_group_id' => 105,
                'title' => '主页管理列表',
                'description' => NULL,
                'created_at' => '2019-05-20 20:29:13',
                'updated_at' => '2019-05-20 20:29:13',
            ),
            84 => 
            array (
                'id' => 100,
                'route_name' => 'backend-api.homepage.upload-pic',
                'controller' => 'App\\Http\\Controllers\\BackendApi\\Admin\\Homepage\\HomepageControlle',
                'method' => 'uploadPic',
                'menu_group_id' => 104,
                'title' => '上传logo',
                'description' => NULL,
                'created_at' => '2019-05-20 21:12:30',
                'updated_at' => '2019-06-04 17:03:52',
            ),
            85 => 
            array (
                'id' => 101,
                'route_name' => 'backend-api.homepageRotationChart.detail',
                'controller' => 'App\\Http\\Controllers\\BackendApi\\Admin\\Homepage\\HomepageRotationC',
                'method' => 'detail',
                'menu_group_id' => 107,
                'title' => '轮播图列表',
                'description' => NULL,
                'created_at' => '2019-05-22 11:01:25',
                'updated_at' => '2019-06-04 17:05:59',
            ),
            86 => 
            array (
                'id' => 102,
                'route_name' => 'backend-api.homepageRotationChart.add',
                'controller' => 'App\\Http\\Controllers\\BackendApi\\Admin\\Homepage\\HomepageRotationC',
                'method' => 'add',
                'menu_group_id' => 107,
                'title' => '添加轮播图',
                'description' => NULL,
                'created_at' => '2019-05-22 11:01:52',
                'updated_at' => '2019-06-04 17:08:32',
            ),
            87 => 
            array (
                'id' => 103,
                'route_name' => 'backend-api.homepageRotationChart.edit',
                'controller' => 'App\\Http\\Controllers\\BackendApi\\Admin\\Homepage\\HomepageRotationC',
                'method' => 'edit',
                'menu_group_id' => 107,
                'title' => '编辑轮播图',
                'description' => NULL,
                'created_at' => '2019-05-22 11:02:21',
                'updated_at' => '2019-06-04 17:08:49',
            ),
            88 => 
            array (
                'id' => 104,
                'route_name' => 'backend-api.homepageRotationChart.delete',
                'controller' => 'App\\Http\\Controllers\\BackendApi\\Admin\\Homepage\\HomepageRotationC',
                'method' => 'delete',
                'menu_group_id' => 107,
                'title' => '删除轮播图',
                'description' => NULL,
                'created_at' => '2019-05-22 11:02:41',
                'updated_at' => '2019-06-04 17:09:07',
            ),
            89 => 
            array (
                'id' => 105,
                'route_name' => 'backend-api.homepageRotationChart.activity-list',
                'controller' => 'App\\Http\\Controllers\\BackendApi\\Admin\\Homepage\\HomepageRotationC',
                'method' => 'activityList',
                'menu_group_id' => 108,
                'title' => '轮播图选的活动列表',
                'description' => NULL,
                'created_at' => '2019-05-22 11:03:02',
                'updated_at' => '2019-06-04 17:09:36',
            ),
            90 => 
            array (
                'id' => 106,
                'route_name' => 'backend-api.homepageRotationChart.sort',
                'controller' => 'App\\Http\\Controllers\\BackendApi\\Admin\\Homepage\\HomepageRotationC',
                'method' => 'sort',
                'menu_group_id' => 107,
                'title' => '轮播拖动',
                'description' => NULL,
                'created_at' => '2019-05-22 14:24:25',
                'updated_at' => '2019-06-04 17:09:20',
            ),
            91 => 
            array (
                'id' => 107,
                'route_name' => 'backend-api.homepage.edit',
                'controller' => 'App\\Http\\Controllers\\BackendApi\\Admin\\Homepage\\HomepageControlle',
                'method' => 'edit',
                'menu_group_id' => 108,
                'title' => '编辑主页模块信息',
                'description' => NULL,
                'created_at' => '2019-05-22 18:40:28',
                'updated_at' => '2019-06-04 17:14:18',
            ),
            92 => 
            array (
                'id' => 108,
                'route_name' => 'backend-api.partnerAdmin.reset-password',
                'controller' => 'App\\Http\\Controllers\\BackendApi\\BackendAuthController',
                'method' => 'updatePAdmPassword',
                'menu_group_id' => 11,
                'title' => '更改密码',
                'description' => NULL,
                'created_at' => '2019-05-23 15:36:37',
                'updated_at' => '2019-06-04 15:31:08',
            ),
            93 => 
            array (
                'id' => 109,
                'route_name' => 'backend-api.lotteries.method-group-switch',
                'controller' => 'App\\Http\\Controllers\\BackendApi\\Game\\Lottery\\LotteriesController',
                'method' => 'methodGroupSwitch',
                'menu_group_id' => 14,
                'title' => '玩法组开关',
                'description' => NULL,
                'created_at' => '2019-05-24 16:10:09',
                'updated_at' => '2019-06-04 17:31:23',
            ),
            94 => 
            array (
                'id' => 110,
                'route_name' => 'backend-api.frontendAllocatedModel.detail',
                'controller' => 'App\\Http\\Controllers\\BackendApi\\DeveloperUsage\\Frontend\\Frontend',
                'method' => 'detail',
                'menu_group_id' => 111,
                'title' => '前端模块管理列表',
                'description' => NULL,
                'created_at' => '2019-05-24 17:10:59',
                'updated_at' => '2019-06-04 18:08:00',
            ),
            95 => 
            array (
                'id' => 111,
                'route_name' => 'backend-api.frontendAllocatedModel.add',
                'controller' => 'App\\Http\\Controllers\\BackendApi\\DeveloperUsage\\Frontend\\Frontend',
                'method' => 'add',
                'menu_group_id' => 111,
                'title' => '添加模块',
                'description' => NULL,
                'created_at' => '2019-05-24 17:12:05',
                'updated_at' => '2019-06-04 18:08:12',
            ),
            96 => 
            array (
                'id' => 112,
                'route_name' => 'backend-api.frontendAllocatedModel.edit',
                'controller' => 'App\\Http\\Controllers\\BackendApi\\DeveloperUsage\\Frontend\\Frontend',
                'method' => 'edit',
                'menu_group_id' => 111,
                'title' => '编辑模块',
                'description' => NULL,
                'created_at' => '2019-05-24 17:12:38',
                'updated_at' => '2019-06-04 18:09:08',
            ),
            97 => 
            array (
                'id' => 113,
                'route_name' => 'backend-api.frontendAllocatedModel.delete',
                'controller' => 'App\\Http\\Controllers\\BackendApi\\DeveloperUsage\\Frontend\\Frontend',
                'method' => 'delete',
                'menu_group_id' => 111,
                'title' => '删除模块',
                'description' => NULL,
                'created_at' => '2019-05-24 17:13:05',
                'updated_at' => '2019-06-04 18:09:18',
            ),
            98 => 
            array (
                'id' => 114,
                'route_name' => 'backend-api.popularLotteries.detail-one',
                'controller' => 'App\\Http\\Controllers\\BackendApi\\Admin\\Homepage\\PopularLotteriesC',
                'method' => 'detailOne',
                'menu_group_id' => 108,
                'title' => '热门彩票一列表',
                'description' => NULL,
                'created_at' => '2019-05-24 17:46:03',
                'updated_at' => '2019-06-04 17:14:27',
            ),
            99 => 
            array (
                'id' => 115,
                'route_name' => 'backend-api.popularLotteries.detail-two',
                'controller' => 'App\\Http\\Controllers\\BackendApi\\Admin\\Homepage\\PopularLotteriesC',
                'method' => 'detailTwo',
                'menu_group_id' => 108,
                'title' => '热门彩票二列表 API',
                'description' => NULL,
                'created_at' => '2019-05-24 17:46:43',
                'updated_at' => '2019-06-04 17:14:39',
            ),
            100 => 
            array (
                'id' => 116,
                'route_name' => 'backend-api.popularLotteries.add',
                'controller' => 'App\\Http\\Controllers\\BackendApi\\Admin\\Homepage\\PopularLotteriesC',
                'method' => 'add',
                'menu_group_id' => 108,
                'title' => '添加热门彩票API',
                'description' => NULL,
                'created_at' => '2019-05-24 17:47:12',
                'updated_at' => '2019-06-04 17:16:15',
            ),
            101 => 
            array (
                'id' => 117,
                'route_name' => 'backend-api.popularLotteries.lotteries-list',
                'controller' => 'App\\Http\\Controllers\\BackendApi\\Admin\\Homepage\\PopularLotteriesC',
                'method' => 'lotteriesList',
                'menu_group_id' => 108,
                'title' => '添加热门彩票时选择的彩种列表',
                'description' => NULL,
                'created_at' => '2019-05-24 17:47:37',
                'updated_at' => '2019-06-04 17:16:24',
            ),
            102 => 
            array (
                'id' => 118,
                'route_name' => 'backend-api.popularLotteries.edit',
                'controller' => 'App\\Http\\Controllers\\BackendApi\\Admin\\Homepage\\PopularLotteriesC',
                'method' => 'edit',
                'menu_group_id' => 108,
                'title' => '编辑热门彩票',
                'description' => NULL,
                'created_at' => '2019-05-24 17:48:21',
                'updated_at' => '2019-06-04 17:16:35',
            ),
            103 => 
            array (
                'id' => 119,
                'route_name' => 'backend-api.popularLotteries.delete',
                'controller' => 'App\\Http\\Controllers\\BackendApi\\Admin\\Homepage\\PopularLotteriesC',
                'method' => 'delete',
                'menu_group_id' => 108,
                'title' => '删除热门彩票',
                'description' => NULL,
                'created_at' => '2019-05-24 17:48:42',
                'updated_at' => '2019-06-04 17:16:43',
            ),
            104 => 
            array (
                'id' => 120,
                'route_name' => 'backend-api.popularLotteries.lotteries-sort',
                'controller' => 'App\\Http\\Controllers\\BackendApi\\Admin\\Homepage\\PopularLotteriesC',
                'method' => 'lotteriesSort',
                'menu_group_id' => 108,
                'title' => '热门彩种排序',
                'description' => NULL,
                'created_at' => '2019-05-24 21:34:17',
                'updated_at' => '2019-06-04 17:16:51',
            ),
            105 => 
            array (
                'id' => 121,
                'route_name' => 'backend-api.notice.detail',
                'controller' => 'App\\Http\\Controllers\\BackendApi\\Admin\\Notice\\NoticeController',
                'method' => 'detail',
                'menu_group_id' => 112,
                'title' => '公告列表',
                'description' => NULL,
                'created_at' => '2019-05-25 11:31:45',
                'updated_at' => '2019-06-04 17:19:38',
            ),
            106 => 
            array (
                'id' => 122,
                'route_name' => 'backend-api.notice.add',
                'controller' => 'App\\Http\\Controllers\\BackendApi\\Admin\\Notice\\NoticeController',
                'method' => 'add',
                'menu_group_id' => 112,
                'title' => '添加公告',
                'description' => NULL,
                'created_at' => '2019-05-25 11:32:32',
                'updated_at' => '2019-06-04 17:19:43',
            ),
            107 => 
            array (
                'id' => 123,
                'route_name' => 'backend-api.notice.edit',
                'controller' => 'App\\Http\\Controllers\\BackendApi\\Admin\\Notice\\NoticeController',
                'method' => 'edit',
                'menu_group_id' => 112,
                'title' => '编辑公告',
                'description' => NULL,
                'created_at' => '2019-05-25 11:32:54',
                'updated_at' => '2019-06-04 17:19:51',
            ),
            108 => 
            array (
                'id' => 124,
                'route_name' => 'backend-api.notice.delete',
                'controller' => 'App\\Http\\Controllers\\BackendApi\\Admin\\Notice\\NoticeController',
                'method' => 'delete',
                'menu_group_id' => 112,
                'title' => '删除公告',
                'description' => NULL,
                'created_at' => '2019-05-25 11:33:25',
                'updated_at' => '2019-06-04 17:20:02',
            ),
            109 => 
            array (
                'id' => 125,
                'route_name' => 'backend-api.notice.sort',
                'controller' => 'App\\Http\\Controllers\\BackendApi\\Admin\\Notice\\NoticeController',
                'method' => 'sort',
                'menu_group_id' => 112,
                'title' => '公告排序',
                'description' => NULL,
                'created_at' => '2019-05-25 11:34:06',
                'updated_at' => '2019-06-04 17:24:14',
            ),
            110 => 
            array (
                'id' => 126,
                'route_name' => 'backend-api.homepage.nav-one',
                'controller' => 'App\\Http\\Controllers\\BackendApi\\Admin\\Homepage\\HomepageControlle',
                'method' => 'navOne',
                'menu_group_id' => 105,
                'title' => '导航一列表列表',
                'description' => NULL,
                'created_at' => '2019-05-25 14:40:56',
                'updated_at' => '2019-06-04 17:04:35',
            ),
            111 => 
            array (
                'id' => 127,
                'route_name' => 'backend-api.homepage.page-model',
                'controller' => 'App\\Http\\Controllers\\BackendApi\\Admin\\Homepage\\HomepageControlle',
                'method' => 'pageModel',
                'menu_group_id' => 108,
                'title' => '主题板块列表',
                'description' => NULL,
                'created_at' => '2019-05-25 14:42:25',
                'updated_at' => '2019-06-04 17:16:59',
            ),
            112 => 
            array (
                'id' => 128,
                'route_name' => 'backend-api.userhandle.user_account_change',
                'controller' => 'App\\Http\\Controllers\\BackendApi\\Users\\UserHandleController',
                'method' => 'userAccountChange',
                'menu_group_id' => 27,
                'title' => '账变记录',
                'description' => NULL,
                'created_at' => '2019-05-25 14:51:00',
                'updated_at' => '2019-06-04 17:43:00',
            ),
            113 => 
            array (
                'id' => 129,
                'route_name' => 'backend-api.userhandle.user_recharge_history',
                'controller' => 'App\\Http\\Controllers\\BackendApi\\Users\\UserHandleController',
                'method' => 'userRechargeHistory',
                'menu_group_id' => 27,
                'title' => '充值记录',
                'description' => NULL,
                'created_at' => '2019-05-25 14:51:44',
                'updated_at' => '2019-06-04 17:43:49',
            ),
            114 => 
            array (
                'id' => 130,
                'route_name' => 'backend-api.userhandle.deduction_balance',
                'controller' => 'App\\Http\\Controllers\\BackendApi\\Users\\UserHandleController',
                'method' => 'deductionBalance',
                'menu_group_id' => 27,
                'title' => '扣减',
                'description' => NULL,
                'created_at' => '2019-05-25 16:35:12',
                'updated_at' => '2019-06-04 17:44:03',
            ),
            115 => 
            array (
                'id' => 131,
                'route_name' => 'backend-api.notice.top',
                'controller' => 'App\\Http\\Controllers\\BackendApi\\Admin\\Notice\\NoticeController',
                'method' => 'top',
                'menu_group_id' => 112,
                'title' => '公告置顶',
                'description' => NULL,
                'created_at' => '2019-05-25 17:39:56',
                'updated_at' => '2019-06-04 17:25:11',
            ),
            116 => 
            array (
                'id' => 132,
                'route_name' => 'backend-api.reportManagement.user-account-change',
                'controller' => 'App\\Http\\Controllers\\BackendApi\\Report\\reportManagementControlle',
                'method' => 'userAccountChange',
                'menu_group_id' => 49,
                'title' => '用户帐变报表',
                'description' => NULL,
                'created_at' => '2019-05-28 15:00:30',
                'updated_at' => '2019-06-04 18:02:40',
            ),
            117 => 
            array (
                'id' => 133,
                'route_name' => 'backend-api.reportManagement.user-recharge-history',
                'controller' => 'App\\Http\\Controllers\\BackendApi\\Report\\reportManagementControlle',
                'method' => 'userRechargeHistory',
                'menu_group_id' => 48,
                'title' => '充值报表',
                'description' => NULL,
                'created_at' => '2019-05-28 15:00:52',
                'updated_at' => '2019-06-04 18:02:26',
            ),
            118 => 
            array (
                'id' => 134,
                'route_name' => 'backend-api.reportManagement.account_change_type',
                'controller' => 'App\\Http\\Controllers\\BackendApi\\Report\\reportManagementControlle',
                'method' => 'accountChangeType',
                'menu_group_id' => 49,
                'title' => '获取所有账变类型',
                'description' => NULL,
                'created_at' => '2019-05-28 16:58:38',
                'updated_at' => '2019-06-04 18:02:57',
            ),
            119 => 
            array (
                'id' => 135,
                'route_name' => 'backend-api.lotteries.method-row-switch',
                'controller' => 'App\\Http\\Controllers\\BackendApi\\Game\\Lottery\\LotteriesController',
                'method' => 'methodRowSwitch',
                'menu_group_id' => 14,
                'title' => '玩法行开关',
                'description' => NULL,
                'created_at' => '2019-05-29 14:46:57',
                'updated_at' => '2019-06-04 17:31:50',
            ),
            120 => 
            array (
                'id' => 136,
                'route_name' => 'backend-api.lotteries.method-switch',
                'controller' => 'App\\Http\\Controllers\\BackendApi\\Game\\Lottery\\LotteriesController',
                'method' => 'methodSwitch',
                'menu_group_id' => 14,
                'title' => '切换玩法开关',
                'description' => NULL,
                'created_at' => '2019-05-29 14:47:39',
                'updated_at' => '2019-06-04 17:31:59',
            ),
            121 => 
            array (
                'id' => 137,
                'route_name' => 'backend-api.frontendWebRoute.detail',
                'controller' => 'App\\Http\\Controllers\\BackendApi\\DeveloperUsage\\Frontend\\Frontend',
                'method' => 'detail',
                'menu_group_id' => 111,
                'title' => '投注端路由列表',
                'description' => NULL,
                'created_at' => '2019-05-30 11:14:43',
                'updated_at' => '2019-06-04 18:28:14',
            ),
            122 => 
            array (
                'id' => 138,
                'route_name' => 'backend-api.frontendAppRoute.detail',
                'controller' => 'App\\Http\\Controllers\\BackendApi\\DeveloperUsage\\Frontend\\Frontend',
                'method' => 'detail',
                'menu_group_id' => 111,
                'title' => '投注端app路由列表',
                'description' => NULL,
                'created_at' => '2019-05-30 11:15:31',
                'updated_at' => '2019-06-04 18:10:05',
            ),
            123 => 
            array (
                'id' => 139,
                'route_name' => 'backend-api.frontendWebRoute.add',
                'controller' => 'App\\Http\\Controllers\\BackendApi\\DeveloperUsage\\Frontend\\Frontend',
                'method' => 'add',
                'menu_group_id' => 111,
                'title' => '投注端添加路由web',
                'description' => NULL,
                'created_at' => '2019-05-30 11:15:54',
                'updated_at' => '2019-06-04 18:14:59',
            ),
            124 => 
            array (
                'id' => 140,
                'route_name' => 'backend-api.frontendAppRoute.add',
                'controller' => 'App\\Http\\Controllers\\BackendApi\\DeveloperUsage\\Frontend\\Frontend',
                'method' => 'add',
                'menu_group_id' => 111,
                'title' => '投注端添加路由app',
                'description' => NULL,
                'created_at' => '2019-05-30 11:16:20',
                'updated_at' => '2019-06-04 18:12:12',
            ),
            125 => 
            array (
                'id' => 141,
                'route_name' => 'backend-api.frontendWebRoute.delete',
                'controller' => 'App\\Http\\Controllers\\BackendApi\\DeveloperUsage\\Frontend\\Frontend',
                'method' => 'delete',
                'menu_group_id' => 111,
                'title' => '投注端删除路由',
                'description' => NULL,
                'created_at' => '2019-05-30 11:16:46',
                'updated_at' => '2019-06-04 18:12:59',
            ),
            126 => 
            array (
                'id' => 142,
                'route_name' => 'backend-api.frontendAppRoute.delete',
                'controller' => 'App\\Http\\Controllers\\BackendApi\\DeveloperUsage\\Frontend\\Frontend',
                'method' => 'delete',
                'menu_group_id' => 111,
                'title' => '投注端删除路由app',
                'description' => NULL,
                'created_at' => '2019-05-30 11:17:22',
                'updated_at' => '2019-06-04 18:13:14',
            ),
            127 => 
            array (
                'id' => 143,
                'route_name' => 'backend-api.methodLevel.detail',
                'controller' => 'App\\Http\\Controllers\\BackendApi\\DeveloperUsage\\MethodLevel\\Metho',
                'method' => 'detail',
                'menu_group_id' => 113,
                'title' => '玩法等级列表',
                'description' => NULL,
                'created_at' => '2019-05-30 20:44:51',
                'updated_at' => '2019-06-04 18:16:16',
            ),
            128 => 
            array (
                'id' => 144,
                'route_name' => 'backend-api.methodLevel.add',
                'controller' => 'App\\Http\\Controllers\\BackendApi\\DeveloperUsage\\MethodLevel\\Metho',
                'method' => 'add',
                'menu_group_id' => 113,
                'title' => '添加玩法等级',
                'description' => NULL,
                'created_at' => '2019-05-30 20:45:21',
                'updated_at' => '2019-06-04 18:16:28',
            ),
            129 => 
            array (
                'id' => 145,
                'route_name' => 'backend-api.methodLevel.edit',
                'controller' => 'App\\Http\\Controllers\\BackendApi\\DeveloperUsage\\MethodLevel\\Metho',
                'method' => 'edit',
                'menu_group_id' => 113,
                'title' => '编辑玩法等级',
                'description' => NULL,
                'created_at' => '2019-05-30 20:45:38',
                'updated_at' => '2019-06-04 18:17:17',
            ),
            130 => 
            array (
                'id' => 146,
                'route_name' => 'backend-api.methodLevel.delete',
                'controller' => 'App\\Http\\Controllers\\BackendApi\\DeveloperUsage\\MethodLevel\\Metho',
                'method' => 'delete',
                'menu_group_id' => 113,
                'title' => '删除玩法等级',
                'description' => NULL,
                'created_at' => '2019-05-30 20:45:55',
                'updated_at' => '2019-06-04 18:17:30',
            ),
            131 => 
            array (
                'id' => 148,
                'route_name' => 'backend-api.frontendWebRoute.is-open',
                'controller' => 'App\\Http\\Controllers\\BackendApi\\DeveloperUsage\\Frontend\\Frontend',
                'method' => 'isOpen',
                'menu_group_id' => 111,
                'title' => 'web路由开放状态改变',
                'description' => NULL,
                'created_at' => '2019-05-31 17:55:07',
                'updated_at' => '2019-06-04 18:14:25',
            ),
            132 => 
            array (
                'id' => 149,
                'route_name' => 'backend-api.frontendAppRoute.is-open',
                'controller' => 'App\\Http\\Controllers\\BackendApi\\DeveloperUsage\\Frontend\\Frontend',
                'method' => 'isOpen',
                'menu_group_id' => 111,
                'title' => 'app路由开放状态改变',
                'description' => NULL,
                'created_at' => '2019-05-31 17:55:39',
                'updated_at' => '2019-06-04 18:14:36',
            ),
            133 => 
            array (
                'id' => 150,
                'route_name' => 'backend-api.homepage.upload-ico',
                'controller' => 'App\\Http\\Controllers\\BackendApi\\Admin\\Homepage\\HomepageControlle',
                'method' => 'uploadIco',
                'menu_group_id' => 105,
                'title' => '添加ico',
                'description' => NULL,
                'created_at' => '2019-06-03 17:21:19',
                'updated_at' => '2019-06-04 17:05:49',
            ),
            134 => 
            array (
                'id' => 151,
                'route_name' => 'backend-api.configures.generate-issue-time',
                'controller' => 'App\\Http\\Controllers\\BackendApi\\Admin\\ConfiguresController',
                'method' => 'generateIssueTime',
                'menu_group_id' => 17,
                'title' => '奖期生成时间',
                'description' => NULL,
                'created_at' => '2019-06-03 21:50:52',
                'updated_at' => '2019-06-04 17:32:36',
            ),
            135 => 
            array (
                'id' => 153,
                'route_name' => 'backend-api.configures.sys-configure-value',
                'controller' => 'App\\Http\\Controllers\\BackendApi\\Admin\\ConfiguresController',
                'method' => 'getSysConfigureValue',
                'menu_group_id' => 17,
                'title' => '生成奖期时间',
                'description' => NULL,
                'created_at' => '2019-06-04 15:18:24',
                'updated_at' => '2019-06-04 15:18:24',
            ),
            136 => 
            array (
                'id' => 154,
                'route_name' => 'backend-api.popularLotteries.detail',
                'controller' => 'App\\Http\\Controllers\\BackendApi\\Admin\\Homepage\\PopularLotteriesC',
                'method' => 'detail',
                'menu_group_id' => 108,
                'title' => '热门彩票列表',
                'description' => NULL,
                'created_at' => '2019-06-05 12:03:30',
                'updated_at' => '2019-06-05 12:03:30',
            ),
            137 => 
            array (
                'id' => 155,
                'route_name' => 'backend-api.popularMethods.detail',
                'controller' => 'App\\Http\\Controllers\\BackendApi\\Admin\\Homepage\\PopularMethodsCon',
                'method' => 'detail',
                'menu_group_id' => 108,
                'title' => '热门玩法列表',
                'description' => NULL,
                'created_at' => '2019-06-05 12:09:22',
                'updated_at' => '2019-06-05 12:09:22',
            ),
            138 => 
            array (
                'id' => 156,
                'route_name' => 'backend-api.popularMethods.add',
                'controller' => 'App\\Http\\Controllers\\BackendApi\\Admin\\Homepage\\PopularMethodsCon',
                'method' => 'add',
                'menu_group_id' => 108,
                'title' => '添加热门玩法',
                'description' => NULL,
                'created_at' => '2019-06-05 12:09:51',
                'updated_at' => '2019-06-05 12:09:51',
            ),
            139 => 
            array (
                'id' => 157,
                'route_name' => 'backend-api.popularMethods.edit',
                'controller' => 'App\\Http\\Controllers\\BackendApi\\Admin\\Homepage\\PopularMethodsCon',
                'method' => 'edit',
                'menu_group_id' => 108,
                'title' => '编辑热门玩法',
                'description' => NULL,
                'created_at' => '2019-06-05 12:10:28',
                'updated_at' => '2019-06-05 12:10:28',
            ),
            140 => 
            array (
                'id' => 158,
                'route_name' => 'backend-api.popularMethods.delete',
                'controller' => 'App\\Http\\Controllers\\BackendApi\\Admin\\Homepage\\PopularMethodsCon',
                'method' => 'delete',
                'menu_group_id' => 108,
                'title' => '删除热门玩法',
                'description' => NULL,
                'created_at' => '2019-06-05 12:10:51',
                'updated_at' => '2019-06-05 12:10:51',
            ),
            141 => 
            array (
                'id' => 159,
                'route_name' => 'backend-api.popularMethods.methods-list',
                'controller' => 'App\\Http\\Controllers\\BackendApi\\Admin\\Homepage\\PopularMethodsCon',
                'method' => 'methodsList',
                'menu_group_id' => 108,
                'title' => '添加热门玩法时的玩法列表',
                'description' => NULL,
                'created_at' => '2019-06-05 13:52:20',
                'updated_at' => '2019-06-05 13:52:20',
            ),
            142 => 
            array (
                'id' => 160,
                'route_name' => 'backend-api.popularLotteries.sort',
                'controller' => 'App\\Http\\Controllers\\BackendApi\\Admin\\Homepage\\PopularLotteriesC',
                'method' => 'sort',
                'menu_group_id' => 108,
                'title' => '热门彩票拖动排序',
                'description' => NULL,
                'created_at' => '2019-06-05 15:08:57',
                'updated_at' => '2019-06-05 15:08:57',
            ),
            143 => 
            array (
                'id' => 161,
                'route_name' => 'backend-api.popularMethods.sort',
                'controller' => 'App\\Http\\Controllers\\BackendApi\\Admin\\Homepage\\PopularMethodsCon',
                'method' => 'sort',
                'menu_group_id' => 108,
                'title' => '热门玩法拖动排序',
                'description' => NULL,
                'created_at' => '2019-06-05 15:09:42',
                'updated_at' => '2019-06-05 15:09:42',
            ),
            144 => 
            array (
                'id' => 162,
                'route_name' => 'backend-api.partnerAdminGroup.create',
                'controller' => 'App\\Http\\Controllers\\BackendApi\\Admin\\PartnerAdminGroupControlle',
                'method' => 'create',
                'menu_group_id' => 11,
                'title' => '创建组',
                'description' => NULL,
                'created_at' => '2019-06-05 15:52:36',
                'updated_at' => '2019-06-05 15:52:36',
            ),
            145 => 
            array (
                'id' => 163,
                'route_name' => 'backend-api.loghandle.frontend-list',
                'controller' => 'App\\Http\\Controllers\\BackendApi\\Admin\\Log\\HandleLogController',
                'method' => 'frontendLogs',
                'menu_group_id' => 114,
                'title' => '获取前台操作日志列表',
                'description' => NULL,
                'created_at' => '2019-06-06 11:57:04',
                'updated_at' => '2019-06-06 11:57:04',
            ),
        ));
        
        
    }
}