<?php

use Illuminate\Database\Seeder;

class FrontendLotteryFnfBetableMethodsTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('frontend_lottery_fnf_betable_methods')->delete();
        
        \DB::table('frontend_lottery_fnf_betable_methods')->insert(array (
            0 => 
            array (
                'id' => 81,
                'series_id' => 'ssc',
                'lottery_name' => '重庆时时彩',
                'lottery_id' => 'cqssc',
                'method_id' => 'HBDW31',
                'method_name' => '后三一码不定位',
                'method_group' => 'BDW',
                'method_row' => '3budingwei',
                'group_sort' => 0,
                'row_sort' => 0,
                'method_sort' => 0,
                'show' => 1,
                'status' => 0,
                'total' => 1000,
                'created_at' => NULL,
                'updated_at' => '2019-05-27 16:38:04',
            ),
            1 => 
            array (
                'id' => 82,
                'series_id' => 'ssc',
                'lottery_name' => '重庆时时彩',
                'lottery_id' => 'cqssc',
                'method_id' => 'QBDW31',
                'method_name' => '前三一码不定位',
                'method_group' => 'BDW',
                'method_row' => '3budingwei',
                'group_sort' => 0,
                'row_sort' => 0,
                'method_sort' => 0,
                'show' => 1,
                'status' => 0,
                'total' => 1000,
                'created_at' => NULL,
                'updated_at' => '2019-05-27 16:22:37',
            ),
            2 => 
            array (
                'id' => 83,
                'series_id' => 'ssc',
                'lottery_name' => '重庆时时彩',
                'lottery_id' => 'cqssc',
                'method_id' => 'HBDW32',
                'method_name' => '后三二码不定位',
                'method_group' => 'BDW',
                'method_row' => '3budingwei',
                'group_sort' => 0,
                'row_sort' => 0,
                'method_sort' => 0,
                'show' => 1,
                'status' => 0,
                'total' => 1000,
                'created_at' => NULL,
                'updated_at' => '2019-05-27 16:38:05',
            ),
            3 => 
            array (
                'id' => 84,
                'series_id' => 'ssc',
                'lottery_name' => '重庆时时彩',
                'lottery_id' => 'cqssc',
                'method_id' => 'QBDW32',
                'method_name' => '前三二码不定位',
                'method_group' => 'BDW',
                'method_row' => '3budingwei',
                'group_sort' => 0,
                'row_sort' => 0,
                'method_sort' => 0,
                'show' => 1,
                'status' => 0,
                'total' => 1000,
                'created_at' => NULL,
                'updated_at' => '2019-05-27 16:22:37',
            ),
            4 => 
            array (
                'id' => 85,
                'series_id' => 'ssc',
                'lottery_name' => '重庆时时彩',
                'lottery_id' => 'cqssc',
                'method_id' => 'BDW41',
                'method_name' => '四星一码不定位',
                'method_group' => 'BDW',
                'method_row' => '4budingwei',
                'group_sort' => 0,
                'row_sort' => 0,
                'method_sort' => 0,
                'show' => 1,
                'status' => 0,
                'total' => 10000,
                'created_at' => NULL,
                'updated_at' => '2019-05-27 16:38:05',
            ),
            5 => 
            array (
                'id' => 86,
                'series_id' => 'ssc',
                'lottery_name' => '重庆时时彩',
                'lottery_id' => 'cqssc',
                'method_id' => 'BDW42',
                'method_name' => '四星二码不定位',
                'method_group' => 'BDW',
                'method_row' => '4budingwei',
                'group_sort' => 0,
                'row_sort' => 0,
                'method_sort' => 0,
                'show' => 1,
                'status' => 0,
                'total' => 10000,
                'created_at' => NULL,
                'updated_at' => '2019-05-27 16:38:05',
            ),
            6 => 
            array (
                'id' => 87,
                'series_id' => 'ssc',
                'lottery_name' => '重庆时时彩',
                'lottery_id' => 'cqssc',
                'method_id' => 'BDW52',
                'method_name' => '五星二码不定位',
                'method_group' => 'BDW',
                'method_row' => '5budingwei',
                'group_sort' => 0,
                'row_sort' => 0,
                'method_sort' => 0,
                'show' => 1,
                'status' => 0,
                'total' => 100000,
                'created_at' => NULL,
                'updated_at' => '2019-05-27 16:38:05',
            ),
            7 => 
            array (
                'id' => 88,
                'series_id' => 'ssc',
                'lottery_name' => '重庆时时彩',
                'lottery_id' => 'cqssc',
                'method_id' => 'BDW53',
                'method_name' => '五星三码不定位',
                'method_group' => 'BDW',
                'method_row' => '5budingwei',
                'group_sort' => 0,
                'row_sort' => 0,
                'method_sort' => 0,
                'show' => 1,
                'status' => 0,
                'total' => 100000,
                'created_at' => NULL,
                'updated_at' => '2019-05-27 16:38:05',
            ),
            8 => 
            array (
                'id' => 93,
                'series_id' => 'ssc',
                'lottery_name' => '重庆时时彩',
                'lottery_id' => 'cqssc',
                'method_id' => 'YFFS',
                'method_name' => '一帆风顺',
                'method_group' => 'QW',
                'method_row' => 'quwei',
                'group_sort' => 0,
                'row_sort' => 0,
                'method_sort' => 0,
                'show' => 1,
                'status' => 1,
                'total' => 100000,
                'created_at' => NULL,
                'updated_at' => '2019-05-27 16:38:05',
            ),
            9 => 
            array (
                'id' => 94,
                'series_id' => 'ssc',
                'lottery_name' => '重庆时时彩',
                'lottery_id' => 'cqssc',
                'method_id' => 'HSCS',
                'method_name' => '好事成双',
                'method_group' => 'QW',
                'method_row' => 'quwei',
                'group_sort' => 0,
                'row_sort' => 0,
                'method_sort' => 0,
                'show' => 1,
                'status' => 1,
                'total' => 100000,
                'created_at' => NULL,
                'updated_at' => '2019-05-27 16:38:05',
            ),
            10 => 
            array (
                'id' => 95,
                'series_id' => 'ssc',
                'lottery_name' => '重庆时时彩',
                'lottery_id' => 'cqssc',
                'method_id' => 'SXBX',
                'method_name' => '三星报喜',
                'method_group' => 'QW',
                'method_row' => 'quwei',
                'group_sort' => 0,
                'row_sort' => 0,
                'method_sort' => 0,
                'show' => 1,
                'status' => 1,
                'total' => 100000,
                'created_at' => NULL,
                'updated_at' => '2019-05-27 16:38:05',
            ),
            11 => 
            array (
                'id' => 96,
                'series_id' => 'ssc',
                'lottery_name' => '重庆时时彩',
                'lottery_id' => 'cqssc',
                'method_id' => 'SJFC',
                'method_name' => '四季发财',
                'method_group' => 'QW',
                'method_row' => 'quwei',
                'group_sort' => 0,
                'row_sort' => 0,
                'method_sort' => 0,
                'show' => 1,
                'status' => 1,
                'total' => 100000,
                'created_at' => NULL,
                'updated_at' => '2019-05-27 16:38:05',
            ),
            12 => 
            array (
                'id' => 97,
                'series_id' => 'ssc',
                'lottery_name' => '重庆时时彩',
                'lottery_id' => 'cqssc',
                'method_id' => 'LHWQ',
                'method_name' => '龙虎万千',
                'method_group' => 'LH',
                'method_row' => 'lhh',
                'group_sort' => 0,
                'row_sort' => 0,
                'method_sort' => 0,
                'show' => 1,
                'status' => 1,
                'total' => 100,
                'created_at' => NULL,
                'updated_at' => '2019-05-27 16:38:06',
            ),
            13 => 
            array (
                'id' => 98,
                'series_id' => 'ssc',
                'lottery_name' => '重庆时时彩',
                'lottery_id' => 'cqssc',
                'method_id' => 'LHWB',
                'method_name' => '龙虎万百',
                'method_group' => 'LH',
                'method_row' => 'lhh',
                'group_sort' => 0,
                'row_sort' => 0,
                'method_sort' => 0,
                'show' => 1,
                'status' => 1,
                'total' => 100,
                'created_at' => NULL,
                'updated_at' => '2019-05-27 16:38:06',
            ),
            14 => 
            array (
                'id' => 99,
                'series_id' => 'ssc',
                'lottery_name' => '重庆时时彩',
                'lottery_id' => 'cqssc',
                'method_id' => 'LHWS',
                'method_name' => '龙虎万十',
                'method_group' => 'LH',
                'method_row' => 'lhh',
                'group_sort' => 0,
                'row_sort' => 0,
                'method_sort' => 0,
                'show' => 1,
                'status' => 1,
                'total' => 100,
                'created_at' => NULL,
                'updated_at' => '2019-05-27 16:38:06',
            ),
            15 => 
            array (
                'id' => 100,
                'series_id' => 'ssc',
                'lottery_name' => '重庆时时彩',
                'lottery_id' => 'cqssc',
                'method_id' => 'LHWG',
                'method_name' => '龙虎万个',
                'method_group' => 'LH',
                'method_row' => 'lhh',
                'group_sort' => 0,
                'row_sort' => 0,
                'method_sort' => 0,
                'show' => 1,
                'status' => 1,
                'total' => 100,
                'created_at' => NULL,
                'updated_at' => '2019-05-27 16:38:06',
            ),
            16 => 
            array (
                'id' => 101,
                'series_id' => 'ssc',
                'lottery_name' => '重庆时时彩',
                'lottery_id' => 'cqssc',
                'method_id' => 'LHQB',
                'method_name' => '龙虎千百',
                'method_group' => 'LH',
                'method_row' => 'lhh',
                'group_sort' => 0,
                'row_sort' => 0,
                'method_sort' => 0,
                'show' => 1,
                'status' => 1,
                'total' => 100,
                'created_at' => NULL,
                'updated_at' => '2019-05-27 16:38:06',
            ),
            17 => 
            array (
                'id' => 102,
                'series_id' => 'ssc',
                'lottery_name' => '重庆时时彩',
                'lottery_id' => 'cqssc',
                'method_id' => 'LHQS',
                'method_name' => '龙虎千十',
                'method_group' => 'LH',
                'method_row' => 'lhh',
                'group_sort' => 0,
                'row_sort' => 0,
                'method_sort' => 0,
                'show' => 1,
                'status' => 1,
                'total' => 100,
                'created_at' => NULL,
                'updated_at' => '2019-05-27 16:38:06',
            ),
            18 => 
            array (
                'id' => 103,
                'series_id' => 'ssc',
                'lottery_name' => '重庆时时彩',
                'lottery_id' => 'cqssc',
                'method_id' => 'LHQG',
                'method_name' => '龙虎千个',
                'method_group' => 'LH',
                'method_row' => 'lhh',
                'group_sort' => 0,
                'row_sort' => 0,
                'method_sort' => 0,
                'show' => 1,
                'status' => 1,
                'total' => 100,
                'created_at' => NULL,
                'updated_at' => '2019-05-27 16:38:06',
            ),
            19 => 
            array (
                'id' => 104,
                'series_id' => 'ssc',
                'lottery_name' => '重庆时时彩',
                'lottery_id' => 'cqssc',
                'method_id' => 'LHBS',
                'method_name' => '龙虎百十',
                'method_group' => 'LH',
                'method_row' => 'lhh',
                'group_sort' => 0,
                'row_sort' => 0,
                'method_sort' => 0,
                'show' => 1,
                'status' => 1,
                'total' => 100,
                'created_at' => NULL,
                'updated_at' => '2019-05-27 16:38:06',
            ),
            20 => 
            array (
                'id' => 105,
                'series_id' => 'ssc',
                'lottery_name' => '重庆时时彩',
                'lottery_id' => 'cqssc',
                'method_id' => 'LHBG',
                'method_name' => '龙虎百个',
                'method_group' => 'LH',
                'method_row' => 'lhh',
                'group_sort' => 0,
                'row_sort' => 0,
                'method_sort' => 0,
                'show' => 1,
                'status' => 1,
                'total' => 100,
                'created_at' => NULL,
                'updated_at' => '2019-05-27 16:38:06',
            ),
            21 => 
            array (
                'id' => 106,
                'series_id' => 'ssc',
                'lottery_name' => '重庆时时彩',
                'lottery_id' => 'cqssc',
                'method_id' => 'LHSG',
                'method_name' => '龙虎十个',
                'method_group' => 'LH',
                'method_row' => 'lhh',
                'group_sort' => 0,
                'row_sort' => 0,
                'method_sort' => 0,
                'show' => 1,
                'status' => 1,
                'total' => 100,
                'created_at' => NULL,
                'updated_at' => '2019-05-27 16:38:06',
            ),
            22 => 
            array (
                'id' => 187,
                'series_id' => 'ssc',
                'lottery_name' => '新疆时时彩',
                'lottery_id' => 'xjssc',
                'method_id' => 'HBDW31',
                'method_name' => '后三一码不定位',
                'method_group' => 'BDW',
                'method_row' => '3budingwei',
                'group_sort' => 0,
                'row_sort' => 0,
                'method_sort' => 0,
                'show' => 1,
                'status' => 1,
                'total' => 1000,
                'created_at' => NULL,
                'updated_at' => '2019-05-27 16:38:04',
            ),
            23 => 
            array (
                'id' => 188,
                'series_id' => 'ssc',
                'lottery_name' => '新疆时时彩',
                'lottery_id' => 'xjssc',
                'method_id' => 'QBDW31',
                'method_name' => '前三一码不定位',
                'method_group' => 'BDW',
                'method_row' => '3budingwei',
                'group_sort' => 0,
                'row_sort' => 0,
                'method_sort' => 0,
                'show' => 1,
                'status' => 1,
                'total' => 1000,
                'created_at' => NULL,
                'updated_at' => '2019-05-27 16:22:37',
            ),
            24 => 
            array (
                'id' => 189,
                'series_id' => 'ssc',
                'lottery_name' => '新疆时时彩',
                'lottery_id' => 'xjssc',
                'method_id' => 'HBDW32',
                'method_name' => '后三二码不定位',
                'method_group' => 'BDW',
                'method_row' => '3budingwei',
                'group_sort' => 0,
                'row_sort' => 0,
                'method_sort' => 0,
                'show' => 1,
                'status' => 1,
                'total' => 1000,
                'created_at' => NULL,
                'updated_at' => '2019-05-27 16:38:05',
            ),
            25 => 
            array (
                'id' => 190,
                'series_id' => 'ssc',
                'lottery_name' => '新疆时时彩',
                'lottery_id' => 'xjssc',
                'method_id' => 'QBDW32',
                'method_name' => '前三二码不定位',
                'method_group' => 'BDW',
                'method_row' => '3budingwei',
                'group_sort' => 0,
                'row_sort' => 0,
                'method_sort' => 0,
                'show' => 1,
                'status' => 1,
                'total' => 1000,
                'created_at' => NULL,
                'updated_at' => '2019-05-27 16:22:37',
            ),
            26 => 
            array (
                'id' => 191,
                'series_id' => 'ssc',
                'lottery_name' => '新疆时时彩',
                'lottery_id' => 'xjssc',
                'method_id' => 'BDW41',
                'method_name' => '四星一码不定位',
                'method_group' => 'BDW',
                'method_row' => '4budingwei',
                'group_sort' => 0,
                'row_sort' => 0,
                'method_sort' => 0,
                'show' => 1,
                'status' => 1,
                'total' => 10000,
                'created_at' => NULL,
                'updated_at' => '2019-05-27 16:38:05',
            ),
            27 => 
            array (
                'id' => 192,
                'series_id' => 'ssc',
                'lottery_name' => '新疆时时彩',
                'lottery_id' => 'xjssc',
                'method_id' => 'BDW42',
                'method_name' => '四星二码不定位',
                'method_group' => 'BDW',
                'method_row' => '4budingwei',
                'group_sort' => 0,
                'row_sort' => 0,
                'method_sort' => 0,
                'show' => 1,
                'status' => 1,
                'total' => 10000,
                'created_at' => NULL,
                'updated_at' => '2019-05-27 16:38:05',
            ),
            28 => 
            array (
                'id' => 193,
                'series_id' => 'ssc',
                'lottery_name' => '新疆时时彩',
                'lottery_id' => 'xjssc',
                'method_id' => 'BDW52',
                'method_name' => '五星二码不定位',
                'method_group' => 'BDW',
                'method_row' => '5budingwei',
                'group_sort' => 0,
                'row_sort' => 0,
                'method_sort' => 0,
                'show' => 1,
                'status' => 1,
                'total' => 100000,
                'created_at' => NULL,
                'updated_at' => '2019-05-27 16:38:05',
            ),
            29 => 
            array (
                'id' => 194,
                'series_id' => 'ssc',
                'lottery_name' => '新疆时时彩',
                'lottery_id' => 'xjssc',
                'method_id' => 'BDW53',
                'method_name' => '五星三码不定位',
                'method_group' => 'BDW',
                'method_row' => '5budingwei',
                'group_sort' => 0,
                'row_sort' => 0,
                'method_sort' => 0,
                'show' => 1,
                'status' => 1,
                'total' => 100000,
                'created_at' => NULL,
                'updated_at' => '2019-05-27 16:38:05',
            ),
            30 => 
            array (
                'id' => 199,
                'series_id' => 'ssc',
                'lottery_name' => '新疆时时彩',
                'lottery_id' => 'xjssc',
                'method_id' => 'YFFS',
                'method_name' => '一帆风顺',
                'method_group' => 'QW',
                'method_row' => 'quwei',
                'group_sort' => 0,
                'row_sort' => 0,
                'method_sort' => 0,
                'show' => 1,
                'status' => 1,
                'total' => 100000,
                'created_at' => NULL,
                'updated_at' => '2019-05-27 16:38:05',
            ),
            31 => 
            array (
                'id' => 200,
                'series_id' => 'ssc',
                'lottery_name' => '新疆时时彩',
                'lottery_id' => 'xjssc',
                'method_id' => 'HSCS',
                'method_name' => '好事成双',
                'method_group' => 'QW',
                'method_row' => 'quwei',
                'group_sort' => 0,
                'row_sort' => 0,
                'method_sort' => 0,
                'show' => 1,
                'status' => 1,
                'total' => 100000,
                'created_at' => NULL,
                'updated_at' => '2019-05-27 16:38:05',
            ),
            32 => 
            array (
                'id' => 201,
                'series_id' => 'ssc',
                'lottery_name' => '新疆时时彩',
                'lottery_id' => 'xjssc',
                'method_id' => 'SXBX',
                'method_name' => '三星报喜',
                'method_group' => 'QW',
                'method_row' => 'quwei',
                'group_sort' => 0,
                'row_sort' => 0,
                'method_sort' => 0,
                'show' => 1,
                'status' => 1,
                'total' => 100000,
                'created_at' => NULL,
                'updated_at' => '2019-05-27 16:38:05',
            ),
            33 => 
            array (
                'id' => 202,
                'series_id' => 'ssc',
                'lottery_name' => '新疆时时彩',
                'lottery_id' => 'xjssc',
                'method_id' => 'SJFC',
                'method_name' => '四季发财',
                'method_group' => 'QW',
                'method_row' => 'quwei',
                'group_sort' => 0,
                'row_sort' => 0,
                'method_sort' => 0,
                'show' => 1,
                'status' => 1,
                'total' => 100000,
                'created_at' => NULL,
                'updated_at' => '2019-05-27 16:38:06',
            ),
            34 => 
            array (
                'id' => 203,
                'series_id' => 'ssc',
                'lottery_name' => '新疆时时彩',
                'lottery_id' => 'xjssc',
                'method_id' => 'LHWQ',
                'method_name' => '龙虎万千',
                'method_group' => 'LH',
                'method_row' => 'lhh',
                'group_sort' => 0,
                'row_sort' => 0,
                'method_sort' => 0,
                'show' => 1,
                'status' => 1,
                'total' => 100,
                'created_at' => NULL,
                'updated_at' => '2019-05-27 16:38:06',
            ),
            35 => 
            array (
                'id' => 204,
                'series_id' => 'ssc',
                'lottery_name' => '新疆时时彩',
                'lottery_id' => 'xjssc',
                'method_id' => 'LHWB',
                'method_name' => '龙虎万百',
                'method_group' => 'LH',
                'method_row' => 'lhh',
                'group_sort' => 0,
                'row_sort' => 0,
                'method_sort' => 0,
                'show' => 1,
                'status' => 1,
                'total' => 100,
                'created_at' => NULL,
                'updated_at' => '2019-05-27 16:38:06',
            ),
            36 => 
            array (
                'id' => 205,
                'series_id' => 'ssc',
                'lottery_name' => '新疆时时彩',
                'lottery_id' => 'xjssc',
                'method_id' => 'LHWS',
                'method_name' => '龙虎万十',
                'method_group' => 'LH',
                'method_row' => 'lhh',
                'group_sort' => 0,
                'row_sort' => 0,
                'method_sort' => 0,
                'show' => 1,
                'status' => 1,
                'total' => 100,
                'created_at' => NULL,
                'updated_at' => '2019-05-27 16:38:06',
            ),
            37 => 
            array (
                'id' => 206,
                'series_id' => 'ssc',
                'lottery_name' => '新疆时时彩',
                'lottery_id' => 'xjssc',
                'method_id' => 'LHWG',
                'method_name' => '龙虎万个',
                'method_group' => 'LH',
                'method_row' => 'lhh',
                'group_sort' => 0,
                'row_sort' => 0,
                'method_sort' => 0,
                'show' => 1,
                'status' => 1,
                'total' => 100,
                'created_at' => NULL,
                'updated_at' => '2019-05-27 16:38:06',
            ),
            38 => 
            array (
                'id' => 207,
                'series_id' => 'ssc',
                'lottery_name' => '新疆时时彩',
                'lottery_id' => 'xjssc',
                'method_id' => 'LHQB',
                'method_name' => '龙虎千百',
                'method_group' => 'LH',
                'method_row' => 'lhh',
                'group_sort' => 0,
                'row_sort' => 0,
                'method_sort' => 0,
                'show' => 1,
                'status' => 1,
                'total' => 100,
                'created_at' => NULL,
                'updated_at' => '2019-05-27 16:38:06',
            ),
            39 => 
            array (
                'id' => 208,
                'series_id' => 'ssc',
                'lottery_name' => '新疆时时彩',
                'lottery_id' => 'xjssc',
                'method_id' => 'LHQS',
                'method_name' => '龙虎千十',
                'method_group' => 'LH',
                'method_row' => 'lhh',
                'group_sort' => 0,
                'row_sort' => 0,
                'method_sort' => 0,
                'show' => 1,
                'status' => 1,
                'total' => 100,
                'created_at' => NULL,
                'updated_at' => '2019-05-27 16:38:06',
            ),
            40 => 
            array (
                'id' => 209,
                'series_id' => 'ssc',
                'lottery_name' => '新疆时时彩',
                'lottery_id' => 'xjssc',
                'method_id' => 'LHQG',
                'method_name' => '龙虎千个',
                'method_group' => 'LH',
                'method_row' => 'lhh',
                'group_sort' => 0,
                'row_sort' => 0,
                'method_sort' => 0,
                'show' => 1,
                'status' => 1,
                'total' => 100,
                'created_at' => NULL,
                'updated_at' => '2019-05-27 16:38:06',
            ),
            41 => 
            array (
                'id' => 210,
                'series_id' => 'ssc',
                'lottery_name' => '新疆时时彩',
                'lottery_id' => 'xjssc',
                'method_id' => 'LHBS',
                'method_name' => '龙虎百十',
                'method_group' => 'LH',
                'method_row' => 'lhh',
                'group_sort' => 0,
                'row_sort' => 0,
                'method_sort' => 0,
                'show' => 1,
                'status' => 1,
                'total' => 100,
                'created_at' => NULL,
                'updated_at' => '2019-05-27 16:38:06',
            ),
            42 => 
            array (
                'id' => 211,
                'series_id' => 'ssc',
                'lottery_name' => '新疆时时彩',
                'lottery_id' => 'xjssc',
                'method_id' => 'LHBG',
                'method_name' => '龙虎百个',
                'method_group' => 'LH',
                'method_row' => 'lhh',
                'group_sort' => 0,
                'row_sort' => 0,
                'method_sort' => 0,
                'show' => 1,
                'status' => 1,
                'total' => 100,
                'created_at' => NULL,
                'updated_at' => '2019-05-27 16:38:06',
            ),
            43 => 
            array (
                'id' => 212,
                'series_id' => 'ssc',
                'lottery_name' => '新疆时时彩',
                'lottery_id' => 'xjssc',
                'method_id' => 'LHSG',
                'method_name' => '龙虎十个',
                'method_group' => 'LH',
                'method_row' => 'lhh',
                'group_sort' => 0,
                'row_sort' => 0,
                'method_sort' => 0,
                'show' => 1,
                'status' => 1,
                'total' => 100,
                'created_at' => NULL,
                'updated_at' => '2019-05-27 16:38:06',
            ),
            44 => 
            array (
                'id' => 293,
                'series_id' => 'ssc',
                'lottery_name' => '黑龙江时时彩',
                'lottery_id' => 'hljssc',
                'method_id' => 'HBDW31',
                'method_name' => '后三一码不定位',
                'method_group' => 'BDW',
                'method_row' => '3budingwei',
                'group_sort' => 0,
                'row_sort' => 0,
                'method_sort' => 0,
                'show' => 1,
                'status' => 1,
                'total' => 1000,
                'created_at' => NULL,
                'updated_at' => '2019-05-27 16:38:04',
            ),
            45 => 
            array (
                'id' => 294,
                'series_id' => 'ssc',
                'lottery_name' => '黑龙江时时彩',
                'lottery_id' => 'hljssc',
                'method_id' => 'QBDW31',
                'method_name' => '前三一码不定位',
                'method_group' => 'BDW',
                'method_row' => '3budingwei',
                'group_sort' => 0,
                'row_sort' => 0,
                'method_sort' => 0,
                'show' => 1,
                'status' => 1,
                'total' => 1000,
                'created_at' => NULL,
                'updated_at' => '2019-05-27 16:22:37',
            ),
            46 => 
            array (
                'id' => 295,
                'series_id' => 'ssc',
                'lottery_name' => '黑龙江时时彩',
                'lottery_id' => 'hljssc',
                'method_id' => 'HBDW32',
                'method_name' => '后三二码不定位',
                'method_group' => 'BDW',
                'method_row' => '3budingwei',
                'group_sort' => 0,
                'row_sort' => 0,
                'method_sort' => 0,
                'show' => 1,
                'status' => 1,
                'total' => 1000,
                'created_at' => NULL,
                'updated_at' => '2019-05-27 16:38:05',
            ),
            47 => 
            array (
                'id' => 296,
                'series_id' => 'ssc',
                'lottery_name' => '黑龙江时时彩',
                'lottery_id' => 'hljssc',
                'method_id' => 'QBDW32',
                'method_name' => '前三二码不定位',
                'method_group' => 'BDW',
                'method_row' => '3budingwei',
                'group_sort' => 0,
                'row_sort' => 0,
                'method_sort' => 0,
                'show' => 1,
                'status' => 1,
                'total' => 1000,
                'created_at' => NULL,
                'updated_at' => '2019-05-27 16:22:37',
            ),
            48 => 
            array (
                'id' => 297,
                'series_id' => 'ssc',
                'lottery_name' => '黑龙江时时彩',
                'lottery_id' => 'hljssc',
                'method_id' => 'BDW41',
                'method_name' => '四星一码不定位',
                'method_group' => 'BDW',
                'method_row' => '4budingwei',
                'group_sort' => 0,
                'row_sort' => 0,
                'method_sort' => 0,
                'show' => 1,
                'status' => 1,
                'total' => 10000,
                'created_at' => NULL,
                'updated_at' => '2019-05-27 16:38:05',
            ),
            49 => 
            array (
                'id' => 298,
                'series_id' => 'ssc',
                'lottery_name' => '黑龙江时时彩',
                'lottery_id' => 'hljssc',
                'method_id' => 'BDW42',
                'method_name' => '四星二码不定位',
                'method_group' => 'BDW',
                'method_row' => '4budingwei',
                'group_sort' => 0,
                'row_sort' => 0,
                'method_sort' => 0,
                'show' => 1,
                'status' => 1,
                'total' => 10000,
                'created_at' => NULL,
                'updated_at' => '2019-05-27 16:38:05',
            ),
            50 => 
            array (
                'id' => 299,
                'series_id' => 'ssc',
                'lottery_name' => '黑龙江时时彩',
                'lottery_id' => 'hljssc',
                'method_id' => 'BDW52',
                'method_name' => '五星二码不定位',
                'method_group' => 'BDW',
                'method_row' => '5budingwei',
                'group_sort' => 0,
                'row_sort' => 0,
                'method_sort' => 0,
                'show' => 1,
                'status' => 1,
                'total' => 100000,
                'created_at' => NULL,
                'updated_at' => '2019-05-27 16:38:05',
            ),
            51 => 
            array (
                'id' => 300,
                'series_id' => 'ssc',
                'lottery_name' => '黑龙江时时彩',
                'lottery_id' => 'hljssc',
                'method_id' => 'BDW53',
                'method_name' => '五星三码不定位',
                'method_group' => 'BDW',
                'method_row' => '5budingwei',
                'group_sort' => 0,
                'row_sort' => 0,
                'method_sort' => 0,
                'show' => 1,
                'status' => 1,
                'total' => 100000,
                'created_at' => NULL,
                'updated_at' => '2019-05-27 16:38:05',
            ),
            52 => 
            array (
                'id' => 305,
                'series_id' => 'ssc',
                'lottery_name' => '黑龙江时时彩',
                'lottery_id' => 'hljssc',
                'method_id' => 'YFFS',
                'method_name' => '一帆风顺',
                'method_group' => 'QW',
                'method_row' => 'quwei',
                'group_sort' => 0,
                'row_sort' => 0,
                'method_sort' => 0,
                'show' => 1,
                'status' => 1,
                'total' => 100000,
                'created_at' => NULL,
                'updated_at' => '2019-05-27 16:38:05',
            ),
            53 => 
            array (
                'id' => 306,
                'series_id' => 'ssc',
                'lottery_name' => '黑龙江时时彩',
                'lottery_id' => 'hljssc',
                'method_id' => 'HSCS',
                'method_name' => '好事成双',
                'method_group' => 'QW',
                'method_row' => 'quwei',
                'group_sort' => 0,
                'row_sort' => 0,
                'method_sort' => 0,
                'show' => 1,
                'status' => 1,
                'total' => 100000,
                'created_at' => NULL,
                'updated_at' => '2019-05-27 16:38:05',
            ),
            54 => 
            array (
                'id' => 307,
                'series_id' => 'ssc',
                'lottery_name' => '黑龙江时时彩',
                'lottery_id' => 'hljssc',
                'method_id' => 'SXBX',
                'method_name' => '三星报喜',
                'method_group' => 'QW',
                'method_row' => 'quwei',
                'group_sort' => 0,
                'row_sort' => 0,
                'method_sort' => 0,
                'show' => 1,
                'status' => 1,
                'total' => 100000,
                'created_at' => NULL,
                'updated_at' => '2019-05-27 16:38:05',
            ),
            55 => 
            array (
                'id' => 308,
                'series_id' => 'ssc',
                'lottery_name' => '黑龙江时时彩',
                'lottery_id' => 'hljssc',
                'method_id' => 'SJFC',
                'method_name' => '四季发财',
                'method_group' => 'QW',
                'method_row' => 'quwei',
                'group_sort' => 0,
                'row_sort' => 0,
                'method_sort' => 0,
                'show' => 1,
                'status' => 1,
                'total' => 100000,
                'created_at' => NULL,
                'updated_at' => '2019-05-27 16:38:06',
            ),
            56 => 
            array (
                'id' => 309,
                'series_id' => 'ssc',
                'lottery_name' => '黑龙江时时彩',
                'lottery_id' => 'hljssc',
                'method_id' => 'LHWQ',
                'method_name' => '龙虎万千',
                'method_group' => 'LH',
                'method_row' => 'lhh',
                'group_sort' => 0,
                'row_sort' => 0,
                'method_sort' => 0,
                'show' => 1,
                'status' => 1,
                'total' => 100,
                'created_at' => NULL,
                'updated_at' => '2019-05-27 16:38:06',
            ),
            57 => 
            array (
                'id' => 310,
                'series_id' => 'ssc',
                'lottery_name' => '黑龙江时时彩',
                'lottery_id' => 'hljssc',
                'method_id' => 'LHWB',
                'method_name' => '龙虎万百',
                'method_group' => 'LH',
                'method_row' => 'lhh',
                'group_sort' => 0,
                'row_sort' => 0,
                'method_sort' => 0,
                'show' => 1,
                'status' => 1,
                'total' => 100,
                'created_at' => NULL,
                'updated_at' => '2019-05-27 16:38:06',
            ),
            58 => 
            array (
                'id' => 311,
                'series_id' => 'ssc',
                'lottery_name' => '黑龙江时时彩',
                'lottery_id' => 'hljssc',
                'method_id' => 'LHWS',
                'method_name' => '龙虎万十',
                'method_group' => 'LH',
                'method_row' => 'lhh',
                'group_sort' => 0,
                'row_sort' => 0,
                'method_sort' => 0,
                'show' => 1,
                'status' => 1,
                'total' => 100,
                'created_at' => NULL,
                'updated_at' => '2019-05-27 16:38:06',
            ),
            59 => 
            array (
                'id' => 312,
                'series_id' => 'ssc',
                'lottery_name' => '黑龙江时时彩',
                'lottery_id' => 'hljssc',
                'method_id' => 'LHWG',
                'method_name' => '龙虎万个',
                'method_group' => 'LH',
                'method_row' => 'lhh',
                'group_sort' => 0,
                'row_sort' => 0,
                'method_sort' => 0,
                'show' => 1,
                'status' => 1,
                'total' => 100,
                'created_at' => NULL,
                'updated_at' => '2019-05-27 16:38:06',
            ),
            60 => 
            array (
                'id' => 313,
                'series_id' => 'ssc',
                'lottery_name' => '黑龙江时时彩',
                'lottery_id' => 'hljssc',
                'method_id' => 'LHQB',
                'method_name' => '龙虎千百',
                'method_group' => 'LH',
                'method_row' => 'lhh',
                'group_sort' => 0,
                'row_sort' => 0,
                'method_sort' => 0,
                'show' => 1,
                'status' => 1,
                'total' => 100,
                'created_at' => NULL,
                'updated_at' => '2019-05-27 16:38:06',
            ),
            61 => 
            array (
                'id' => 314,
                'series_id' => 'ssc',
                'lottery_name' => '黑龙江时时彩',
                'lottery_id' => 'hljssc',
                'method_id' => 'LHQS',
                'method_name' => '龙虎千十',
                'method_group' => 'LH',
                'method_row' => 'lhh',
                'group_sort' => 0,
                'row_sort' => 0,
                'method_sort' => 0,
                'show' => 1,
                'status' => 1,
                'total' => 100,
                'created_at' => NULL,
                'updated_at' => '2019-05-27 16:38:06',
            ),
            62 => 
            array (
                'id' => 315,
                'series_id' => 'ssc',
                'lottery_name' => '黑龙江时时彩',
                'lottery_id' => 'hljssc',
                'method_id' => 'LHQG',
                'method_name' => '龙虎千个',
                'method_group' => 'LH',
                'method_row' => 'lhh',
                'group_sort' => 0,
                'row_sort' => 0,
                'method_sort' => 0,
                'show' => 1,
                'status' => 1,
                'total' => 100,
                'created_at' => NULL,
                'updated_at' => '2019-05-27 16:38:06',
            ),
            63 => 
            array (
                'id' => 316,
                'series_id' => 'ssc',
                'lottery_name' => '黑龙江时时彩',
                'lottery_id' => 'hljssc',
                'method_id' => 'LHBS',
                'method_name' => '龙虎百十',
                'method_group' => 'LH',
                'method_row' => 'lhh',
                'group_sort' => 0,
                'row_sort' => 0,
                'method_sort' => 0,
                'show' => 1,
                'status' => 1,
                'total' => 100,
                'created_at' => NULL,
                'updated_at' => '2019-05-27 16:38:06',
            ),
            64 => 
            array (
                'id' => 317,
                'series_id' => 'ssc',
                'lottery_name' => '黑龙江时时彩',
                'lottery_id' => 'hljssc',
                'method_id' => 'LHBG',
                'method_name' => '龙虎百个',
                'method_group' => 'LH',
                'method_row' => 'lhh',
                'group_sort' => 0,
                'row_sort' => 0,
                'method_sort' => 0,
                'show' => 1,
                'status' => 1,
                'total' => 100,
                'created_at' => NULL,
                'updated_at' => '2019-05-27 16:38:06',
            ),
            65 => 
            array (
                'id' => 318,
                'series_id' => 'ssc',
                'lottery_name' => '黑龙江时时彩',
                'lottery_id' => 'hljssc',
                'method_id' => 'LHSG',
                'method_name' => '龙虎十个',
                'method_group' => 'LH',
                'method_row' => 'lhh',
                'group_sort' => 0,
                'row_sort' => 0,
                'method_sort' => 0,
                'show' => 1,
                'status' => 1,
                'total' => 100,
                'created_at' => NULL,
                'updated_at' => '2019-05-27 16:38:06',
            ),
            66 => 
            array (
                'id' => 399,
                'series_id' => 'ssc',
                'lottery_name' => '中兴1分彩',
                'lottery_id' => 'zx1fc',
                'method_id' => 'HBDW31',
                'method_name' => '后三一码不定位',
                'method_group' => 'BDW',
                'method_row' => '3budingwei',
                'group_sort' => 0,
                'row_sort' => 0,
                'method_sort' => 0,
                'show' => 1,
                'status' => 1,
                'total' => 1000,
                'created_at' => NULL,
                'updated_at' => '2019-05-27 16:38:04',
            ),
            67 => 
            array (
                'id' => 400,
                'series_id' => 'ssc',
                'lottery_name' => '中兴1分彩',
                'lottery_id' => 'zx1fc',
                'method_id' => 'QBDW31',
                'method_name' => '前三一码不定位',
                'method_group' => 'BDW',
                'method_row' => '3budingwei',
                'group_sort' => 0,
                'row_sort' => 0,
                'method_sort' => 0,
                'show' => 1,
                'status' => 1,
                'total' => 1000,
                'created_at' => NULL,
                'updated_at' => '2019-05-27 16:22:37',
            ),
            68 => 
            array (
                'id' => 401,
                'series_id' => 'ssc',
                'lottery_name' => '中兴1分彩',
                'lottery_id' => 'zx1fc',
                'method_id' => 'HBDW32',
                'method_name' => '后三二码不定位',
                'method_group' => 'BDW',
                'method_row' => '3budingwei',
                'group_sort' => 0,
                'row_sort' => 0,
                'method_sort' => 0,
                'show' => 1,
                'status' => 1,
                'total' => 1000,
                'created_at' => NULL,
                'updated_at' => '2019-05-27 16:38:05',
            ),
            69 => 
            array (
                'id' => 402,
                'series_id' => 'ssc',
                'lottery_name' => '中兴1分彩',
                'lottery_id' => 'zx1fc',
                'method_id' => 'QBDW32',
                'method_name' => '前三二码不定位',
                'method_group' => 'BDW',
                'method_row' => '3budingwei',
                'group_sort' => 0,
                'row_sort' => 0,
                'method_sort' => 0,
                'show' => 1,
                'status' => 1,
                'total' => 1000,
                'created_at' => NULL,
                'updated_at' => '2019-05-27 16:22:37',
            ),
            70 => 
            array (
                'id' => 403,
                'series_id' => 'ssc',
                'lottery_name' => '中兴1分彩',
                'lottery_id' => 'zx1fc',
                'method_id' => 'BDW41',
                'method_name' => '四星一码不定位',
                'method_group' => 'BDW',
                'method_row' => '4budingwei',
                'group_sort' => 0,
                'row_sort' => 0,
                'method_sort' => 0,
                'show' => 1,
                'status' => 1,
                'total' => 10000,
                'created_at' => NULL,
                'updated_at' => '2019-05-27 16:38:05',
            ),
            71 => 
            array (
                'id' => 404,
                'series_id' => 'ssc',
                'lottery_name' => '中兴1分彩',
                'lottery_id' => 'zx1fc',
                'method_id' => 'BDW42',
                'method_name' => '四星二码不定位',
                'method_group' => 'BDW',
                'method_row' => '4budingwei',
                'group_sort' => 0,
                'row_sort' => 0,
                'method_sort' => 0,
                'show' => 1,
                'status' => 1,
                'total' => 10000,
                'created_at' => NULL,
                'updated_at' => '2019-05-27 16:38:05',
            ),
            72 => 
            array (
                'id' => 405,
                'series_id' => 'ssc',
                'lottery_name' => '中兴1分彩',
                'lottery_id' => 'zx1fc',
                'method_id' => 'BDW52',
                'method_name' => '五星二码不定位',
                'method_group' => 'BDW',
                'method_row' => '5budingwei',
                'group_sort' => 0,
                'row_sort' => 0,
                'method_sort' => 0,
                'show' => 1,
                'status' => 1,
                'total' => 100000,
                'created_at' => NULL,
                'updated_at' => '2019-05-27 16:38:05',
            ),
            73 => 
            array (
                'id' => 406,
                'series_id' => 'ssc',
                'lottery_name' => '中兴1分彩',
                'lottery_id' => 'zx1fc',
                'method_id' => 'BDW53',
                'method_name' => '五星三码不定位',
                'method_group' => 'BDW',
                'method_row' => '5budingwei',
                'group_sort' => 0,
                'row_sort' => 0,
                'method_sort' => 0,
                'show' => 1,
                'status' => 1,
                'total' => 100000,
                'created_at' => NULL,
                'updated_at' => '2019-05-27 16:38:05',
            ),
            74 => 
            array (
                'id' => 411,
                'series_id' => 'ssc',
                'lottery_name' => '中兴1分彩',
                'lottery_id' => 'zx1fc',
                'method_id' => 'YFFS',
                'method_name' => '一帆风顺',
                'method_group' => 'QW',
                'method_row' => 'quwei',
                'group_sort' => 0,
                'row_sort' => 0,
                'method_sort' => 0,
                'show' => 1,
                'status' => 1,
                'total' => 100000,
                'created_at' => NULL,
                'updated_at' => '2019-05-27 16:38:05',
            ),
            75 => 
            array (
                'id' => 412,
                'series_id' => 'ssc',
                'lottery_name' => '中兴1分彩',
                'lottery_id' => 'zx1fc',
                'method_id' => 'HSCS',
                'method_name' => '好事成双',
                'method_group' => 'QW',
                'method_row' => 'quwei',
                'group_sort' => 0,
                'row_sort' => 0,
                'method_sort' => 0,
                'show' => 1,
                'status' => 1,
                'total' => 100000,
                'created_at' => NULL,
                'updated_at' => '2019-05-27 16:38:05',
            ),
            76 => 
            array (
                'id' => 413,
                'series_id' => 'ssc',
                'lottery_name' => '中兴1分彩',
                'lottery_id' => 'zx1fc',
                'method_id' => 'SXBX',
                'method_name' => '三星报喜',
                'method_group' => 'QW',
                'method_row' => 'quwei',
                'group_sort' => 0,
                'row_sort' => 0,
                'method_sort' => 0,
                'show' => 1,
                'status' => 1,
                'total' => 100000,
                'created_at' => NULL,
                'updated_at' => '2019-05-27 16:38:05',
            ),
            77 => 
            array (
                'id' => 414,
                'series_id' => 'ssc',
                'lottery_name' => '中兴1分彩',
                'lottery_id' => 'zx1fc',
                'method_id' => 'SJFC',
                'method_name' => '四季发财',
                'method_group' => 'QW',
                'method_row' => 'quwei',
                'group_sort' => 0,
                'row_sort' => 0,
                'method_sort' => 0,
                'show' => 1,
                'status' => 1,
                'total' => 100000,
                'created_at' => NULL,
                'updated_at' => '2019-05-27 16:38:06',
            ),
            78 => 
            array (
                'id' => 415,
                'series_id' => 'ssc',
                'lottery_name' => '中兴1分彩',
                'lottery_id' => 'zx1fc',
                'method_id' => 'LHWQ',
                'method_name' => '龙虎万千',
                'method_group' => 'LH',
                'method_row' => 'lhh',
                'group_sort' => 0,
                'row_sort' => 0,
                'method_sort' => 0,
                'show' => 1,
                'status' => 1,
                'total' => 100,
                'created_at' => NULL,
                'updated_at' => '2019-05-27 16:38:06',
            ),
            79 => 
            array (
                'id' => 416,
                'series_id' => 'ssc',
                'lottery_name' => '中兴1分彩',
                'lottery_id' => 'zx1fc',
                'method_id' => 'LHWB',
                'method_name' => '龙虎万百',
                'method_group' => 'LH',
                'method_row' => 'lhh',
                'group_sort' => 0,
                'row_sort' => 0,
                'method_sort' => 0,
                'show' => 1,
                'status' => 1,
                'total' => 100,
                'created_at' => NULL,
                'updated_at' => '2019-05-27 16:38:06',
            ),
            80 => 
            array (
                'id' => 417,
                'series_id' => 'ssc',
                'lottery_name' => '中兴1分彩',
                'lottery_id' => 'zx1fc',
                'method_id' => 'LHWS',
                'method_name' => '龙虎万十',
                'method_group' => 'LH',
                'method_row' => 'lhh',
                'group_sort' => 0,
                'row_sort' => 0,
                'method_sort' => 0,
                'show' => 1,
                'status' => 1,
                'total' => 100,
                'created_at' => NULL,
                'updated_at' => '2019-05-27 16:38:06',
            ),
            81 => 
            array (
                'id' => 418,
                'series_id' => 'ssc',
                'lottery_name' => '中兴1分彩',
                'lottery_id' => 'zx1fc',
                'method_id' => 'LHWG',
                'method_name' => '龙虎万个',
                'method_group' => 'LH',
                'method_row' => 'lhh',
                'group_sort' => 0,
                'row_sort' => 0,
                'method_sort' => 0,
                'show' => 1,
                'status' => 1,
                'total' => 100,
                'created_at' => NULL,
                'updated_at' => '2019-05-27 16:38:06',
            ),
            82 => 
            array (
                'id' => 419,
                'series_id' => 'ssc',
                'lottery_name' => '中兴1分彩',
                'lottery_id' => 'zx1fc',
                'method_id' => 'LHQB',
                'method_name' => '龙虎千百',
                'method_group' => 'LH',
                'method_row' => 'lhh',
                'group_sort' => 0,
                'row_sort' => 0,
                'method_sort' => 0,
                'show' => 1,
                'status' => 1,
                'total' => 100,
                'created_at' => NULL,
                'updated_at' => '2019-05-27 16:38:06',
            ),
            83 => 
            array (
                'id' => 420,
                'series_id' => 'ssc',
                'lottery_name' => '中兴1分彩',
                'lottery_id' => 'zx1fc',
                'method_id' => 'LHQS',
                'method_name' => '龙虎千十',
                'method_group' => 'LH',
                'method_row' => 'lhh',
                'group_sort' => 0,
                'row_sort' => 0,
                'method_sort' => 0,
                'show' => 1,
                'status' => 1,
                'total' => 100,
                'created_at' => NULL,
                'updated_at' => '2019-05-27 16:38:06',
            ),
            84 => 
            array (
                'id' => 421,
                'series_id' => 'ssc',
                'lottery_name' => '中兴1分彩',
                'lottery_id' => 'zx1fc',
                'method_id' => 'LHQG',
                'method_name' => '龙虎千个',
                'method_group' => 'LH',
                'method_row' => 'lhh',
                'group_sort' => 0,
                'row_sort' => 0,
                'method_sort' => 0,
                'show' => 1,
                'status' => 1,
                'total' => 100,
                'created_at' => NULL,
                'updated_at' => '2019-05-27 16:38:06',
            ),
            85 => 
            array (
                'id' => 422,
                'series_id' => 'ssc',
                'lottery_name' => '中兴1分彩',
                'lottery_id' => 'zx1fc',
                'method_id' => 'LHBS',
                'method_name' => '龙虎百十',
                'method_group' => 'LH',
                'method_row' => 'lhh',
                'group_sort' => 0,
                'row_sort' => 0,
                'method_sort' => 0,
                'show' => 1,
                'status' => 1,
                'total' => 100,
                'created_at' => NULL,
                'updated_at' => '2019-05-27 16:38:06',
            ),
            86 => 
            array (
                'id' => 423,
                'series_id' => 'ssc',
                'lottery_name' => '中兴1分彩',
                'lottery_id' => 'zx1fc',
                'method_id' => 'LHBG',
                'method_name' => '龙虎百个',
                'method_group' => 'LH',
                'method_row' => 'lhh',
                'group_sort' => 0,
                'row_sort' => 0,
                'method_sort' => 0,
                'show' => 1,
                'status' => 1,
                'total' => 100,
                'created_at' => NULL,
                'updated_at' => '2019-05-27 16:38:06',
            ),
            87 => 
            array (
                'id' => 424,
                'series_id' => 'ssc',
                'lottery_name' => '中兴1分彩',
                'lottery_id' => 'zx1fc',
                'method_id' => 'LHSG',
                'method_name' => '龙虎十个',
                'method_group' => 'LH',
                'method_row' => 'lhh',
                'group_sort' => 0,
                'row_sort' => 0,
                'method_sort' => 0,
                'show' => 1,
                'status' => 1,
                'total' => 100,
                'created_at' => NULL,
                'updated_at' => '2019-05-27 16:38:06',
            ),
            88 => 
            array (
                'id' => 505,
                'series_id' => 'ssc',
                'lottery_name' => '腾讯分分彩',
                'lottery_id' => 'txffc',
                'method_id' => 'HBDW31',
                'method_name' => '后三一码不定位',
                'method_group' => 'BDW',
                'method_row' => '3budingwei',
                'group_sort' => 0,
                'row_sort' => 0,
                'method_sort' => 0,
                'show' => 1,
                'status' => 1,
                'total' => 1000,
                'created_at' => NULL,
                'updated_at' => '2019-05-27 16:38:05',
            ),
            89 => 
            array (
                'id' => 506,
                'series_id' => 'ssc',
                'lottery_name' => '腾讯分分彩',
                'lottery_id' => 'txffc',
                'method_id' => 'QBDW31',
                'method_name' => '前三一码不定位',
                'method_group' => 'BDW',
                'method_row' => '3budingwei',
                'group_sort' => 0,
                'row_sort' => 0,
                'method_sort' => 0,
                'show' => 1,
                'status' => 1,
                'total' => 1000,
                'created_at' => NULL,
                'updated_at' => '2019-05-27 16:22:37',
            ),
            90 => 
            array (
                'id' => 507,
                'series_id' => 'ssc',
                'lottery_name' => '腾讯分分彩',
                'lottery_id' => 'txffc',
                'method_id' => 'HBDW32',
                'method_name' => '后三二码不定位',
                'method_group' => 'BDW',
                'method_row' => '3budingwei',
                'group_sort' => 0,
                'row_sort' => 0,
                'method_sort' => 0,
                'show' => 1,
                'status' => 1,
                'total' => 1000,
                'created_at' => NULL,
                'updated_at' => '2019-05-27 16:38:05',
            ),
            91 => 
            array (
                'id' => 508,
                'series_id' => 'ssc',
                'lottery_name' => '腾讯分分彩',
                'lottery_id' => 'txffc',
                'method_id' => 'QBDW32',
                'method_name' => '前三二码不定位',
                'method_group' => 'BDW',
                'method_row' => '3budingwei',
                'group_sort' => 0,
                'row_sort' => 0,
                'method_sort' => 0,
                'show' => 1,
                'status' => 1,
                'total' => 1000,
                'created_at' => NULL,
                'updated_at' => '2019-05-27 16:22:37',
            ),
            92 => 
            array (
                'id' => 509,
                'series_id' => 'ssc',
                'lottery_name' => '腾讯分分彩',
                'lottery_id' => 'txffc',
                'method_id' => 'BDW41',
                'method_name' => '四星一码不定位',
                'method_group' => 'BDW',
                'method_row' => '4budingwei',
                'group_sort' => 0,
                'row_sort' => 0,
                'method_sort' => 0,
                'show' => 1,
                'status' => 1,
                'total' => 10000,
                'created_at' => NULL,
                'updated_at' => '2019-05-27 16:38:05',
            ),
            93 => 
            array (
                'id' => 510,
                'series_id' => 'ssc',
                'lottery_name' => '腾讯分分彩',
                'lottery_id' => 'txffc',
                'method_id' => 'BDW42',
                'method_name' => '四星二码不定位',
                'method_group' => 'BDW',
                'method_row' => '4budingwei',
                'group_sort' => 0,
                'row_sort' => 0,
                'method_sort' => 0,
                'show' => 1,
                'status' => 1,
                'total' => 10000,
                'created_at' => NULL,
                'updated_at' => '2019-05-27 16:38:05',
            ),
            94 => 
            array (
                'id' => 511,
                'series_id' => 'ssc',
                'lottery_name' => '腾讯分分彩',
                'lottery_id' => 'txffc',
                'method_id' => 'BDW52',
                'method_name' => '五星二码不定位',
                'method_group' => 'BDW',
                'method_row' => '5budingwei',
                'group_sort' => 0,
                'row_sort' => 0,
                'method_sort' => 0,
                'show' => 1,
                'status' => 1,
                'total' => 100000,
                'created_at' => NULL,
                'updated_at' => '2019-05-27 16:38:05',
            ),
            95 => 
            array (
                'id' => 512,
                'series_id' => 'ssc',
                'lottery_name' => '腾讯分分彩',
                'lottery_id' => 'txffc',
                'method_id' => 'BDW53',
                'method_name' => '五星三码不定位',
                'method_group' => 'BDW',
                'method_row' => '5budingwei',
                'group_sort' => 0,
                'row_sort' => 0,
                'method_sort' => 0,
                'show' => 1,
                'status' => 1,
                'total' => 100000,
                'created_at' => NULL,
                'updated_at' => '2019-05-27 16:38:05',
            ),
            96 => 
            array (
                'id' => 517,
                'series_id' => 'ssc',
                'lottery_name' => '腾讯分分彩',
                'lottery_id' => 'txffc',
                'method_id' => 'YFFS',
                'method_name' => '一帆风顺',
                'method_group' => 'QW',
                'method_row' => 'quwei',
                'group_sort' => 0,
                'row_sort' => 0,
                'method_sort' => 0,
                'show' => 1,
                'status' => 1,
                'total' => 100000,
                'created_at' => NULL,
                'updated_at' => '2019-05-27 16:38:05',
            ),
            97 => 
            array (
                'id' => 518,
                'series_id' => 'ssc',
                'lottery_name' => '腾讯分分彩',
                'lottery_id' => 'txffc',
                'method_id' => 'HSCS',
                'method_name' => '好事成双',
                'method_group' => 'QW',
                'method_row' => 'quwei',
                'group_sort' => 0,
                'row_sort' => 0,
                'method_sort' => 0,
                'show' => 1,
                'status' => 1,
                'total' => 100000,
                'created_at' => NULL,
                'updated_at' => '2019-05-27 16:38:05',
            ),
            98 => 
            array (
                'id' => 519,
                'series_id' => 'ssc',
                'lottery_name' => '腾讯分分彩',
                'lottery_id' => 'txffc',
                'method_id' => 'SXBX',
                'method_name' => '三星报喜',
                'method_group' => 'QW',
                'method_row' => 'quwei',
                'group_sort' => 0,
                'row_sort' => 0,
                'method_sort' => 0,
                'show' => 1,
                'status' => 1,
                'total' => 100000,
                'created_at' => NULL,
                'updated_at' => '2019-05-27 16:38:05',
            ),
            99 => 
            array (
                'id' => 520,
                'series_id' => 'ssc',
                'lottery_name' => '腾讯分分彩',
                'lottery_id' => 'txffc',
                'method_id' => 'SJFC',
                'method_name' => '四季发财',
                'method_group' => 'QW',
                'method_row' => 'quwei',
                'group_sort' => 0,
                'row_sort' => 0,
                'method_sort' => 0,
                'show' => 1,
                'status' => 1,
                'total' => 100000,
                'created_at' => NULL,
                'updated_at' => '2019-05-27 16:38:06',
            ),
            100 => 
            array (
                'id' => 521,
                'series_id' => 'ssc',
                'lottery_name' => '腾讯分分彩',
                'lottery_id' => 'txffc',
                'method_id' => 'LHWQ',
                'method_name' => '龙虎万千',
                'method_group' => 'LH',
                'method_row' => 'lhh',
                'group_sort' => 0,
                'row_sort' => 0,
                'method_sort' => 0,
                'show' => 1,
                'status' => 1,
                'total' => 100,
                'created_at' => NULL,
                'updated_at' => '2019-05-27 16:38:06',
            ),
            101 => 
            array (
                'id' => 522,
                'series_id' => 'ssc',
                'lottery_name' => '腾讯分分彩',
                'lottery_id' => 'txffc',
                'method_id' => 'LHWB',
                'method_name' => '龙虎万百',
                'method_group' => 'LH',
                'method_row' => 'lhh',
                'group_sort' => 0,
                'row_sort' => 0,
                'method_sort' => 0,
                'show' => 1,
                'status' => 1,
                'total' => 100,
                'created_at' => NULL,
                'updated_at' => '2019-05-27 16:38:06',
            ),
            102 => 
            array (
                'id' => 523,
                'series_id' => 'ssc',
                'lottery_name' => '腾讯分分彩',
                'lottery_id' => 'txffc',
                'method_id' => 'LHWS',
                'method_name' => '龙虎万十',
                'method_group' => 'LH',
                'method_row' => 'lhh',
                'group_sort' => 0,
                'row_sort' => 0,
                'method_sort' => 0,
                'show' => 1,
                'status' => 1,
                'total' => 100,
                'created_at' => NULL,
                'updated_at' => '2019-05-27 16:38:06',
            ),
            103 => 
            array (
                'id' => 524,
                'series_id' => 'ssc',
                'lottery_name' => '腾讯分分彩',
                'lottery_id' => 'txffc',
                'method_id' => 'LHWG',
                'method_name' => '龙虎万个',
                'method_group' => 'LH',
                'method_row' => 'lhh',
                'group_sort' => 0,
                'row_sort' => 0,
                'method_sort' => 0,
                'show' => 1,
                'status' => 1,
                'total' => 100,
                'created_at' => NULL,
                'updated_at' => '2019-05-27 16:38:06',
            ),
            104 => 
            array (
                'id' => 525,
                'series_id' => 'ssc',
                'lottery_name' => '腾讯分分彩',
                'lottery_id' => 'txffc',
                'method_id' => 'LHQB',
                'method_name' => '龙虎千百',
                'method_group' => 'LH',
                'method_row' => 'lhh',
                'group_sort' => 0,
                'row_sort' => 0,
                'method_sort' => 0,
                'show' => 1,
                'status' => 1,
                'total' => 100,
                'created_at' => NULL,
                'updated_at' => '2019-05-27 16:38:06',
            ),
            105 => 
            array (
                'id' => 526,
                'series_id' => 'ssc',
                'lottery_name' => '腾讯分分彩',
                'lottery_id' => 'txffc',
                'method_id' => 'LHQS',
                'method_name' => '龙虎千十',
                'method_group' => 'LH',
                'method_row' => 'lhh',
                'group_sort' => 0,
                'row_sort' => 0,
                'method_sort' => 0,
                'show' => 1,
                'status' => 1,
                'total' => 100,
                'created_at' => NULL,
                'updated_at' => '2019-05-27 16:38:06',
            ),
            106 => 
            array (
                'id' => 527,
                'series_id' => 'ssc',
                'lottery_name' => '腾讯分分彩',
                'lottery_id' => 'txffc',
                'method_id' => 'LHQG',
                'method_name' => '龙虎千个',
                'method_group' => 'LH',
                'method_row' => 'lhh',
                'group_sort' => 0,
                'row_sort' => 0,
                'method_sort' => 0,
                'show' => 1,
                'status' => 1,
                'total' => 100,
                'created_at' => NULL,
                'updated_at' => '2019-05-27 16:38:06',
            ),
            107 => 
            array (
                'id' => 528,
                'series_id' => 'ssc',
                'lottery_name' => '腾讯分分彩',
                'lottery_id' => 'txffc',
                'method_id' => 'LHBS',
                'method_name' => '龙虎百十',
                'method_group' => 'LH',
                'method_row' => 'lhh',
                'group_sort' => 0,
                'row_sort' => 0,
                'method_sort' => 0,
                'show' => 1,
                'status' => 1,
                'total' => 100,
                'created_at' => NULL,
                'updated_at' => '2019-05-27 16:38:06',
            ),
            108 => 
            array (
                'id' => 529,
                'series_id' => 'ssc',
                'lottery_name' => '腾讯分分彩',
                'lottery_id' => 'txffc',
                'method_id' => 'LHBG',
                'method_name' => '龙虎百个',
                'method_group' => 'LH',
                'method_row' => 'lhh',
                'group_sort' => 0,
                'row_sort' => 0,
                'method_sort' => 0,
                'show' => 1,
                'status' => 1,
                'total' => 100,
                'created_at' => NULL,
                'updated_at' => '2019-05-27 16:38:06',
            ),
            109 => 
            array (
                'id' => 530,
                'series_id' => 'ssc',
                'lottery_name' => '腾讯分分彩',
                'lottery_id' => 'txffc',
                'method_id' => 'LHSG',
                'method_name' => '龙虎十个',
                'method_group' => 'LH',
                'method_row' => 'lhh',
                'group_sort' => 0,
                'row_sort' => 0,
                'method_sort' => 0,
                'show' => 1,
                'status' => 1,
                'total' => 100,
                'created_at' => NULL,
                'updated_at' => '2019-05-27 16:38:06',
            ),
            110 => 
            array (
                'id' => 906,
                'series_id' => 'p3p5',
                'lottery_name' => '排列35',
                'lottery_id' => 'p3p5',
                'method_id' => 'QBDW31',
                'method_name' => '前三一码不定位',
                'method_group' => 'BDW',
                'method_row' => 'budingwei',
                'group_sort' => 0,
                'row_sort' => 0,
                'method_sort' => 0,
                'show' => 1,
                'status' => 1,
                'total' => 1000,
                'created_at' => NULL,
                'updated_at' => '2019-05-27 16:22:37',
            ),
            111 => 
            array (
                'id' => 907,
                'series_id' => 'p3p5',
                'lottery_name' => '排列35',
                'lottery_id' => 'p3p5',
                'method_id' => 'QBDW32',
                'method_name' => '前三二码不定位',
                'method_group' => 'BDW',
                'method_row' => 'budingwei',
                'group_sort' => 0,
                'row_sort' => 0,
                'method_sort' => 0,
                'show' => 1,
                'status' => 1,
                'total' => 1000,
                'created_at' => NULL,
                'updated_at' => '2019-05-27 16:22:37',
            ),
            112 => 
            array (
                'id' => 910,
                'series_id' => 'pk10',
                'lottery_name' => '北京PK10',
                'lottery_id' => 'bjpk10',
                'method_id' => 'PKQZX1',
                'method_name' => '第一名复式',
                'method_group' => 'CDY',
                'method_row' => 'diyiming',
                'group_sort' => 0,
                'row_sort' => 0,
                'method_sort' => 0,
                'show' => 1,
                'status' => 1,
                'total' => 10,
                'created_at' => NULL,
                'updated_at' => '2019-05-27 16:36:40',
            ),
            113 => 
            array (
                'id' => 912,
                'series_id' => 'pk10',
                'lottery_name' => '北京PK10',
                'lottery_id' => 'bjpk10',
                'method_id' => 'PKQD2',
                'method_name' => '第二名复式',
                'method_group' => 'CQ2',
                'method_row' => 'dierming',
                'group_sort' => 0,
                'row_sort' => 0,
                'method_sort' => 0,
                'show' => 1,
                'status' => 1,
                'total' => 10,
                'created_at' => NULL,
                'updated_at' => '2019-05-27 16:36:40',
            ),
            114 => 
            array (
                'id' => 916,
                'series_id' => 'pk10',
                'lottery_name' => '北京PK10',
                'lottery_id' => 'bjpk10',
                'method_id' => 'PKQD3',
                'method_name' => '第三名复式',
                'method_group' => 'CQ3',
                'method_row' => 'disanming',
                'group_sort' => 0,
                'row_sort' => 0,
                'method_sort' => 0,
                'show' => 1,
                'status' => 1,
                'total' => 10,
                'created_at' => NULL,
                'updated_at' => '2019-05-27 16:36:41',
            ),
            115 => 
            array (
                'id' => 920,
                'series_id' => 'pk10',
                'lottery_name' => '北京PK10',
                'lottery_id' => 'bjpk10',
                'method_id' => 'PKQD4',
                'method_name' => '第四名复式',
                'method_group' => 'CQ4',
                'method_row' => 'disiming',
                'group_sort' => 0,
                'row_sort' => 0,
                'method_sort' => 0,
                'show' => 1,
                'status' => 1,
                'total' => 10,
                'created_at' => NULL,
                'updated_at' => '2019-05-27 16:36:41',
            ),
            116 => 
            array (
                'id' => 924,
                'series_id' => 'pk10',
                'lottery_name' => '北京PK10',
                'lottery_id' => 'bjpk10',
                'method_id' => 'PKQD5',
                'method_name' => '第五名复式',
                'method_group' => 'CQ5',
                'method_row' => 'diwuming',
                'group_sort' => 0,
                'row_sort' => 0,
                'method_sort' => 0,
                'show' => 1,
                'status' => 1,
                'total' => 10,
                'created_at' => NULL,
                'updated_at' => '2019-05-27 16:36:41',
            ),
            117 => 
            array (
                'id' => 934,
                'series_id' => 'pk10',
                'lottery_name' => '急速飞艇',
                'lottery_id' => 'ftpk10',
                'method_id' => 'PKQZX1',
                'method_name' => '第一名复式',
                'method_group' => 'CDY',
                'method_row' => 'diyiming',
                'group_sort' => 0,
                'row_sort' => 0,
                'method_sort' => 0,
                'show' => 1,
                'status' => 1,
                'total' => 10,
                'created_at' => NULL,
                'updated_at' => '2019-05-27 16:36:40',
            ),
            118 => 
            array (
                'id' => 936,
                'series_id' => 'pk10',
                'lottery_name' => '急速飞艇',
                'lottery_id' => 'ftpk10',
                'method_id' => 'PKQD2',
                'method_name' => '第二名复式',
                'method_group' => 'CQ2',
                'method_row' => 'dierming',
                'group_sort' => 0,
                'row_sort' => 0,
                'method_sort' => 0,
                'show' => 1,
                'status' => 1,
                'total' => 10,
                'created_at' => NULL,
                'updated_at' => '2019-05-27 16:36:40',
            ),
            119 => 
            array (
                'id' => 940,
                'series_id' => 'pk10',
                'lottery_name' => '急速飞艇',
                'lottery_id' => 'ftpk10',
                'method_id' => 'PKQD3',
                'method_name' => '第三名复式',
                'method_group' => 'CQ3',
                'method_row' => 'disanming',
                'group_sort' => 0,
                'row_sort' => 0,
                'method_sort' => 0,
                'show' => 1,
                'status' => 1,
                'total' => 10,
                'created_at' => NULL,
                'updated_at' => '2019-05-27 16:36:41',
            ),
            120 => 
            array (
                'id' => 944,
                'series_id' => 'pk10',
                'lottery_name' => '急速飞艇',
                'lottery_id' => 'ftpk10',
                'method_id' => 'PKQD4',
                'method_name' => '第四名复式',
                'method_group' => 'CQ4',
                'method_row' => 'disiming',
                'group_sort' => 0,
                'row_sort' => 0,
                'method_sort' => 0,
                'show' => 1,
                'status' => 1,
                'total' => 10,
                'created_at' => NULL,
                'updated_at' => '2019-05-27 16:36:41',
            ),
            121 => 
            array (
                'id' => 948,
                'series_id' => 'pk10',
                'lottery_name' => '急速飞艇',
                'lottery_id' => 'ftpk10',
                'method_id' => 'PKQD5',
                'method_name' => '第五名复式',
                'method_group' => 'CQ5',
                'method_row' => 'diwuming',
                'group_sort' => 0,
                'row_sort' => 0,
                'method_sort' => 0,
                'show' => 1,
                'status' => 1,
                'total' => 10,
                'created_at' => NULL,
                'updated_at' => '2019-05-27 16:36:41',
            ),
            122 => 
            array (
                'id' => 958,
                'series_id' => 'pk10',
                'lottery_name' => '中兴PK10',
                'lottery_id' => 'zxpk10',
                'method_id' => 'PKQZX1',
                'method_name' => '第一名复式',
                'method_group' => 'CDY',
                'method_row' => 'diyiming',
                'group_sort' => 0,
                'row_sort' => 0,
                'method_sort' => 0,
                'show' => 1,
                'status' => 1,
                'total' => 10,
                'created_at' => NULL,
                'updated_at' => '2019-05-27 16:36:40',
            ),
            123 => 
            array (
                'id' => 960,
                'series_id' => 'pk10',
                'lottery_name' => '中兴PK10',
                'lottery_id' => 'zxpk10',
                'method_id' => 'PKQD2',
                'method_name' => '第二名复式',
                'method_group' => 'CQ2',
                'method_row' => 'dierming',
                'group_sort' => 0,
                'row_sort' => 0,
                'method_sort' => 0,
                'show' => 1,
                'status' => 1,
                'total' => 10,
                'created_at' => NULL,
                'updated_at' => '2019-05-27 16:36:40',
            ),
            124 => 
            array (
                'id' => 964,
                'series_id' => 'pk10',
                'lottery_name' => '中兴PK10',
                'lottery_id' => 'zxpk10',
                'method_id' => 'PKQD3',
                'method_name' => '第三名复式',
                'method_group' => 'CQ3',
                'method_row' => 'disanming',
                'group_sort' => 0,
                'row_sort' => 0,
                'method_sort' => 0,
                'show' => 1,
                'status' => 1,
                'total' => 10,
                'created_at' => NULL,
                'updated_at' => '2019-05-27 16:36:41',
            ),
            125 => 
            array (
                'id' => 968,
                'series_id' => 'pk10',
                'lottery_name' => '中兴PK10',
                'lottery_id' => 'zxpk10',
                'method_id' => 'PKQD4',
                'method_name' => '第四名复式',
                'method_group' => 'CQ4',
                'method_row' => 'disiming',
                'group_sort' => 0,
                'row_sort' => 0,
                'method_sort' => 0,
                'show' => 1,
                'status' => 1,
                'total' => 10,
                'created_at' => NULL,
                'updated_at' => '2019-05-27 16:36:41',
            ),
            126 => 
            array (
                'id' => 972,
                'series_id' => 'pk10',
                'lottery_name' => '中兴PK10',
                'lottery_id' => 'zxpk10',
                'method_id' => 'PKQD5',
                'method_name' => '第五名复式',
                'method_group' => 'CQ5',
                'method_row' => 'diwuming',
                'group_sort' => 0,
                'row_sort' => 0,
                'method_sort' => 0,
                'show' => 1,
                'status' => 1,
                'total' => 10,
                'created_at' => NULL,
                'updated_at' => '2019-05-27 16:36:41',
            ),
        ));
        
        
    }
}