<?php

use Illuminate\Database\Seeder;

class LotteryIssueRulesTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('lottery_issue_rules')->delete();
        
        \DB::table('lottery_issue_rules')->insert(array (
            0 => 
            array (
                'id' => 1,
                'lottery_id' => 'cqssc',
                'lottery_name' => '重庆时时彩',
                'begin_time' => '00:10:00',
                'end_time' => '03:10:00',
                'issue_seconds' => 1200,
                'first_time' => '00:30:00',
                'adjust_time' => 30,
                'encode_time' => 5,
                'issue_count' => 9,
                'status' => 1,
                'created_at' => '2019-04-29 15:22:08',
                'updated_at' => NULL,
            ),
            1 => 
            array (
                'id' => 2,
                'lottery_id' => 'cqssc',
                'lottery_name' => '重庆时时彩',
                'begin_time' => '07:10:00',
                'end_time' => '23:50:00',
                'issue_seconds' => 1200,
                'first_time' => '07:30:00',
                'adjust_time' => 45,
                'encode_time' => 5,
                'issue_count' => 50,
                'status' => 1,
                'created_at' => '2019-04-29 15:22:08',
                'updated_at' => NULL,
            ),
            2 => 
            array (
                'id' => 3,
                'lottery_id' => 'hljssc',
                'lottery_name' => '黑龙江时时彩',
                'begin_time' => '08:40:00',
                'end_time' => '22:40:00',
                'issue_seconds' => 1200,
                'first_time' => '09:00:00',
                'adjust_time' => 120,
                'encode_time' => 10,
                'issue_count' => 42,
                'status' => 1,
                'created_at' => '2019-04-29 15:22:08',
                'updated_at' => NULL,
            ),
            3 => 
            array (
                'id' => 4,
                'lottery_id' => 'xjssc',
                'lottery_name' => '新疆时时彩',
                'begin_time' => '10:00:00',
                'end_time' => '02:00:00',
                'issue_seconds' => 1200,
                'first_time' => '10:20:00',
                'adjust_time' => 120,
                'encode_time' => 10,
                'issue_count' => 48,
                'status' => 1,
                'created_at' => '2019-04-29 15:22:09',
                'updated_at' => NULL,
            ),
            4 => 
            array (
                'id' => 5,
                'lottery_id' => 'zx1fc',
                'lottery_name' => '中兴1分彩',
                'begin_time' => '00:00:00',
                'end_time' => '00:00:00',
                'issue_seconds' => 60,
                'first_time' => '00:01:00',
                'adjust_time' => 0,
                'encode_time' => 0,
                'issue_count' => 1440,
                'status' => 1,
                'created_at' => '2019-04-29 15:22:09',
                'updated_at' => NULL,
            ),
            5 => 
            array (
                'id' => 6,
                'lottery_id' => 'txffc',
                'lottery_name' => '腾讯分分彩',
                'begin_time' => '00:00:00',
                'end_time' => '00:00:00',
                'issue_seconds' => 60,
                'first_time' => '00:01:00',
                'adjust_time' => 0,
                'encode_time' => 0,
                'issue_count' => 1440,
                'status' => 1,
                'created_at' => '2019-04-29 15:22:09',
                'updated_at' => NULL,
            ),
            6 => 
            array (
                'id' => 7,
                'lottery_id' => 'sd115',
                'lottery_name' => '山东11选5',
                'begin_time' => '08:41:00',
                'end_time' => '23:01:00',
                'issue_seconds' => 1200,
                'first_time' => '09:01:00',
                'adjust_time' => 90,
                'encode_time' => 60,
                'issue_count' => 43,
                'status' => 1,
                'created_at' => '2019-04-29 15:22:10',
                'updated_at' => NULL,
            ),
            7 => 
            array (
                'id' => 8,
                'lottery_id' => 'gd115',
                'lottery_name' => '广东11选5',
                'begin_time' => '09:10:00',
                'end_time' => '23:10:00',
                'issue_seconds' => 1200,
                'first_time' => '09:30:00',
                'adjust_time' => 60,
                'encode_time' => 60,
                'issue_count' => 42,
                'status' => 1,
                'created_at' => '2019-04-29 15:22:10',
                'updated_at' => NULL,
            ),
            8 => 
            array (
                'id' => 9,
                'lottery_id' => 'sx115',
                'lottery_name' => '山西11选5',
                'begin_time' => '08:26:00',
                'end_time' => '00:06:00',
                'issue_seconds' => 1200,
                'first_time' => '08:46:00',
                'adjust_time' => 120,
                'encode_time' => 60,
                'issue_count' => 47,
                'status' => 1,
                'created_at' => '2019-04-29 15:22:10',
                'updated_at' => NULL,
            ),
            9 => 
            array (
                'id' => 10,
                'lottery_id' => 'sh115',
                'lottery_name' => '上海11选5',
                'begin_time' => '09:00:00',
                'end_time' => '00:00:00',
                'issue_seconds' => 1200,
                'first_time' => '09:20:00',
                'adjust_time' => 120,
                'encode_time' => 60,
                'issue_count' => 45,
                'status' => 1,
                'created_at' => '2019-04-29 15:22:10',
                'updated_at' => NULL,
            ),
            10 => 
            array (
                'id' => 11,
                'lottery_id' => 'jx115',
                'lottery_name' => '江西十一选5',
                'begin_time' => '10:00:00',
                'end_time' => '02:00:00',
                'issue_seconds' => 1200,
                'first_time' => '10:20:00',
                'adjust_time' => 120,
                'encode_time' => 60,
                'issue_count' => 42,
                'status' => 1,
                'created_at' => '2019-04-29 15:22:11',
                'updated_at' => NULL,
            ),
            11 => 
            array (
                'id' => 12,
                'lottery_id' => 'zx115',
                'lottery_name' => '中兴十一选5',
                'begin_time' => '00:00:00',
                'end_time' => '00:00:00',
                'issue_seconds' => 60,
                'first_time' => '00:01:00',
                'adjust_time' => 0,
                'encode_time' => 0,
                'issue_count' => 1440,
                'status' => 1,
                'created_at' => '2019-04-29 15:22:11',
                'updated_at' => NULL,
            ),
            12 => 
            array (
                'id' => 13,
                'lottery_id' => 'jsk3',
                'lottery_name' => '江苏快3',
                'begin_time' => '08:30:00',
                'end_time' => '22:10:00',
                'issue_seconds' => 1200,
                'first_time' => '08:50:00',
                'adjust_time' => 180,
                'encode_time' => 5,
                'issue_count' => 41,
                'status' => 1,
                'created_at' => '2019-04-29 15:22:11',
                'updated_at' => NULL,
            ),
            13 => 
            array (
                'id' => 14,
                'lottery_id' => 'ahk3',
                'lottery_name' => '安徽快三',
                'begin_time' => '08:40:00',
                'end_time' => '22:00:00',
                'issue_seconds' => 1200,
                'first_time' => '09:00:00',
                'adjust_time' => 180,
                'encode_time' => 5,
                'issue_count' => 40,
                'status' => 1,
                'created_at' => '2019-04-29 15:22:12',
                'updated_at' => NULL,
            ),
            14 => 
            array (
                'id' => 15,
                'lottery_id' => 'gsk3',
                'lottery_name' => '甘肃快3',
                'begin_time' => '09:59:00',
                'end_time' => '21:59:00',
                'issue_seconds' => 1200,
                'first_time' => '10:19:00',
                'adjust_time' => 120,
                'encode_time' => 60,
                'issue_count' => 36,
                'status' => 1,
                'created_at' => '2019-04-29 15:22:12',
                'updated_at' => NULL,
            ),
            15 => 
            array (
                'id' => 16,
                'lottery_id' => 'hnk3',
                'lottery_name' => '河南快3',
                'begin_time' => '08:34:00',
                'end_time' => '22:34:00',
                'issue_seconds' => 1200,
                'first_time' => '08:54:00',
                'adjust_time' => 120,
                'encode_time' => 60,
                'issue_count' => 42,
                'status' => 1,
                'created_at' => '2019-04-29 15:22:12',
                'updated_at' => NULL,
            ),
            16 => 
            array (
                'id' => 17,
                'lottery_id' => 'zxk3',
                'lottery_name' => '中兴快3',
                'begin_time' => '00:00:00',
                'end_time' => '00:00:00',
                'issue_seconds' => 60,
                'first_time' => '00:01:00',
                'adjust_time' => 0,
                'encode_time' => 0,
                'issue_count' => 1440,
                'status' => 1,
                'created_at' => '2019-04-29 15:22:12',
                'updated_at' => NULL,
            ),
            17 => 
            array (
                'id' => 18,
                'lottery_id' => 'fc3d',
                'lottery_name' => '福彩3D',
                'begin_time' => '20:20:00',
                'end_time' => '20:20:00',
                'issue_seconds' => 87000,
                'first_time' => '20:30:00',
                'adjust_time' => 600,
                'encode_time' => 600,
                'issue_count' => 1,
                'status' => 1,
                'created_at' => '2019-04-29 15:22:13',
                'updated_at' => NULL,
            ),
            18 => 
            array (
                'id' => 19,
                'lottery_id' => 'zx3d',
                'lottery_name' => '中兴3D',
                'begin_time' => '00:00:00',
                'end_time' => '00:00:00',
                'issue_seconds' => 60,
                'first_time' => '00:01:00',
                'adjust_time' => 0,
                'encode_time' => 0,
                'issue_count' => 1440,
                'status' => 1,
                'created_at' => '2019-04-29 15:22:13',
                'updated_at' => NULL,
            ),
            19 => 
            array (
                'id' => 20,
                'lottery_id' => 'p3p5',
                'lottery_name' => '排列35',
                'begin_time' => '20:20:00',
                'end_time' => '20:20:00',
                'issue_seconds' => 87000,
                'first_time' => '20:30:00',
                'adjust_time' => 1800,
                'encode_time' => 1800,
                'issue_count' => 1,
                'status' => 1,
                'created_at' => '2019-04-29 15:22:13',
                'updated_at' => NULL,
            ),
            20 => 
            array (
                'id' => 21,
                'lottery_id' => 'bjpk10',
                'lottery_name' => '北京赛车PK10',
                'begin_time' => '09:10:00',
                'end_time' => '23:50:00',
                'issue_seconds' => 1200,
                'first_time' => '09:30:00',
                'adjust_time' => 60,
                'encode_time' => 0,
                'issue_count' => 44,
                'status' => 1,
                'created_at' => '2019-04-29 15:22:13',
                'updated_at' => NULL,
            ),
            21 => 
            array (
                'id' => 22,
                'lottery_id' => 'ftpk10',
                'lottery_name' => '急速飞艇',
                'begin_time' => '00:00:00',
                'end_time' => '00:00:00',
                'issue_seconds' => 60,
                'first_time' => '00:01:00',
                'adjust_time' => 0,
                'encode_time' => 0,
                'issue_count' => 1440,
                'status' => 1,
                'created_at' => '2019-04-29 15:22:14',
                'updated_at' => NULL,
            ),
            22 => 
            array (
                'id' => 23,
                'lottery_id' => 'zxpk10',
                'lottery_name' => '中兴PK10',
                'begin_time' => '00:00:00',
                'end_time' => '00:00:00',
                'issue_seconds' => 60,
                'first_time' => '00:01:00',
                'adjust_time' => 0,
                'encode_time' => 0,
                'issue_count' => 1440,
                'status' => 1,
                'created_at' => '2019-04-29 15:22:15',
                'updated_at' => NULL,
            ),
        ));
        
        
    }
}