<?php

use Illuminate\Database\Seeder;

class SysConfiguresTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('sys_configures')->delete();
        
        \DB::table('sys_configures')->insert(array (
            0 => 
            array (
                'id' => 1,
                'pid' => 0,
                'rid' => '',
                'sign' => 'web',
                'name' => '网站',
                'description' => NULL,
                'value' => '',
                'add_admin_id' => 0,
                'last_update_admin_id' => 0,
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            1 => 
            array (
                'id' => 2,
                'pid' => 0,
                'rid' => '',
                'sign' => 'finance',
                'name' => '财务',
                'description' => NULL,
                'value' => '',
                'add_admin_id' => 0,
                'last_update_admin_id' => 0,
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            2 => 
            array (
                'id' => 3,
                'pid' => 0,
                'rid' => '',
                'sign' => 'lottery',
                'name' => '游戏',
                'description' => NULL,
                'value' => '',
                'add_admin_id' => 0,
                'last_update_admin_id' => 0,
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            3 => 
            array (
                'id' => 5,
                'pid' => 0,
                'rid' => '',
                'sign' => 'user',
                'name' => '用户',
                'description' => NULL,
                'value' => '',
                'add_admin_id' => 0,
                'last_update_admin_id' => 0,
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            4 => 
            array (
                'id' => 6,
                'pid' => 0,
                'rid' => '',
                'sign' => 'system',
                'name' => '系统',
                'description' => NULL,
                'value' => '',
                'add_admin_id' => 0,
                'last_update_admin_id' => 0,
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            5 => 
            array (
                'id' => 7,
                'pid' => 0,
                'rid' => '',
                'sign' => 'client',
                'name' => '包网',
                'description' => NULL,
                'value' => '',
                'add_admin_id' => 0,
                'last_update_admin_id' => 0,
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            6 => 
            array (
                'id' => 1001,
                'pid' => 1,
                'rid' => '',
                'sign' => 'web_site_name',
                'name' => '网站名称',
                'description' => NULL,
                'value' => '中兴',
                'add_admin_id' => 0,
                'last_update_admin_id' => 0,
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            7 => 
            array (
                'id' => 1002,
                'pid' => 1,
                'rid' => '',
                'sign' => 'web_site_title',
                'name' => '网站标题',
                'description' => NULL,
                'value' => '中兴',
                'add_admin_id' => 0,
                'last_update_admin_id' => 0,
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            8 => 
            array (
                'id' => 2001,
                'pid' => 2,
                'rid' => '',
                'sign' => 'finance_recharge_maintain',
                'name' => '充值是否维护',
                'description' => NULL,
                'value' => '0',
                'add_admin_id' => 0,
                'last_update_admin_id' => 0,
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            9 => 
            array (
                'id' => 2002,
                'pid' => 2,
                'rid' => '',
                'sign' => 'finance_withdraw_maintain',
                'name' => '提现是否维护',
                'description' => NULL,
                'value' => '0',
                'add_admin_id' => 0,
                'last_update_admin_id' => 0,
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            10 => 
            array (
                'id' => 2003,
                'pid' => 2,
                'rid' => '',
                'sign' => 'finance_card_max_bind',
                'name' => '最大绑卡数',
                'description' => NULL,
                'value' => '5',
                'add_admin_id' => 0,
                'last_update_admin_id' => 0,
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            11 => 
            array (
                'id' => 2004,
                'pid' => 2,
                'rid' => '',
                'sign' => 'finance_card_can_same_owner',
                'name' => '绑卡是否可以重名',
                'description' => NULL,
                'value' => '1',
                'add_admin_id' => 0,
                'last_update_admin_id' => 0,
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            12 => 
            array (
                'id' => 2005,
                'pid' => 2,
                'rid' => '',
                'sign' => 'finance_recharge_order_plus',
                'name' => '充值订单号修正数字',
                'description' => NULL,
                'value' => '20000000',
                'add_admin_id' => 0,
                'last_update_admin_id' => 0,
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            13 => 
            array (
                'id' => 2006,
                'pid' => 2,
                'rid' => '',
                'sign' => 'finance_notify_url',
                'name' => '回调通知地址',
                'description' => NULL,
                'value' => 'http://admin.jianwosuojian.com/callback/recharge',
                'add_admin_id' => 0,
                'last_update_admin_id' => 0,
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            14 => 
            array (
                'id' => 2007,
                'pid' => 2,
                'rid' => '',
                'sign' => 'finance_callback_url',
                'name' => '回调跳转地址',
                'description' => NULL,
                'value' => 'http://admin.jianwosuojian.com/callback/recharge',
                'add_admin_id' => 0,
                'last_update_admin_id' => 0,
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            15 => 
            array (
                'id' => 2008,
                'pid' => 2,
                'rid' => '',
                'sign' => 'finance_min_recharge',
                'name' => '最小充值',
                'description' => NULL,
                'value' => '100',
                'add_admin_id' => 0,
                'last_update_admin_id' => 0,
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            16 => 
            array (
                'id' => 2009,
                'pid' => 2,
                'rid' => '',
                'sign' => 'finance_max_recharge',
                'name' => '最大充值',
                'description' => NULL,
                'value' => '5000',
                'add_admin_id' => 0,
                'last_update_admin_id' => 0,
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            17 => 
            array (
                'id' => 2010,
                'pid' => 2,
                'rid' => '',
                'sign' => 'finance_min_withdraw',
                'name' => '最小提现',
                'description' => NULL,
                'value' => '100',
                'add_admin_id' => 0,
                'last_update_admin_id' => 0,
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            18 => 
            array (
                'id' => 2011,
                'pid' => 2,
                'rid' => '',
                'sign' => 'finance_max_withdraw',
                'name' => '最大提现',
                'description' => NULL,
                'value' => '20000',
                'add_admin_id' => 0,
                'last_update_admin_id' => 0,
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            19 => 
            array (
                'id' => 2012,
                'pid' => 2,
                'rid' => '',
                'sign' => 'finance_day_withdraw_count',
                'name' => '每日最大提现次数',
                'description' => NULL,
                'value' => '5',
                'add_admin_id' => 0,
                'last_update_admin_id' => 0,
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            20 => 
            array (
                'id' => 2013,
                'pid' => 2,
                'rid' => '',
                'sign' => 'finance_withdraw_order_plus',
                'name' => '提现订单号修正数字',
                'description' => NULL,
                'value' => '20000000',
                'add_admin_id' => 0,
                'last_update_admin_id' => 0,
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            21 => 
            array (
                'id' => 2014,
                'pid' => 2,
                'rid' => '',
                'sign' => 'finance_withdraw_time_range',
                'name' => '提现时间段',
                'description' => NULL,
                'value' => '00:00:00-02:00:00|09:00:00-24:00:00',
                'add_admin_id' => 0,
                'last_update_admin_id' => 0,
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            22 => 
            array (
                'id' => 2015,
                'pid' => 2,
                'rid' => '',
                'sign' => 'finance_card_withdraw_limit_hour',
                'name' => '提现时间段',
                'description' => NULL,
                'value' => '5',
                'add_admin_id' => 0,
                'last_update_admin_id' => 0,
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            23 => 
            array (
                'id' => 2016,
                'pid' => 2,
                'rid' => '',
                'sign' => 'finance_withdraw_need_check',
                'name' => '提现是否需要审核',
                'description' => NULL,
                'value' => '1',
                'add_admin_id' => 0,
                'last_update_admin_id' => 0,
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            24 => 
            array (
                'id' => 2017,
                'pid' => 2,
                'rid' => '',
                'sign' => 'finance_merchant_id',
                'name' => '商户号',
                'description' => NULL,
                'value' => '11800003',
                'add_admin_id' => 0,
                'last_update_admin_id' => 0,
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            25 => 
            array (
                'id' => 2018,
                'pid' => 2,
                'rid' => '',
                'sign' => 'finance_key',
                'name' => '商户秘钥',
                'description' => NULL,
                'value' => '7e3ed76395ec095b2d69fd6138f63c51',
                'add_admin_id' => 0,
                'last_update_admin_id' => 0,
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            26 => 
            array (
                'id' => 2019,
                'pid' => 2,
                'rid' => '',
                'sign' => 'finance_gateway',
                'name' => '接口地址',
                'description' => NULL,
                'value' => 'https://api.chunqiufun.com/v1_beta/',
                'add_admin_id' => 0,
                'last_update_admin_id' => 0,
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            27 => 
            array (
                'id' => 5001,
                'pid' => 5,
                'rid' => '',
                'sign' => 'user_min_prize_group',
                'name' => '开户最低奖金组',
                'description' => NULL,
                'value' => '1700',
                'add_admin_id' => 0,
                'last_update_admin_id' => 0,
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            28 => 
            array (
                'id' => 5002,
                'pid' => 5,
                'rid' => '',
                'sign' => 'user_max_prize_group',
                'name' => '开户最高奖金组',
                'description' => NULL,
                'value' => '1980',
                'add_admin_id' => 0,
                'last_update_admin_id' => 0,
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
        ));
        
        
    }
}